### ISSUE TITLE
improving Dozer Events

### ISSUE THREAD

**Issue by brabenetz** [DozerMapper/dozer#102]
Hi,
I would like to improve the Dozer Events.

1\. EventManagerAware
The Dozer Evens works fine if you only use XML without CustomConverters.
And it's clear: Dozer cannot know how deep a CustomConvertes converts some beans. Instead the custom converter should be able to fire Events.
I would introduce a EventManagerAware Interface for custom Converter (like MappingAware).

2a\. Events preMapping and postMappong
First I thought the DozerEventType.MAPPING_STARTED and DozerEventType.MAPPING_FINISHED would be fired on each Object Mapping. Now I know that it will only be called one time at Mapper.map(...).
It was confusing because with our custom converters (implements MappingAware) we called Mapper.map(...) during the mapping process. At first it locked like that the event will be fired on each Object Mapping.

What we need is a DozerEventType.PRE_OBJECT_MAPPING and DozerEventType.POST_OBJECT_MAPPING.
At the moment there is no way to Implements new events without changing all EventListener Implementations.
So I come to step 2b:

2b\. introduce new EventListener Interface
The new EventListener Interface should only have one Method: "void handleEvent(final DozerEvent event);" to implement.
The implementations can check for event.getType() to differ between the Event-Types (adding new events are no API changes).
The "old" eventListerner interface will be deprecated. An Adapter could wrap the old eventListener Interface and implement the new EventListener Interface.
As Class name I would propose the same Name "DozerEventListener" but in package "org.dozer.event" or in the same package "org.dozer" but with name like "DozerMappingEventListener"
If the generics will be removed from "DozerBeanMapper.setEventListeners(List)" the Setter could handle both: old and new Event Listener Interfaces. The Setter will wrap the old Interface with the Adapter.
With this, new Events are possible without changing any existing EventListener implementations.

Please let me know if you would like some of this changes, then I will make a forke and start with the the implementations.

with friendly regards,
Harald

ps.: sorry for my poor English

**Comment by kiliit** [comment]
What happened to this one?

It could be really nice with some more events. Fire events every time we start mapping a new object. 

The prewrite happens after the value is converted and that is too late, if you need information about which the source object and field the converter is working on now.

**Comment by brabenetz** [comment]
I will switch to Orika.
