### ISSUE TITLE
Make source object and destination object in custom converters available

### ISSUE THREAD

**Issue by maho2nd** [DozerMapper/dozer#106]
Hi,

I think i would be very useful to get the source and destination object in custom converter:
- Sometimes it is necessary to convert a field value on the basis of other field values of the source object. If you can get the source object this will be easy.
- Currenty, custom converter with the same source and destionation field type makes no sense, because always <code>convertFrom()</code> is called. If you will be able to get the source / destination object type on the basis of the source / destination object you can separate the two (or more) cases.
- Enables another solution to handle the mult-fields-to-single-field problem

Maybe i could be implemented like the <code>MapperAware</code> interface. So, the interface <code>SourceObjectAware</code> and <code>DestinationObjectAware</code> will define a <code>setSourceObject(Object object)</code> or <code>setDestinationObject(Object object)</code> in your custom mapper.

Do you think such an extension make sense?

**Comment by garethahealy** [comment]
@maho2nd ; is this still an issue?

**Comment by maho2nd** [comment]
@garethahealy Sorry, I don't use DozerMapper any more.
