### ISSUE TITLE
Prefer mapping annotations on Target instead of Source

### ISSUE THREAD

**Issue by sfrancolla** [DozerMapper/dozer#108]
My use-case is that I need to translate our core entities to many api versions.  Building annotations on the source doesn't facilitate this.  They need to be on the target.  For now, I will lazily process custom annotations on my target dtos into dozer api configuration.  Would prefer that you support annotations on target in future.  Thanks!

**Comment by garethahealy** [comment]
@sfrancolla ; is this still an issue?

**Comment by sfrancolla** [comment]
This was four years ago. I built a work-around at the time. I don't code much anymore.

If I remember correctly, the work-around was to build a pretty low-level filter or interceptor in Spring to analyze the url and dynamically set the mapping on each request right before the Dozer mapping. Since the three possible target DTOs essentially mirror the signature of the source entity but with varying scope of desired methods to be serialized, it all just worked. 

It was a complex bit of code but solid once it was complete.
