### ISSUE TITLE
deep-mapping shoud not create empty objects in destination hierarchy

### ISSUE THREAD

**Issue by metatechbe** [DozerMapper/dozer#11]
Currently, when deep-mapping is used for a field, Dozer creates empty objects in destination hierarchy, instead of copying "null" from source to destination.  
This behaviour looses relevant information : "null" means that no child objects are defined, which is different from a "empty" object (object with default values for all fields).
Fix : in method "writeDeepDestinationValue", the "destFieldValue" argument should be checked for null value.

**Comment by garethahealy** [comment]
@metatechbe ; can this issue be closed?
