### ISSUE TITLE
Avoid mapping inheritance

### ISSUE THREAD

**Issue by juantula** [DozerMapper/dozer#112]
I have a use case where inheritance needs to be avoided, for example:

``` xml
<mapping type="one-way">
        <class-a>SomeClass<class-a>
        <class-b>SomeDTO<class-b>
        <field-exclude>
            <a>createdByUser</a>
            <b>this</b>
        </field-exclude>
</mapping>
<mapping type="one-way" map-id="id" wilcard="false">
        <class-a>SomeClassParent<class-a>
        <class-b>SomeDTO<class-b>
        <field>
            <a>id</a>
            <b>id</b>
        </field>
</mapping>
```

then, if I call 

``` java
mapper.map(someClassInstance, someDTOInstance, "id");
```

what happens is that first the mapper gets the by id mapping, but then it adds inheritance mapping, happening that in fact it matches current class, not first match parents (that can be the way to fix the problem), adding all fields, when I only need the id field in my mapping.

Great tool!

**Comment by garethahealy** [comment]
@juantula ; can you please raise a PR.
