### ISSUE TITLE
Dozer isn't mapping my collection properly

### ISSUE THREAD

**Issue by BenDol** [DozerMapper/dozer#116]
I have written a thorough explanation to the issue [here](http://stackoverflow.com/questions/17354989/dozer-not-mapping-collection-properly)

Perhaps there is something that I am doing wrong here. It seems like a referencing issue of some sort? I am fairly new to Java so I could be missing something.

EDIT: Turns out this is not actually a Dozer bug. The debugging suggested that Dozer was bugging out, but I don't think that is the case. Reason I think this is because I changed over to another mapper with the same issue, so unless this new mapper has the same issue (lol) its not Dozer. If anyone has any idea as to why this is happening for me, I would appreciate the help.

My guess atm is the hibernate custom field mapper that I added. The only reason I disregarded this in the first place is because when I started debugging, it seemed that Dozer was mapping the fields before it returned from addToSet.

Cheers,
Ben

**Comment by garethahealy** [comment]
@BenDol ; is this still an issue?

**Comment by BenDol** [comment]
Could be, I haven't used Dozer in a while now.

**Comment by vmnt** [comment]
I get the same behavior as well.

**Comment by garethahealy** [comment]
@vmnt ; not that i know of, but if you create a github repo with a unit test showing the problem with the latest release, i can have a look
