### ISSUE TITLE
Inheritance mapping issue with map-ids 

### ISSUE THREAD

**Issue by CuervoSodieh** [DozerMapper/dozer#124]
Hi,

with version 5.3.2, inheritance mapping with map-ids is not always working correctly. The attached project demonstrates the issue. In my concrete usecase I have JAXB-generated classes, with a base-class that is not abstract and several classes extending this base-class. In my mapping files, I have a mapping for the common properties in the base-class plus additional mappings for class-specific extensions, as described in the docs (http://dozer.sourceforge.net/documentation/baseattributes.html). For the extending classes I am using map-ids. This setup was working nicely up until Dozer 5.3.1. With 5.3.2 the inheritance mapping was slightly changed:

The class in question is
org.dozer.classmap.ClassMappings

The following method was changed:
findInterfaceMapping

in 5.3.1:
if (destClass.isAssignableFrom(mappingDestClass) ||
(mappingDestClass.isInterface() && mappingDestClass.isAssignableFrom(destClass))) {
if (MappingUtils.getRealClass(srcClass).equals(mappingSrcClass)) {
return map;
}
}

in 5.3.2/5.4.0:
// Destination could be an abstract type. Picking up the best concrete type to use.
if ((destClass.isAssignableFrom(mappingDestClass) && isAbstract(destClass)) ||
(isInterfaceImplementation(destClass, mappingDestClass))) {
if (MappingUtils.getRealClass(srcClass).equals(mappingSrcClass)) {
return map;
}
}

I tracked the issue down to the "isAbstract(destClass)" method call, which in my case breaks the mapping. My base-class is not abstract and I cannot change this, since it was generated by JAXB. From my point of view the isAbstract() check should either be removed or appended in a separate OR clause.

Unfortunaltely github doesn't allow to attach archives (at least I don't know how)
but in the old issue tracker you can find a sample project.
http://sourceforge.net/p/dozer/bugs/355/

Can you please fix this for the next version?

Best regards,

**Comment by garethahealy** [comment]
@CuervoSodieh ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by tugas** [comment]
I'm using Dozer for a project, and when we bump from the version 5.3.1 to 5.3.2+, the mapping was broken  leading to a few problems, why the need to ensure that the class is abstract? 
I checkout Dozer, and removed the abstract validation, and everything went OK, again.
Thanks
