### ISSUE TITLE
NullPointerException thrown while mapping

### ISSUE THREAD

**Issue by amitsharma10** [DozerMapper/dozer#126]
I am using dozer 5.4.0 and class MappingProcessor is throwing NullPointerException in 
private <T> T map(Object srcObj, final Class<T> destClass, final T destObj, final String mapId); method. 

The issue is - 

```
if (destClass == null) {
  destType = (Class<T>) destObj.getClass();
  result = destObj;
} else {
  destType = destClass;
  result = null;
}
```

if destClass is null it is getting class of destObj but later in the code it is calling 

```
  Object alreadyMappedValue = mappedFields.getMappedValue(srcObj, destClass);
```

so if destClass was null in method argument, it will still be null and hence throws a NullPointerException in getMappedValue method. 

Please fix this.

**Comment by kopa** [comment]
I can confirm that this is fixed in 5.5.1 at least.
Someone should close this issue.
