### ISSUE TITLE
Deep Property Mapping does not always map correctly

### ISSUE THREAD

**Issue by ssgonzo68** [DozerMapper/dozer#137]
Example with custom mapping using XML
        <field>
            <a>ShopSection</a>
            <b>shopSectionID.shopSectionID</b>
        </field>
Class b is a JPA entity class.  Sometimes and I have not figured out why not all the time, there are issues when my option in class a wants to map to the first deptth level of shopSectionID which then gives me an difference in type error, but I know if it mapped to the second level shopSectionId, they are the same level.  I have several mapping that follow this pattern.  The is no issues when converting data from class b to a but sometimes (20% to 30% of my mappings) I have issues when converting data from a to b.  In order to work around this issue I will ususally change my set and get method and variable name of my class at level of for the b class.  Then I will change my xml mapping.
for example.
        <field>
            <a>ShopSection</a>
            <b>shopSectionIDKey.shopSectionID</b>
        </field>

**Comment by garethahealy** [comment]
@ssgonzo68 ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by ssgonzo68** [comment]
I'm not working on that project any more, therefore I don't know if it's really an issue any more. You close this.  Thanks
