### ISSUE TITLE
add custom converter class on annotation

### ISSUE THREAD

**Issue by elyrank** [DozerMapper/dozer#140]
enhancement request:
it would be great if instead of adding a custom converter and a custom mapping to the mapper , I could specify on the field annotation what is the converter to be used. something like:

 @Mapping(value = "complexObject", customConverter = MyCustomConverter.class)
    private MyComplexObjectEntity complexObject;

this would replace all this code:

```
public void initMapper() {
    mapper().setCustomConverters(Collections.<CustomConverter>singletonList(myConverter));
    BeanMappingBuilder myMapper = new BeanMappingBuilder() {

        @Override
        protected void configure() {
            mapping(ComplexObjectParent.class, ComplexObjectParentEntity.class).fields("complexObject", "complexObjectEntity",
                    FieldsMappingOptions.customConverter(MyConverter.class));
        }
    };
    mapper().addMapping(myMapper);
```

**Comment by garethahealy** [comment]
https://github.com/DozerMapper/dozer/issues/415
