### ISSUE TITLE
DSL for Conversion

### ISSUE THREAD

**Issue by sirinath** [DozerMapper/dozer#141]
Can you add a DSL for object conversion to simplify conversion using annotation than API mapping.

**Comment by garethahealy** [comment]
@sirinath ; is this still a requirement ?

**Comment by sirinath** [comment]
It will be good to have but will not affect me now as I am not using Dozer. In case I start using it I definitely would want it.

**Comment by garethahealy** [comment]
As you don't use Dozer anymore and are then only requester, closing for now due to lack of time/man power to implement.
