### ISSUE TITLE
Filling "null" as a method parameter

### ISSUE THREAD

**Issue by lcir** [DozerMapper/dozer#146]
Filling "null" as a method parameter in method call is very bad practice. It's little bit dangerous. If you want to crate metjod like this:

method(String param) and method(Properties param) and you call method in code like this: method(null). Then java is confused which one should use.

**Comment by garethahealy** [comment]
@lcir ; can you please provide more info.

**Comment by lcir** [comment]
@garethahealy Sorry, i can't. I'm not using this mapper for 3 years. Details about this issue disappeared from my head long time ago :)
