### ISSUE TITLE
create-method was not called

### ISSUE THREAD

**Issue by shaohui-liu2000** [DozerMapper/dozer#162]
I was following the example as on the documentation: http://dozer.sourceforge.net/documentation/customCreateMethod.html 

 <b create-method="someCreateMethod">createMethodType</b>

I created a static factory method in the create-method tag, and found it was never called. If I put in garbage in the someCreateMethod, I don't get any error either. Is this attribute actually being used? I am using the latest dozer 5.4.0 .

**Comment by softdays** [comment]
Reproduced with 5.5.1

**Comment by spongyT** [comment]
Reproduced with 5.4.0 and 5.5.1

**Comment by stevo11101** [comment]
Reproduced with 5.5.1

**Comment by michal-filip** [comment]
Reproduced with 5.5.1

**Comment by garethahealy** [comment]
@shaohui-liu2000 ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.
