### ISSUE TITLE
Mapping of java.time.LocalDate ... not working

### ISSUE THREAD

**Issue by danielplappert** [DozerMapper/dozer#172]
Using dozer and Java 1.8 in combination with the new Date-API causes a problem in case of LocalDate (oder LocalDateTime) properties. There are no out-of-the-box converters for these new Objects. 

In case you want to map these objects, dozer throws the following exception:

<pre>
caused by: java.lang.NoSuchMethodException: java.time.LocalDate.<init>()
    at java.lang.Class.getConstructor0(Class.java:2971) ~[na:1.8.0_05]
    at java.lang.Class.getDeclaredConstructor(Class.java:2165) ~[na:1.8.0_05]
    at org.dozer.factory.ConstructionStrategies$ByConstructor.newInstance(ConstructionStrategies.java:272) ~[dozer-5.5.1.jar:na]
</pre>

**Comment by zhugw** [comment]
Yeah, I met the same problem.
Wrapped by: org.dozer.MappingException: java.lang.NoSuchMethodException: java.time.LocalDateTime.<init>()
I 'd like to know how to solve it except change it to Date again

**Comment by GeBeater** [comment]
I am running in the same issue. So I have written a straightforward so called "dozer-jdk8-support" dependency which is also available on the maven Central Repository.

see https://github.com/GeBeater/dozer-jdk8-support

**Comment by yuranos87** [comment]
@GeBeater , it this issue present in Dozer 5.4.0 and later? I wasn't even aware of the issue, but I just checked our code and ZonedDateTime conversion works like a charm on 5.4.0.

**Comment by garethahealy** [comment]
@GeBeater ; would you be interested in raising a PR with your convertors?

**Comment by GeBeater** [comment]
@garethahealy Wow! It is great to see that dozer was rekindled. As time of converter library creation I decided against a PR because at that time I assumed that nobody would accept the request. I will have a look at the coming weekend and give you feedback whether I am able to raise a PR or not. ;-)

**Comment by garethahealy** [comment]
@GeBeater ; cool!

**Comment by GeBeater** [comment]
@garethahealy Please let me know, whether the way I implemented LocalDate Converter (see [commit ae9b60beead ...](https://github.com/GeBeater/dozer/commit/ae9b60beead9d68f740335d8556a34d177e29432) is ok. If so, I will implement the remaining converters and create a PR.

**Comment by garethahealy** [comment]
@GeBeater ; The code looks fine, but why didn't you add it to the current date convertor? that seems like more logical place than creating another convertor.

-
 https://github.com/garethahealy/dozer/blob/master/core/src/main/java/org/dozer/converters/DateConverter.java

**Comment by GeBeater** [comment]
@garethahealy Thanks for your feedback. The reason is, that the DateConverter you are mentioned handles types which contains a date and a time. So I am going to rename the converter to DateTimeConverter and extend the converter with the handling of LocalDateTime and ZonedDateTime types. The handling of types that are contains only a date as well as the handling of types that are only support a time should be placed in a separate converter (my opinion). Please let me know whether this is ok.

**Comment by garethahealy** [comment]
@GeBeater ; just to understand fully.

1. Rename DateConverter to DateTimeConverter
2. Move any Date only from DateTimeConverter to DateConverter
2. Move any Time only from DateTimeConverter to TimeConverter

Looking at the current convertor, i can only see Timestamp that is only Time related, and no Date only. All others are DateTime.

https://github.com/garethahealy/dozer/blob/master/core/src/main/java/org/dozer/converters/DateConverter.java#L61

**Comment by yuranos87** [comment]
Sorry, guys. It only worked on 5.4.0 because we used `copy-by-reference`

**Comment by francisoud** [comment]
FYI still not solved with current latest dozer version: 5.5.1.
I'm using LocaleDate withjdk 1.8.0_91, hibernate-core 5.0.11.Final & hibernate-jpa: 2.1-api-1.0.0.Final.

I'll go with the workaround: https://github.com/GeBeater/dozer-jdk8-support

**Comment by gudstrand** [comment]
I have added the dozer-jdk8-support to my project, and configured it via the xml file as directed.  But my LocalDateTime objects are still being mapped with the current datetime instead of the datetime in the original object.    Any ideas?

**Comment by francisoud** [comment]
@gudstrand surely a configuration/use problem: check http://stackoverflow.com/a/41081180/3824457 or  or https://github.com/DozerMapper/dozer#simple-example

**Comment by gudstrand** [comment]
I did everything suggested and finally just moved on. Replaced dozer with ModelMapper and it worked right out of the box.

**Comment by vguna** [comment]
Hi.

Any plans to add support for `Instant`?

**Comment by garethahealy** [comment]
@GeBeater ; hows the PR for java 8 datetime objects? Need any help?

**Comment by drozdzmic** [comment]
I can help with that.

**Comment by flkue** [comment]
You can add the copy by reference configuration as workaround until it is implemented:

```xml
<configuration>
...
    <copy-by-references>
        <copy-by-reference>java.time.*</copy-by-reference>
    </copy-by-references>
...
</configuration>
```

**Comment by FuchengLi** [comment]
Hi , I got convert issue for offsetdatatime .
org.dozer.MappingException: java.lang.NoSuchMethodException: java.time.OffsetDateTime

**Comment by Jijonty** [comment]
@FuchengLi: Had same issue. Update to dozer-core 6.2.0 and dozer-jdk8-support 1.0.4 and it works.

**Comment by garethahealy** [comment]
Java8 datetime is supported on master. Can someone check it covers their requirements please

**Comment by ralerArahal** [comment]
It's work fine. When a release with this important fix?

**Comment by kmmahesh** [comment]
I have added the dozer-jdk8-support to my project and added dozerJdk8Converters.xml under `src/main/resources` in my maven based project, as directed [here](https://github.com/GeBeater/dozer-jdk8-support#usage). But am still getting same error that of org.dozer.MappingException: java.lang.NoSuchMethodException: java.time.LocalDateTime.<init>(). Any idea what's going wrong ?

**Comment by Jijonty** [comment]
@kmmahesh Can you give us more information which dozer version do you use? You don't need dozerJdk8Converters.xml after 6.4.0

**Comment by kmmahesh** [comment]
hi @Jijonty, am using Dozer v5.5.1. Where can I get latest version 6.4.0 of Dozer. CHecked [here ](https://bintray.com/buzdin/dozer-mapper/dozer/) but it's showing 5.4.0 as latest version.
THanks.

**Comment by Jijonty** [comment]
@kmmahesh here is the latest version https://mvnrepository.com/artifact/com.github.dozermapper/dozer-core/6.4.1

**Comment by Jijonty** [comment]
@kmmahesh Not sure without playing with exact code, but you can try some of the examples from [documentation](https://dozermapper.github.io/gitbook/), like excluding fields or annotations

**Comment by kmmahesh** [comment]
@Jijonty got it as how to map selected fields, you can use Context based mapping by specifying a map-id. [Documentation](https://dozermapper.github.io/gitbook/documentation/contextmapping.html) has e.g.
Thanks.

**Comment by ad3luc** [comment]
Hi I'm still getting this error.
Is a way to fix without using the **dozer-jdk8-support**

I updated the new dependencies
```
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-core</artifactId>
    <version>6.4.1</version>
</dependency>
```
but when I call 

`dozer.map(eventNtt, EventDto.class);`

I get this:

> c.g.dozermapper.core.MappingProcessor    : Field mapping error -->
>   MapId: null
>   Type: null
>   Source parent class: com.event.ntt.Event
>   Source field name: eventTimestamp
>   Source field type: class java.time.Instant
>   Source field value: 2019-02-08T16:09:07.062Z
>   Dest parent class: com.event.dto.EventDto
>   Dest field name: eventTimestamp
>   Dest field type: java.time.Instant
> 
> com.github.dozermapper.core.MappingException: java.lang.NoSuchMethodException: java.time.Instant.<init>()

I'm doing something wrong?
I must add the support libary **dozer-jdk8-support**?

**Comment by Jijonty** [comment]
@ad3luc What I'm seeing is converter for java.time.Instant is added 2 weeks ago and probably will be pushed in next release. You can use the latest version, package and use the jar

**Comment by ad3luc** [comment]
@Jijonty I think that should be the only way until the pushed a new release...

Thanks
