### ISSUE TITLE
global configuration conflicts

### ISSUE THREAD

**Issue by allbutone** [DozerMapper/dozer#185]
here's my test case:

``` java
        List mappingFiles = new ArrayList();
        mappingFiles.add("path/to/dozer-global-configuration.xml");//contains <configuration> block
        mappingFiles.add("path/to/moduleA.mapping.xml");//contains <configuration> block

        mapper = new DozerBeanMapper();
        mapper.setMappingFiles(mappingFiles);

        mapper.map(srcObj, destObj);
```

here's the exception:

``` java
        org.dozer.MappingException: More than one global configuration found.  Only one global configuration block (<configuration></configuration>) can be specified across all mapping files.  You need to consolidate all global configuration blocks into a single one.
```

but [here](http://dozer.sourceforge.net/documentation/advancedConfiguration.html) i found:

> Dozer supports the ability to have multiple mapping files. Each of these mapping files can have their own configuration block. A mapping will inherit its configuration from the mapping file that it is stored in.

that means multiple mapping files each of which may have its own configuration block can coexist.
is it a dozer bug or something wrong with my config ? thx.

**Comment by svanderworth** [comment]
It's 2016, I'm new to dozer, and I am also confused on this point.  Any updates from the authors?

**Comment by garethahealy** [comment]
@allbutone ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by eau-de-la-seine** [comment]
Same problem here : "org.dozer.MappingException: More than one global configuration found.  Only one global configuration block (<configuration></configuration>) can be specified across all mapping files.  You need to consolidate all global configuration blocks into a single one."

When you read the FAQ (http://dozer.sourceforge.net/documentation/faq.html#component-mappings):
_Is it better to have 1 large xml mapping file or to have multiple smaller mapping files?
We recommend componentizing your mapping files instead of having 1 large mapping file._

**So where's the problem ?**

**Comment by garethahealy** [comment]
@eau-de-la-seine ; as per my last comment to @allbutone. please create a github repo showing the problem.

**Comment by eau-de-la-seine** [comment]
@garethahealy Hi, I've edited my comment, so you can see the `<configuration>` tag now. My problem is that I have a Maven module (named "A") which has a "XML Dozer" file configuration with a `<configuration>`. This module A is a dependency for my other Maven module (named "B"). But module B has also a "XML Dozer" file configuration with a `<configuration>`. My observation is, as I can see from the error message, that Dozer does not support more than once `<configuration>` per `ObjectMapper` ! It shouldn't be a limitation.

**Comment by garethahealy** [comment]
@eau-de-la-seine ; a code example which i can checkout, build and debug is 100% better than a text explanation. can you please provide.
