### ISSUE TITLE
Subclass isn't mapped using superclass mapping

### ISSUE THREAD

**Issue by dutchtoro** [DozerMapper/dozer#192]
Hi,

I have the following problem.

Mapping in the following way:

 nl.toro.PrivatePerson person = new nl.toro.PrivatePerson();
 person.setNumber(1);
 person.setName("someone");

 nl.toro2.Person person2 = mapper.map(person, nl.toro2.Person.class);

 Simple Pojo's:
 in package nl.toro
 Person
 PrivatePerson extends Person
 BusinessPerson extends Person 
 mapping to objects with same signature in package nl.toro2
 In the mapping file we have configuration for
  nl.toro.Person -> nl.toro2.Person
  nl.toro.PrivatePerson -> nl.toro2.PrivatePerson
  nl.toro.BusinessPerson -> nl.toro2.BusinessPerson

 Case:
 Calling the mapping with the Superclass nl.toro.Person (implementation of nl.toro.PrivatePerson)

 Expected:
 Get back the mapped Superclass nl.toro2.Person (implementation of nl.toro2.PrivatePerson)

 Result:
 Only Superclass is mapped and not the underlaying Subclass nl.toro2.PrivatePerson
 In version 5.3.0 and 5.3.1 this works, but in later versions in doesn't work anymore.

 The cause was the fix in org.dozer.classmap.ClassMappings in method "private ClassMap findInterfaceMapping(Class<?> destClass, Class<?> srcClass, String mapId)" for version 5.3.2:
       // Destination could be an abstract type. Picking up the best concrete type to use.
      if ((destClass.isAssignableFrom(mappingDestClass) && isAbstract(destClass)) ||
              (isInterfaceImplementation(destClass, mappingDestClass))) {
        if (MappingUtils.getRealClass(srcClass).equals(mappingSrcClass)) {
          return map;
        }
      }

If you want I have a small testproject, so mail me if you want that.      

We have a lot of classes which extends a class and where we only have to map the Super in the code, hope you can solve my problem.    

Regards,
Andre Torensma

**Comment by garethahealy** [comment]
@dutchtoro ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by dutchtoro** [comment]
Hi Gareth, thx for the reply. We stopped using Dozer almost 2 years ago. So I don't know if it's still An issue.
Regards, Andre
