### ISSUE TITLE
Ignore groovy metaClass property

### ISSUE THREAD

**Issue by Aaronlong31** [DozerMapper/dozer#194]
I can't use dozer with groovy, because of this:
org.dozer.MappingException: No read or write method found for field (metaClass) in class (xxxx)

**Comment by Aaronlong31** [comment]
@CrossfireCurt Thank you!

**Comment by MattFriedman** [comment]
I'm having the same issue now as I am using Groovy. I don't see a way to exclude `metaClass` globally so it'll have to be done for every mapping.

**Comment by CrossfireCurt** [comment]
I've switched to Orika mapper because of all these inconveniences. It's like dozer, but up to date and more flexible.

http://orika-mapper.github.io/orika-docs/

**Comment by garethahealy** [comment]
Closing as workaround provided by @CrossfireCurt
