### ISSUE TITLE
Dozer 5.5.1 is not compatible with JDK 1.5

### ISSUE THREAD

**Issue by vootan** [DozerMapper/dozer#196]
cannot access org.dozer.Mapper
[ERROR] bad class file: C:\Users\vootan.m2\repository\net\sf\dozer\dozer\5.5.1\dozer-5.5.1.jar(org/dozer/Mapper.class)
[ERROR] class file has wrong version 50.0, should be 49.0

Dozer 5.5.1 is compatible with JDK 1.5 as per documentation. But the jar is built with JDK 7. I tried to compile the source code with JDK 1.5 but dozer dependencies are not JDK 1.5 compatible. Can you please publish dozer that can be included in projects built with JDK 5? Thank you.

Naresh Voota

**Comment by garethahealy** [comment]
@vootan ; Only JDK8 is supported going forward.
