### ISSUE TITLE
Deep Mapping not working with object.value

### ISSUE THREAD

**Issue by mr0reed** [DozerMapper/dozer#202]
Hello,

i have to classes srcObj1 and srcObj2. 
srcObj1 has a field called version (type java.lang.string)
srcObj2 has an object <mypackage>.Version version with one Attribute "value" (type java.lang.string)

my mapping looks like following:
<mapping>
<class-a>srcObj1</class-a>
<class-b>srcObj2</class-b>

<field>
<a>version</a>
<b>version.value</b>
</field>
</mapping>

It seems like the value is being mapped, but i get an Exception:
"Illegal object type for the method 'setVersion' -
Expected types:
<myPackage>.Version
Actual types:
java.lang.String

When using some other deep mapping-value like
<b>someOtherNestedObject.parameterCalledOtherThanValue</b>
then the mapping works fine.
Even using a custom-converter works fine.
So therefore my question:
Ist "version.value" or even just "value" some magic word in dozer, which shouldn't be used or what am I missing? Maybe a bug?

Thanks for your help.

Regards
mr0reed

**Comment by wjn0918** [comment]
hello

i have the same error as you

this is my Source class
```
@Data
public class Source {
    private long id;
    private String info;
}
```
this is my Dest class
```
@Data
public class Dest {
    private long id;
    private Info info;
}
```
this is my Info class
```
@Data
public class Info {
    private String content;
}
```
i also set the config as you say
```
    <mapping wildcard="false">
        <class-a>com.example.Source</class-a>
        <class-b>com.example.Dest</class-b>
        <field>
            <a>info</a>
            <b>info.content</b>
        </field>
    </mapping>
```
this is my test class
```
    @Test
    public void cs() {
        Source cs = new Source();
        cs.setInfo("wjn");
        Dest map = mapper.map(cs, Dest.class);
        System.out.println(map);

    }
```
but i got the exception
```
com.github.dozermapper.core.MappingException: Illegal object type for the method 'setInfo'. 
 Expected types: 
com.example.Info
 Actual types: 
java.lang.String
```

how can i fix it 
thanks for your help
