### ISSUE TITLE
Fails to map protobuf enum when package used instead of java_package in .proto

### ISSUE THREAD

**Issue by milespomeroy** [DozerMapper/dozer#205]
```
package my.package.name;

option java_outer_classname = "Protos";

enum MyEnum {
    THING = 1;
    THUNG = 2;
}
```

When mapping the above protobuf to an Enum the mapping with fail with a Class Not Found exception. This is due to the `ProtoUtils#getEnumClassByEnumDescriptor` method:

``` java
  private static Class<? extends Enum> getEnumClassByEnumDescriptor(Descriptors.EnumDescriptor descriptor) {
    return (Class<? extends Enum>)MappingUtils.loadClass(StringUtils.join(new String[]{
            descriptor.getFile().getOptions().getJavaPackage(),
            descriptor.getFile().getOptions().getJavaOuterClassname(),
            descriptor.getFullName()}, '.'));
  }
```

Which will construct a class name of ".Protos.my.package.name.MyEnum" when it should be "my.package.name.Protos.MyEnum".

Using the `option java_package="my.package.name";` construct instead of `package my.package.name;` in the protobuf will work correctly as it's done in the existing tests. The `package my.package.name;` is a valid protobuf and gets compiled with the right java package name. I'd suggest that this construct be supported. Otherwise this should be called out in the documentation for this feature. At the very least `descriptor.getFullName()` could be changed to `descriptor.getName()` so that the `package` is not prepended to the name.

**Comment by garethahealy** [comment]
Seems related to: https://github.com/DozerMapper/dozer/pull/288 - @milespomeroy ; can you retest with latest.
