### ISSUE TITLE
Fails to map protobuf fields with underscores

### ISSUE THREAD

**Issue by milespomeroy** [DozerMapper/dozer#206]
The [Google Protobuf Style Guide](https://developers.google.com/protocol-buffers/docs/style) states that multi-word fields use a lowercase-underscore naming pattern.

The tests for Dozer proto use camelcase instead, see: [ProtoTestObjects.proto](https://github.com/DozerMapper/dozer/blob/master/proto/src/test/java/org/dozer/vo/proto/ProtoTestObjects.proto).

When the Google suggested lowercase-underscore pattern is used, Dozer fails to find the property to write to, "unable to determine write method…". The workaround is to use only single word fields or use camelcase for field names. But Dozer should be able to work with `.proto` files conforming to the style guide.

**Comment by garethahealy** [comment]
@jbq ; can you review / provide info please.

**Comment by jbq** [comment]
Problem confirmed:

- Added unit test for this: https://github.com/jbq/dozer/commit/d7c874e36ee0b0e8dd5980416d587566cc61412e
- Unit test failure at https://travis-ci.org/jbq/dozer/builds/238286827

```
Failed tests: 
  ProtoBeansMappingTest.testSnakeCaseField_toProto:287 expected:<[some value]> but was:<[]>
```
