### ISSUE TITLE
about the issue #118 : Fix Dozer mapping stops working 

### ISSUE THREAD

**Issue by tofmonaute** [DozerMapper/dozer#207]
Hi,
My name is Christophe and I have a problem with dozer that stops working after a while.
So I would like to know if the issue#118 that treat my problem  is solved in the last version of dozer (#118: https://github.com/DozerMapper/dozer/commit/a5845b1e417795640bdd10be01b9a268819f3575)
If not, I would like to know when you intend to commit the changes.
Best regards,
Christophe

**Comment by garethahealy** [comment]
Closing as no feedback from @tofmonaute

**Comment by asadabdin** [comment]
Default constructor is missing. try adding them in your class
