### ISSUE TITLE
Extract Eclipse Plugin to separate Git repo

### ISSUE THREAD

**Issue by buzdin** [DozerMapper/dozer#209]

**Comment by orange-buffalo** [comment]
I also believe that Eclipse plugin should be extracted to a separate repo. @garethahealy, have you had a chance to ponder if it makes sense to invest in supporting this plugin in scope of main Dozer project?

**Comment by garethahealy** [comment]
@orange-buffalo ; i have no experience of working on eclipse plugins, so currently, no.

**Comment by orange-buffalo** [comment]
It seems like work on this issue has been already commenced. @garethahealy, do you have write access to https://github.com/DozerMapper/dozer-eclipse-plugin? If yes, I could prepare pull requests for both repos to move the plugin.

**Comment by garethahealy** [comment]
@orange-buffalo ; am not sure, @buzdin will be able to confirm.

**Comment by buzdin** [comment]
@garethahealy sent you invite for eclipse repo. Just move it there and write that project owner is needed. Lots of stuff missing. For example proper Maven build with publication to P2 repository. And supported Eclipse version is quite outdated.

**Comment by orange-buffalo** [comment]
Looks like we're done here and can close this issue.

**Comment by buzdin** [comment]
closed
