### ISSUE TITLE
Support for immutable types

### ISSUE THREAD

**Issue by piotrdytkowski** [DozerMapper/dozer#216]
Immutable types are not supported by Dozer. When a type doesn't have a no-arg constructor and all fields are final, Dozer can't perform the mapping.
Workaround is to write a custom bean factory that creates an object with dummy values (for example nulls), but it would be great to use a constructor for object creation.

Example configuration:

``` xml
<mapping>
        <class-a>com.example.AnyType</class-a>
        <class-b use-constructor="true">com.example.ImmutableType</class-b>
        <field>
            <a>fieldA</a>
            <b>fieldB</b>
        </field>
    </mapping>
```

That would map a field to a class that looks like: 

``` java
public class ImmutableType {
  private final String fieldB;
  public ImmutableType(String fieldB) {
    this.fieldB = fieldB;
  }
  public String getFieldB() {
    return this.fieldB;
  }
}
```

Only one constructor is expected in a class, containing all fields.

**Comment by garethahealy** [comment]
https://github.com/DozerMapper/dozer/pull/218

**Comment by micd** [comment]
Need help with that?

**Comment by micd** [comment]
Need help with that?

**Comment by orange-buffalo** [comment]
@micd thanks, there is already work in progress on this issue, see #218. Any comments and feedback for the PR is welcome.
