### ISSUE TITLE
Option for configure ClassMap in polymorphism case 

### ISSUE THREAD

**Issue by josejuanmontiel** [DozerMapper/dozer#219]
Hi,

we use 5.3.1 version, we upgrade to use "Mapping Metadata Introspection" and realize that from 5.3.1 to 5.3.2 this fix http://sourceforge.net/p/dozer/bugs/300 was "resolved".

We have a "polymorphism" rest with jackson... http://wiki.fasterxml.com/JacksonPolymorphicDeserialization and we use dozer to "generic" transport from rest class model to "jackrabit class model" in this case...

In our only rest point entry... we "generic" map(source, ParentClass) and dozer "do the magic" to choose the appropiate child (that we define in dozer.xml).

How can we mix this (5.3.1) feature with "Mapping Metadata Introspection"

Thanks in advance.

**Comment by garethahealy** [comment]
@josejuanmontiel ; can you retest with v6.0.0 please.

**Comment by josejuanmontiel** [comment]
yes, but give me a few day to remember ;)

**Comment by josejuanmontiel** [comment]
yes, but give me a few day to remember ;)

**Comment by josejuanmontiel** [comment]
If i'm honest, i don't remember my "original" problem, but trying to reproduce the old referenced issue https://sourceforge.net/p/dozer/bugs/300/ y made a test org.dozer.functional_tests.InterfaceABCTest https://github.com/DozerMapper/dozer/pull/433

**Comment by josejuanmontiel** [comment]
@garethahealy I create a pull request in https://github.com/DozerMapper/dozer/pull/452
