### ISSUE TITLE
It's hardly possible to use dozer in OSGi

### ISSUE THREAD

**Issue by szhem** [DozerMapper/dozer#22]
OSGi is highly modular environment and there are a lot of OSGi containers like apache-karaf, apache-servicemix, jboss, eclipse virgo, paremus service fabric, etc.

These containers behave like application containers, i.e. we are able to deploy OSGi bundles like ordinary applications into them.

It's often necessary to have separate applications which use conversions (by means of dozer) and which must be isolated, versioned, etc. So they need completely separate dozer configurations per bundle. 

Currently it's hardly possible because of class loading issues and a lot of singletons (DozerInitializer, GlobalSettings, BeanContainer, GlobalStatistics, etc.) in the dozer. That means that all these singletons are shared across all OSGi bundles. It's also hardly possible to specify correct classloader of the bundle (because BeanContainer is singleton).

It's seems that some kind of refactoring is needed to remove all these singletons. 

Will the dozer be supported in the future? It seems that these great project becomes not very active.

**Comment by writemevenkat** [comment]
@raves I do stuck with the NoTypeConversionAvailableException exception in Fuse 6.2.1/dozer 5.5.1. It works when i deploy it for the first time and upon restarting the container shows up with NoTypeConversionAvailableException.  I tried reseting Thread Context Class Loader with Bundle Context Class Loader but no luck. Would you care to share the workaround ?

**Comment by garethahealy** [comment]
@writemevenkat ; 6.1 should be released soon which should help with OSGi classloader issues. We'd be interested in feedback, if possible.

**Comment by writemevenkat** [comment]
@garethahealy thanks for the response. is dozer 6.0.0 released ?

**Comment by garethahealy** [comment]
Yes, v6 is released
- https://github.com/DozerMapper/dozer/blob/master/docs/asciidoc/migration/v5-to-v6.adoc

**Comment by atanasov-ka** [comment]
I saw that dozer v6.1 was released. Before in v5.3 there was an error when trying to find the mapping files from bundle classloader. 

Do you know whether this issue was addressed in v6.1? 

Thanks

P.S.
The error in v5.3 is looking like this:
> Caused by: org.dozer.MappingException: Unable to locate dozer mapping file [OSGI-INF/dozer/*/Whatever-mapping.xml] in the classpath!
>     at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:87)[581:net.sf.dozer.dozer-osgi:5.3.2]
>     at org.dozer.util.MappingValidator.validateURL(MappingValidator.java:63)[581:net.sf.dozer.dozer-osgi:5.3.2]
>     at org.dozer.loader.CustomMappingsLoader.loadFromFiles(CustomMappingsLoader.java:101)[581:net.sf.dozer.dozer-osgi:5.3.2]
>     at org.dozer.loader.CustomMappingsLoader.load(CustomMappingsLoader.java:56)[581:net.sf.dozer.dozer-osgi:5.3.2]
>     at org.dozer.DozerBeanMapper.loadCustomMappings(DozerBeanMapper.java:213)[581:net.sf.dozer.dozer-osgi:5.3.2]
>     at org.dozer.DozerBeanMapper.getMappingProcessor(DozerBeanMapper.java:186)[581:net.sf.dozer.dozer-osgi:5.3.2]
>     at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:111)[581:net.sf.dozer.dozer-osgi:5.3.2]
>     at org.apache.camel.converter.dozer.DozerTypeConverter.convertTo(DozerTypeConverter.java:46)[577:org.apache.camel.camel-dozer:2.10.0.fuse-71-047]
>     at org.apache.camel.converter.dozer.DozerTypeConverter.convertTo(DozerTypeConverter.java:50)[577:org.apache.camel.camel-dozer:2.10.0.fuse-71-047]
>     at org.apache.camel.impl.converter.BaseTypeConverterRegistry.doConvertTo(BaseTypeConverterRegistry.java:253)[81:org.apache.camel.camel-core:2.10.0.fuse-71-047]
>     at org.apache.camel.impl.converter.BaseTypeConverterRegistry.mandatoryConvertTo(BaseTypeConverterRegistry.java:155)[81:org.apache.camel.camel-core:2.10.0.fuse-71-047]
>     ... 42 more

**Comment by garethahealy** [comment]
@atanasov-ka ; yes, OSGi support has improved since v5.3. But, since you are using Camel, you'd need to move to Camel 2.20 as well.
