### ISSUE TITLE
Need to convert class A to class B having lists

### ISSUE THREAD

**Issue by Guarav** [DozerMapper/dozer#221]
I have a class A as : 

```
class A {

  private String account;
  private List<String> targets;

}
```

and class B 

```
class B {
   private String account;
   private List<Custom> customTargets;
}
```

and class Custom class 

```
class Custom {
  private String target1;

  private String target2;

}
```

Now, i need to convert class A to class B, for which i got stuck at converting List<String> to List<Custom> and fill Custom.target1 to be filled with elements of List<String>

i tried 

```
<mapping type="one-way">
        <class-a>A</class-a>
        <class-b>B</class-b>


        <field>
            <a>targets</a>
            <b>customTargets</b>
            <a-hint>java.lang.String</a-hint>
            <b-hint>Custom</b-hint>
        </field>
    </mapping>

 <mapping type="one-way">
        <class-a>java.lang.String</class-a>
        <class-b>Custom</class-b>

        <field>
            <a>this</a>
            <b>target1</b>
        </field>
    </mapping>
```

But List in class B is getting converted to `List<String>` instead of `List<Custom>`.
Note : I am avoiding using custom converter here.

**Comment by TimMeissner** [comment]
+1 i got this too, must be a bug? Did you try writing a custom converter to get around the problem?

**Comment by garethahealy** [comment]
@Guarav  ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by Guarav** [comment]
It was for a very old project. I just checked, I ended up writing a custom converter.
