### ISSUE TITLE
OSGI 5.5.1 project fails due to clash with Felix Framework.

### ISSUE THREAD

**Issue by inthegarage** [DozerMapper/dozer#224]
During upgrade to the latest version of Dozer, we have some compatibility problems with one of the linked bundles.

It would seem that the package is referencing it's own OSGI framework version:
    <dependency>
      <groupId>org.apache.felix</groupId>
      <artifactId>org.apache.felix.framework</artifactId>
      <version>4.0.3</version>
      <scope>provided</scope>
    </dependency>

and here:
    <import.packages>
      org.dozer.*,
      org.osgi.framework,

Although I can't determine if this is the problem, when we load a class via the bundle context it causes the following linkage error:

java.lang.LinkageError: loader constraint violation: loader (instance of org/apa
che/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) previously initiate
d loading for a different type with name "org/osgi/framework/BundleContext"
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findCla
ss(BundleWiringImpl.java:2228)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDele
gation(BundleWiringImpl.java:1472)
        at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringIm
pl.java:75)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadCla
ss(BundleWiringImpl.java:1923)

This is running in Adobe CQ5.6.1.

The code is roughly as follows:

BundleContext bundleContext = componentContext.getBundleContext();
//Fails here:
ServiceReference ref = bundleContext.getServiceReference(MyServiceClass.class.getName());

I'd thought that a jar/bundle shouldn't really specify it's own framework version and should just "go with the flow", I may wrong here, however this just doesn't seem right to me.

Could you take a look at the problem for me, in the meantime we will have to downgrade back to 5.4.0

Many thanks

Pete

**Comment by garethahealy** [comment]
@inthegarage ; is this still a problem?

**Comment by inthegarage** [comment]
I will see if I can check this . May take a day or two.

**Comment by orange-buffalo** [comment]
This should be fixed in `master` now. #348 fixes the issue when OSGi API and Felix classes were embedded into `dozer-osgi` bundle. Now there is only one OSGi-ready artifact `dozer`, which contains only Dozer binaries.

**Comment by inthegarage** [comment]
@orange-buffalo Many thanks for that. unfortunately I'm not able to re-test this situation as I do not have the environment any-more.

**Comment by orange-buffalo** [comment]
@inthegarage thanks for the feedback. As there is no way to check the problem and its rootcause is fixed, don't you mind closing this issue?

**Comment by inthegarage** [comment]
Yes, Issue closed.

**Comment by orange-buffalo** [comment]
Thanks!
