### ISSUE TITLE
Inheritance bug or feature?

### ISSUE THREAD

**Issue by diorcety** [DozerMapper/dozer#225]
Image 4 classes

``` java
class A1 {
}
class A2 {
}
class B1 extends A1 {
}
class B2 extends A2 {
}
```

with mapping between A1 <=> A2 and B1 <=> B2 (like mapping two domains with almost same classes)

actually if i do 
B1 b1 = new B1()
...
A2 a2 = dozer.map(b1, A2.class);

the class of a2 is the same that provided in the second parameter A2.

But it shouldn't be B2? 
- indeed we ask for A2.class but B2 object is also a A2 object (inheritance)
- B2 is the most "complete" mapping that can be done with B1 and A2.class rule

**Comment by garethahealy** [comment]
@diorcety ; you do not tell dozer about B2, so how should it now you want it mapped to this type? You ask for A2, so get A2.

**Comment by diorcety** [comment]
Can't really remember the context.
