### ISSUE TITLE
The LICENSE.md file contains only the license header

### ISSUE THREAD

**Issue by puntogil** [DozerMapper/dozer#228]
The LICENSE.md file contains only the license header.
Please. Added license full text [1] and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards
[1] http://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by garethahealy** [comment]
Done.
