### ISSUE TITLE
Class level is-accessible doesn't work

### ISSUE THREAD

**Issue by ashlineldridge** [DozerMapper/dozer#23]
It's my understanding that when the `is-accessible="true"` settings is applied at the class level this should result in private fields (without getters / setters) being mapped.

For example, the following mapping...

``` xml
<mapping>
        <class-a is-accessible="true">com.example.Foo</class-a>
        <class-b is-accessible="true">com.example.FooDTO</class-b>
</mapping>
```

...should result in the private fields of `Foo` being mapped to `FooDTO` and visa versa. But the above does not work with Dozer 5.3.2.

However, when the individual fields of `Foo` and `FooDTO` are specified and is-accessible="true" is applied at the field-level the private fields are mapped correctly.

Please correct me if my understanding of how `is-accessible="true"` when applied at the class level is incorrect.

**Comment by phil-schneider** [comment]
When will 5.5.2 oder 5.6.0 be released?

**Comment by yuranos87** [comment]
@lauriharpf, will this fix work with API as well? I'm really keen on using something like:
`        return new BeanMappingBuilder() {
            @Override
            protected void configure() {
                mapping(type(typeA).accessible(true), type(typeB).accessible(true));
            }

        };`
