### ISSUE TITLE
Duplicate map id is only perform inside the same file

### ISSUE THREAD

**Issue by diorcety** [DozerMapper/dozer#233]
Here the code

``` java
 // Check to see if this is a duplicate map id, irregardless of src and dest class names. 
      // Duplicate map-ids are not allowed
      if (!MappingUtils.isBlankOrNull(classMap.getMapId())) {
        if (mapIds.contains(classMap.getMapId())) {
          throw new IllegalArgumentException("Duplicate Map Id's Found. Map Id: " + classMap.getMapId());
        }
        mapIds.add(classMap.getMapId());
      }
```

If the mapId appears in an another file this check is useless, but nevertheless it works(if src/des class is different).
Maybe the test can be remove

**Comment by garethahealy** [comment]
@diorcety  ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by diorcety** [comment]
Can't tell... i'm not working on that anymore.
