### ISSUE TITLE
MappedFieldsTracker does not consider map-id

### ISSUE THREAD

**Issue by raja-hm** [DozerMapper/dozer#238]
Hello,

I have class A, having a child classes Class B and Class C. Class C is also child for Class B. Which is cyclic relation but I avoided cyclic relation in code and want to map partial data of Class C under Class A and Partial data under Class B. I achieved this as follows with mapping using wildcard=false
&lt;mapping map-id="classA">
		&lt;class-a>classA&lt;/class-a>
		&lt;class-b>ClassA&lt;/class-b>
		&lt;field>
			&lt;a>id&lt;/a>
			&lt;b>id&lt;/b>
		&lt;/field>
		&lt;field map-id="classB">
			&lt;a>classb&lt;/a>
			&lt;b>classb&lt;/b>
		&lt;/field>		
		&lt;field map-id="classC">
			&lt;a>classc&lt;/a>
			&lt;b>classc&lt;/b>
		&lt;/field>		
&lt;/mapping>	
&lt;mapping map-id="classB">
		&lt;class-a>classB&lt;/class-a>
		&lt;class-b>ClassB&lt;/class-b>
		&lt;field>
			&lt;a>id&lt;/a>
			&lt;b>id&lt;/b>
		&lt;/field>
		&lt;field map-id="classCAgain">
			&lt;a>classc&lt;/a>
			&lt;b>classc&lt;/b>
		&lt;/field>		
&lt;/mapping>	
&lt;mapping map-id="classC">
		&lt;class-a>classC&lt;/class-a>
		&lt;class-b>ClassC&lt;/class-b>
		&lt;field>
			&lt;a>id&lt;/a>
			&lt;b>id&lt;/b>
		&lt;/field>
		&lt;field>
			&lt;a>partialA&lt;/a>
			&lt;b>partialA&lt;/b>
		&lt;/field>		
		&lt;field>
			&lt;a>partailA2&lt;/a>
			&lt;b>partialA2&lt;/b>
		&lt;/field>		
&lt;/mapping>	
&lt;mapping map-id="classCAgain">
		&lt;class-a>classC&lt;/class-a>
		&lt;class-b>ClassC&lt;/class-b>
		&lt;field>
			&lt;a>id&lt;/a>
			&lt;b>id&lt;/b>
		&lt;/field>
		&lt;field>
			&lt;a>PartialB1&lt;/a>
			&lt;b>PartialB1&lt;/b>
		&lt;/field>		
		&lt;field>
			&lt;a>PartialB2&lt;/a>
			&lt;b>PartialB2&lt;/b>
		&lt;/field>		
&lt;/mapping>	

It works fine if I have two different instances of Class C under A and B. But if I have same instance of Class C under A and B, MappedFieldsTracker just checks the object had code and declares as already mapped and I see the mapped data same under A and B which is not what i expect. The MappedFieldsTracker should also consider the map id and its mapped same object for same map id then only declare as processed otherwise it should process again and give the correct mapping based on the map id.

Raja

**Comment by jetrii** [comment]
+1 This is very annoying and has resulted in unexpected mappings.

**Comment by jetrii** [comment]
I submitted a PR with the fix, but Dozer doesn't seem that active anymore...

**Comment by lauriharpf** [comment]
Thanks for the report @raja-hm and again, thanks to @jetrii for the fix!

My understanding is that this bug appears when mapping the same instance twice with different map-id's. Commit e258aa40346196663b83a3643a1bc2f8cdee8367 has a simple regression test, which fails with the pre-#257 code and passes with the post-#257 code.

Sorry for the delay, my resources to contribute to Dozer are unfortunately quite limited at the moment. As always, pull requests and bug reports are very welcome. If you are interested in contributing more frequently, please contact @buzdin.

**Comment by jetrii** [comment]
Thank you for your hard work @lauriharpf!

**Comment by Daryonyx** [comment]
Thank you again. I encounter the same issue using a previous version. I'm happy to see that it's fixed now :)
