### ISSUE TITLE
XmlBean to XmlBean throws

### ISSUE THREAD

**Issue by SkySpiral7** [DozerMapper/dozer#246]
Attempted to map from an already existing XmlBean to another will always throw: org.apache.xmlbeans.impl.values.XmlValueNotSupportedException: Could not get a Java Date type from a Schema complex type at org.apache.xmlbeans.impl.values.XmlObjectBase.getGDateValue(XmlObjectBase.java:1648). As demonstrated by this simple unit test:

``` Java
  @Test
  public void objectToObject() {
    CarXml source = CarXml.Factory.newInstance();
    source.setMake("Ford");
    CarXml destination = CarXml.Factory.newInstance();

    new DozerBeanMapper().map(source, destination);
    Assert.assertEquals(source.getMake(), destination.getMake());
  }
```

which fails in Dozer 5.5.1 and 5.3.2. Dozer claims to support XmlBeans and mapping from source to destination concrete objects is basic functionality so this unit test should pass. Sample XSD not included because it fails for any 2 XmlBeans.

**Comment by SkySpiral7** [comment]
The test case can easily be changed to use GetWeatherByZipCode (in the Dozer test XSDs).

**Comment by garethahealy** [comment]
@SkySpiral7 ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by SkySpiral7** [comment]
@garethahealy Yes this is still an issue.

I created a branch in my fork for this: https://github.com/SkySpiral7/dozer/tree/issue/246
I haven't created a pull request to DozerMapper/dozer because my branch only includes a failing test (not a fix) so merging it would break the build.

The test was written as a top-level integration test because I don't know where the bug is coming from. I'm guessing the issue is that it is looking at GetWeatherByZipCodeImpl which (indirectly) extends XmlObjectBase which has set(java.util.Date).

Dozer should be detecting that this is an XmlBeans object and only recursively look for fields on the interfaces excluding org.apache.xmlbeans.XmlObject and above (in this case GetWeatherByZipCode only includes a single field names ZipCode).

**Comment by garethahealy** [comment]
@SkySpiral7 ; same "problem" as #247 - you need to provide the factory to dozer. See example:

https://github.com/garethahealy/dozer/commit/40f6b51cce1e4bdc0e0e5ecd2c6d8c8086310448

**Comment by SkySpiral7** [comment]
You are correct: adding a mapping and factory does solve the problem (RTFM). But why would I need a factory if an object isn't being created... [apparently](https://github.com/SkySpiral7/dozer/commit/3e19730511aff74bf49cf55723df19da673ce6e2#diff-6a28d377011eb7a2eeb4c31a317891cb) I don't.

So just like #247 I'll change this issue from "bug" to "feature request". It is very strange that I would need a mapping.xml which says to map to and from the same class with no other information (using org.dozer.vo.impl.GetWeatherByZipCodeDocumentImpl.GetWeatherByZipCodeImpl does not work). The new feature in this case would be to find the appropriate interface automatically.

**Comment by garethahealy** [comment]
XMLBeans support has been dropped due to no support for >= Java9
- https://github.com/DozerMapper/dozer/blob/7a431584c817e717a8b244756fd54819a0a1d158/docs/asciidoc/migration/v62-to-v63.adoc
