### ISSUE TITLE
ClassMap XmlBean Impl Factory not found

### ISSUE THREAD

**Issue by SkySpiral7** [DozerMapper/dozer#247]
Pasted below is a unit test class that should pass all 4 tests. But due to a bug in Dozer only 2 of them pass. The first time an XmlBean is mapped as the destination and the bean is concrete then the ClassMap object (which Dozer uses internally) will contain a reference to the XmlBean implementation and not the interface. The next time after that when that XmlBean class needs to be created Dozer will look for the Factory class on the impl class and not find it since it is in fact located on the interface class.

The 2 obvious ways to fix this are: 1) only store interface classes in ClassMap for XmlBeans (if given an impl class get it's interface instead) 2) change the way the Factory is located and if it isn't found on the class then check for it on the interface.

``` Java

import static org.junit.Assert.assertEquals;

import org.dozer.DozerBeanMapper;
import org.dozer.Mapper;
import org.dozer.vo.GetWeatherByPlaceNameResponseDocument.GetWeatherByPlaceNameResponse;
import org.dozer.vo.WeatherForecasts;
import org.junit.Before;
import org.junit.Test;

public class UT_DozerMapping {

  private Mapper mapper;
  private ForecastClass forecastBean;
  private WeatherForecasts forecastXml;

  @Before
  public void setUp() {
    mapper = new DozerBeanMapper();
    forecastBean = new ForecastClass();
    forecastBean.setPlaceName("String value");
    forecastXml = WeatherForecasts.Factory.newInstance();
  }

  @Test
  public void populateThenCreateDestination() {
    // Create a broken mapping
    mapper.map(forecastBean, forecastXml);
    assertEquals(forecastBean.getPlaceName(), forecastXml.getPlaceName());

    // Dozer now has to create the xml which it can't do because of
    // broken map.
    assertEquals(forecastBean.getPlaceName(), mapper.map(forecastBean, WeatherForecasts.class).getPlaceName());
  }

  @Test
  public void createDestinationFirst() {
    // This mapping won't be broken (java bean to xml bean interface)
    assertEquals(forecastBean.getPlaceName(), mapper.map(forecastBean, WeatherForecasts.class).getPlaceName());
    // This mapping will still work
    mapper.map(forecastBean, forecastXml);
    assertEquals(forecastBean.getPlaceName(), forecastXml.getPlaceName());
    // This mapping still won't be broken
    assertEquals(forecastBean.getPlaceName(), mapper.map(forecastBean, WeatherForecasts.class).getPlaceName());
  }

  @Test
  public void populateInnerThenCreateOuter() {
    // Create a broken mapping
    mapper.map(forecastBean, forecastXml);
    assertEquals(forecastBean.getPlaceName(), forecastXml.getPlaceName());

    WeatherResponseClass responseBean = new WeatherResponseClass();
    responseBean.setGetWeatherByPlaceNameResult(forecastBean);

    // Dozer now has to create the xml which it can't do because of
    // broken map.
    GetWeatherByPlaceNameResponse responseXml = mapper.map(responseBean, GetWeatherByPlaceNameResponse.class);
    assertEquals(responseBean.getGetWeatherByPlaceNameResult().getPlaceName(), responseXml
        .getGetWeatherByPlaceNameResult().getPlaceName());
  }

  @Test
  public void createInnerThenCreateOuter() {
    // Create correct mapping
    assertEquals(forecastBean.getPlaceName(), mapper.map(forecastBean, WeatherForecasts.class).getPlaceName());

    // then do exactly the same thing as populateInnerThenCreateOuter
    mapper.map(forecastBean, forecastXml);
    assertEquals(forecastBean.getPlaceName(), forecastXml.getPlaceName());

    WeatherResponseClass responseBean = new WeatherResponseClass();
    responseBean.setGetWeatherByPlaceNameResult(forecastBean);

    GetWeatherByPlaceNameResponse responseXml = mapper.map(responseBean, GetWeatherByPlaceNameResponse.class);
    assertEquals(responseBean.getGetWeatherByPlaceNameResult().getPlaceName(), responseXml
        .getGetWeatherByPlaceNameResult().getPlaceName());
  }

  public static class WeatherResponseClass {
    private ForecastClass getWeatherByPlaceNameResult;

    public ForecastClass getGetWeatherByPlaceNameResult() {
      return getWeatherByPlaceNameResult;
    }

    public void setGetWeatherByPlaceNameResult(ForecastClass getWeatherByPlaceNameResult) {
      this.getWeatherByPlaceNameResult = getWeatherByPlaceNameResult;
    }
  }

  public static class ForecastClass {
    private String placeName;

    public String getPlaceName() {
      return placeName;
    }

    public void setPlaceName(String placeName) {
      this.placeName = placeName;
    }
  }

}
```

**Comment by garethahealy** [comment]
@SkySpiral7 ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by SkySpiral7** [comment]
Yes this is still an issue.

I created a branch in my fork for this: https://github.com/SkySpiral7/dozer/tree/issue/247
I haven't created a pull request to DozerMapper/dozer because my branch only includes failing tests (not a fix) so merging it would break the build.

The test was written as a top-level integration test because I don't know enough about the dozer code to know which internal classes to use for a more specific test.

**Comment by garethahealy** [comment]
This can be solved by providing a mapper.xml which tells dozer what factory to use. See: https://github.com/garethahealy/dozer/commit/c4c16a618b5edb88391ad87e819474e572a444d0

You are hitting the "problem", as no mapping.xml is found [1], dozer defaults to an empty factory [2].

[1] https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/MappingProcessor.java#L1140-L1150
[2] https://github.com/DozerMapper/dozer/blob/759d68ba9faf61493ed1165c39f0985ee18aaaf8/core/src/main/java/org/dozer/classmap/ClassMapBuilder.java#L95

**Comment by SkySpiral7** [comment]
It seems that the [documentation](http://dozer.sourceforge.net/documentation/xmlbeans.html#Mapping_XMLBeans) does say to always use mapping.xml for XMLBeans so this seems to be a case of RTFM.

For the majority of our use cases dozer maps XMLBeans just fine without mapping.xml so these failure cases were unexpected. Therefore in the principle of least surprise I'd like to change this issue from "bug" to "feature request". The XMLBeans factories are easy to find so it wouldn't be difficult for dozer to find them automatically. It's also easy to know if an object is an XMLBean since they all extend the same object.

On the other hand XMLBeans was [officially retired on 2014-05-23](https://xmlbeans.apache.org/) so it would be reasonable to say "we will not add features for XMLBeans support".

**Comment by garethahealy** [comment]
XMLBeans support has been dropped due to no support for >= Java9
- https://github.com/DozerMapper/dozer/blob/7a431584c817e717a8b244756fd54819a0a1d158/docs/asciidoc/migration/v62-to-v63.adoc
