### ISSUE TITLE
Generic type "Object" preferred over hint

### ISSUE THREAD

**Issue by fullerlee** [DozerMapper/dozer#260]
Hi
I had a problem with some JAXB2-generated lists of type List<Object>.

Despite using a hint (and/or deep hint), Dozer was deriving the items to be of type Object, so the mapping to a field in the real class type was failing.

I wonder if ReflectionUtils, line 169 (if genericType != null) should be checking if the generic type is anything other than Object if a hint is present?

Thanks,
Lee

**Comment by garethahealy** [comment]
Maybe related to: https://github.com/DozerMapper/dozer/pull/241
