### ISSUE TITLE
Add mapping strategy to global configuration options

### ISSUE THREAD

**Issue by openwms** [DozerMapper/dozer#271]
We often have to map on field-level instead of property/method level and need to have a common configuration option to define the mapping strategy. To avoid explicit field mappings like this

```
        <field>
            <a is-accessible="true">color</a>
            <b is-accessible="true">color</b>
        </field>
```

we want to configure field mapping globally:

```
    <configuration>
            <mapping-type>FIELD</mapping-type>
    </configuration>
```

We do although not want to have unnecessary accessors (getter/setters) in our domain objects just to satisfy Dozer.

**Comment by ice3ider4** [comment]
+1

**Comment by yuranos87** [comment]
@openwms , do you know if someone has started working on it? Or has it been at least approved? I'm keen on looking into it myself.

**Comment by openwms** [comment]
@yuranos87 I did only a few investigations in the code to find out how it can be realizied. It shouldn't be hard to get it realized. The more tricky part is to find all occurrences where this configuration parameter needs to be considered.
@garethahealy Whats your opinion? Do you give your approval for this feature?

**Comment by garethahealy** [comment]
If one of you is happy to do the work, i am happy to review/merge.

**Comment by Shabin** [comment]
Any roadmap for implementing this?
