### ISSUE TITLE
In spring boot project, dozer map nested object failed

### ISSUE THREAD

**Issue by zhugw** [DozerMapper/dozer#273]
I just encountered a problem of using dozer to map dto to entity. See below:

```
GoodsForm:
List<GoodsPriceForm> priceList;

Goods
List<GoodsPrice> priceList;
```

when in controller, call `dozer.map(goodsForm,Goods.class)`, then iterate priceList of goods
`goods.getPriceList().forEach(p->p.setGoodsId(goods.getId()))`, at this step, it throws exception:

```
java.lang.ClassCastException: com.foo.goods.model.GoodsPrice cannot be cast to com.foo.goods.model.GoodsPrice
at com.foo.goods.service.GoodsService$$Lambda$11/310447431.accept(Unknown Source) ~[na:na]
at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_51]
```

because I used spring boot devtools and [in spring boot document](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-customizing-classload) it says

> By default, any open project in your IDE will be loaded using the “restart” classloader, and any regular .jar file will be loaded using the “base” classloader.

So exists two ClassLoader that cause this problem. If I want to solve this problem, how to modify dozer source code?

**Comment by garethahealy** [comment]
@zhugw ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by zhugw** [comment]
Wow it's been a long time,  if this weekend I have time I'll supply one demo.

**Comment by garethahealy** [comment]
@zhugw ; cool!

**Comment by zhugw** [comment]
Sorry! I cannot  reproduce it now. And more info you could see: http://stackoverflow.com/questions/33955542/a-dozer-map-exception-related-to-spring-boot-devtools/33969984#33969984

**Comment by MacGyver27** [comment]
@garethahealy this is the same issue I am having.. applied fix from the stackoverflow post and it works
```
restart.include.dozer-core=/dozer-core-6.4.1
restart.include.dozer-spring=/dozer-spring-6.4.1.jar
```
And it somehow works now.. this was something completely new to me..
