### ISSUE TITLE
Dozer-Proto Constructs Wrongly Qualified Class Name

### ISSUE THREAD

**Issue by jmferland** [DozerMapper/dozer#275]
Dozer's ProtoUtils cannot handle any proto files have that a "package x;" defined in the proto file. The reason is that ProtoUtils incorrectly calls Descriptors.FieldDescriptor.getMessageType().getFullName() when it should call Descriptors.FieldDescriptor.getMessageType().getName() instead.

If "package x;" is defined in the .proto file, then getFullName() returns "the type's fully-qualified name, within the proto language's namespace." (see JavaDocs). getName() returns the type/ java type's unqualified name, which is what we want.

**Comment by garethahealy** [comment]
Related to: https://github.com/DozerMapper/dozer/pull/288

**Comment by garethahealy** [comment]
@jmferland ; can you retest with latest please
