### ISSUE TITLE
is-accessible in global configuration

### ISSUE THREAD

**Issue by ArneLimburg** [DozerMapper/dozer#278]
Hi,
is-accessible is defined class- and field-level, so is there any reason, that it is not available in global configuration? If no, consider this a feature request ;-)

**Comment by openwms** [comment]
+1. same as here #271.

**Comment by Ice3ider** [comment]
+1

**Comment by kamaydeo** [comment]
+1

**Comment by garethahealy** [comment]
Closing as duplicate of #271
