### ISSUE TITLE
Pull request not accepted

### ISSUE THREAD

**Issue by gilbertg** [DozerMapper/dozer#281]
Hi, I submitted some code for pull request October last year, titled: 

> Implemented CustomFieldValidator to inject a point of prevention before a source field value is fetched during mapping

It's not yet been accepted, makes it hard to roll in new versions of Dozer; and (imo) adds some value.

What will it take to get such a feature in the library?
~Gilbert

**Comment by garethahealy** [comment]
https://github.com/DozerMapper/dozer/pull/266
