### ISSUE TITLE
Translating string "yyyy-MM-dd" to XmlGregorianCalendar issue

### ISSUE THREAD

**Issue by alexmanrique** [DozerMapper/dozer#289]
Hi,
any help with this?
I'm using the XmlGregorianCalendarConverter but dateFormat field of this converter (when I debug) is null (is not reading date-format element of my xml mapping configuration)
https://stackoverflow.com/questions/38634827/dozer-string-to-xmlgregoriancalendar-issue
thanks

**Comment by garethahealy** [comment]
@alexmanrique ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by alexmanrique** [comment]
Hi @garethahealy
the problem was with map-id that I was using in the custom-mapping.xml file (it didn't exist) 

old mapping file 

`<mappings xmlns="http://dozer.sourceforge.net"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://dozer.sourceforge.net http://dozer.sourceforge.net/schema/beanmapping.xsd">

    <mapping date-format="yyyy-MM-dd" map-id="non-existent-map-id">
        <class-a>org.dozer.vo.DateContainer</class-a>
        <class-b>org.dozer.vo.DateObjectDest</class-b>
        <field>
            <a>date</a>
            <b>recDate</b>
        </field>
    </mapping>
</mappings>
`
new mapping file

`<mappings xmlns="http://dozer.sourceforge.net"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://dozer.sourceforge.net http://dozer.sourceforge.net/schema/beanmapping.xsd">

    <mapping date-format="yyyy-MM-dd">
        <class-a>org.dozer.vo.DateContainer</class-a>
        <class-b>org.dozer.vo.DateObjectDest</class-b>
        <field>
            <a>date</a>
            <b>recDate</b>
        </field>
    </mapping>
</mappings>`

now this test passes 

``` java
 public void testConvert_String() throws Exception {
        Mapper mapper = getNewMapper(new String[]{"customMapping.xml"});
        DateContainer dateContainer = new DateContainer();
        dateContainer.setDate("1983-07-04");
        DateObjectDest dateObjectDest = mapper.map(dateContainer, DateObjectDest.class);
        assertEquals(1983, dateObjectDest.getRecDate().getYear());
        assertEquals(7, dateObjectDest.getRecDate().getMonth());
        assertEquals(4, dateObjectDest.getRecDate().getDay());
    } 

we can close the issue

regards
