### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.springframework.ide.eclipse.beans.ui.BeansUIImages

### ISSUE THREAD

**Issue by njaner** [DozerMapper/dozer#295]
Couldn't show content assist in any "field" field in xml view because a NCDFE error occurs.

last version of dozer eclipse plugin installed 0.8.1.
error occurs when CTRL+SPACE after "ma" (see sample file).
class test.mapping.Car exists with field "make". 
class test.mapping.CarDto exists with field "manufacturer".

**sample dozer-mapping.xml file :**
[dozerMapping.xml.txt](https://github.com/DozerMapper/dozer/files/571413/dozerMapping.xml.txt)

**Eclipse traces :**
first time
java.lang.ExceptionInInitializerError
	at org.dozer.eclipse.plugin.sourcepage.util.DozerPluginUtils.createMethodProposal(DozerPluginUtils.java:300)
Caused by: java.lang.NullPointerException
	at org.springframework.ide.eclipse.beans.ui.BeansUIImages.<clinit>(BeansUIImages.java:66)

[dozer-eclipse-first-trace.txt](https://github.com/DozerMapper/dozer/files/571433/dozer-eclipse-first-trace.txt)

then next times 

java.lang.NoClassDefFoundError: Could not initialize class org.springframework.ide.eclipse.beans.ui.BeansUIImages
	at org.dozer.eclipse.plugin.sourcepage.util.DozerPluginUtils.createMethodProposal(DozerPluginUtils.java:300)
[dozer-eclipse-trace.txt](https://github.com/DozerMapper/dozer/files/571418/dozer-eclipse-trace.txt)

**Comment by garethahealy** [comment]
@njaner ; the plugin has moved to its own repo, can you raise the issue there please.
- https://github.com/DozerMapper/dozer-eclipse-plugin
