### ISSUE TITLE
Error loading commons-dozer.xml

### ISSUE THREAD

**Issue by fclotet** [DozerMapper/dozer#297]
Loading commons-dozer.xml I'm getting an error "java.net.SocketException: Software caused connection abort: socket write error"

**The error is related to the server http://dozer.sourceforge.net, it is returning empty response for Java/1.7.0_09**

The file ....\WEB-INF\classes\dozer\commons-dozer.xml is referencing to "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd"

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mappings PUBLIC "-//DOZER//DTD MAPPINGS//EN"
   "http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd">
<mappings>
...
```

When parses the xml java is try to download http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd, for doing it the jdk is sending a http protocol header similar to:

```
GET http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd HTTP/1.1
Host: dozer.sourceforge.net
User-Agent: Java/1.7.0_09
```

When User-Agent is "Java/1.7.0_09" the response from the server is empty... setting anything diferent is working... for example:

```
GET http://dozer.sourceforge.net/dtd/dozerbeanmapping.dtd HTTP/1.1
Host: dozer.sourceforge.net
User-Agent: Java/1.7.0_0X
```

My java version is

```
>java -version
java version "1.7.0_09"
Java(TM) SE Runtime Environment (build 1.7.0_09-b05)
Java HotSpot(TM) 64-Bit Server VM (build 23.5-b02, mixed mode)
```

grettings,
Fidel

**Comment by garethahealy** [comment]
As you've noted that changing the user agent works, i'd suggest updating to latest JDK7 version.
