### ISSUE TITLE
can't use xml and api config at same time

### ISSUE THREAD

**Issue by cay914** [DozerMapper/dozer#298]
I want to use xml to config the global option. i.e <date-format>
and mapping class i use the api.
some thing like this 
mapping(Station.class, StationResp.class)
but api method is disable.

	    List<String> mappingFiles = new ArrayList<String>();
	    mappingFiles.add("dozer-mapping.xml");
	    DozerBeanMapper dozerBeanMapper = new DozerBeanMapper();
	    dozerBeanMapper.setMappingFiles(mappingFiles);
	    dozerBeanMapper.addMapping(tmsMappingBuilder());

When I don't add the **mappingFiles** to **dozerBeanMapper**, the api method works.
Can I use xml and api config at same time?

**Comment by cay914** [comment]
well, I'm wrong.

**Comment by garethahealy** [comment]
@cay914 ; is this is not an issue, can you close please
