### ISSUE TITLE
Direct map between Primitive or wrapper

### ISSUE THREAD

**Issue by w-rodolfo-labsch** [DozerMapper/dozer#299]
Not sure if a feature request or bug, although the following seems pretty intuitive but does not work on dozer and I couldn't find anywhere in the documentation about it:

mapper.map(1, Long.class);
// or maybe:
mapper.map("1", Integer.class);
mapper.map(1, int.class);

I could make it work with:
PrimitiveOrWrapperConverter converter = new PrimitiveOrWrapperConverter();
converter.convert("1", Integer.class, null);

But as the javadoc (PrimitiveOrWrapperConverter) goes:
"Internal class for converting between wrapper types(including primitives). Only intended for internal use."

**Comment by garethahealy** [comment]
@w-rodolfo-labsch ; why would you want to use dozer to map between a primitive or wrapper? I don't understand the use case.

**Comment by w-rodolfo-labsch** [comment]
1. For cases where you just cannot use dozer to convert between DTOs, because the conversion is just too complex for dozer to handle. Then I could use dozer to convert simple types directly.
2. I could also mention the case where you simply want a direct conversion, you have an Object but need a simple int.

**Comment by garethahealy** [comment]
@w-rodolfo-labsch ; i've added an example of how you can do this. Wraps the PrimitiveOrWrapperConverter, so it can be used as a custom converter.

https://github.com/garethahealy/dozer/commit/410dbed693b24e1a3a23e1113693dfd590505a1c

**Comment by garethahealy** [comment]
@w-rodolfo-labsch ; need anymore info? if not, please close.

**Comment by w-rodolfo-labsch** [comment]
@garethahealy 

This is exactly the type of code I would like to avoid:
```
public class PrimitiveOrWrapperCustomConverter implements CustomConverter {
      private PrimitiveOrWrapperConverter converter = new PrimitiveOrWrapperConverter();
      public Object convert(Object destination, Object source, Class<?> destClass, Class<?> sourceClass) {
         return converter.convert(source, destClass, null);
     }
}
```
That is, if I need to create my own converter, might as well make the conversion myself.
And this is the reason I see that Dozer should do it natively.
If you do accept this feature, I can provide a patch for it.

**Comment by garethahealy** [comment]
@w-rodolfo-labsch ; Am happy to merge/review, if your happy to commit.

**Comment by w-rodolfo-labsch** [comment]
Will do :+1:

**Comment by garethahealy** [comment]
@w-rodolfo-labsch ; have you had chance to work on this?

**Comment by garethahealy** [comment]
@w-rodolfo-labsch ; any update?
