### ISSUE TITLE
Upgrade pax-exam to 4.x

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#314]
See camel for tips
- https://github.com/apache/camel/tree/master/components/camel-test-karaf

**Comment by garethahealy** [comment]
mvn versions:display-dependency-updates

[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   org.apache.felix:org.apache.felix.framework ........... 4.2.1 -> 5.6.2
[INFO]   org.ops4j.pax.exam:pax-exam-container-native ......... 3.5.0 -> 4.10.0
[INFO]   org.ops4j.pax.exam:pax-exam-junit4 ................... 3.5.0 -> 4.10.0
[INFO]   org.ops4j.pax.exam:pax-exam-link-mvn ................. 3.5.0 -> 4.10.0

**Comment by orange-buffalo** [comment]
Hi, this is done as part of OSGI bundle improvements in #336.
