### ISSUE TITLE
POMs have lots duplication and different versions for dependancies

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#326]
The current POMs have a lot of duplication (i.e.: same plugins copy+pasted) and use the same dependancies (i.e.: version specified in 2 different POMs) or use different versions (i.e.: OSGi framework).

Would make it easier going forward to have a parent POM to control versions/common plugins across the components.

**Comment by buzdin** [comment]
do you think that upgrade to gradle would make more sense?

**Comment by garethahealy** [comment]
@buzdin ; i don't have any experience of gradle / not seen any customers use it in my day-to-day job, but happy to create an issue to add support and investigate.
