### ISSUE TITLE
Bi-directional mapping of Object/String fields with empty string fails (unit test)

### ISSUE THREAD

**Issue by skjardenCode** [DozerMapper/dozer#334]
Hello,

I came across a trivial use case, where I had to map between two simple classes, where one property is of type `Object` and the other is a `String`. When I map from class A to class B and immediately back from (mapped) B to A while using an empty string for the mapped property, Dozer "loses" the empty string and sets the property to `null`.

(_Edit: I'm using Dozer 5.5.1._)

Please see this small unit test, that fails at the last `assertEquals`:

```java
import static org.junit.Assert.assertEquals;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.dozer.DozerBeanMapper;
import org.junit.Before;
import org.junit.Test;

public class DozerEmptyStringMappingTest
{
    @Test
    public void test_mapEmptyString()
    {
        DozerBeanMapper dozerBeanMapper = new DozerBeanMapper();

        
        // Test bi-directional mapping with non-empty string

        ClassA classA = new ClassA();
        classA.setName( "Not Empty" );
        
        ClassB classB = dozerBeanMapper.map( classA, ClassB.class );
        ClassA mappedClassA = dozerBeanMapper.map( classB, ClassA.class );

        assertEquals( "Not Empty", classB.getName() );
        assertEquals( "Not Empty", mappedClassA.getName() );
    
    
        // Test bi-directional mapping with empty string
        
        classA.setName( "" );
    
        classB = dozerBeanMapper.map( classA, ClassB.class );
        mappedClassA = dozerBeanMapper.map( classB, ClassA.class );

        assertEquals( "", classB.getName() );
        assertEquals( "", mappedClassA.getName() );      // Fails: 'getName()' returns null 
    }

    public static class ClassA
    {
        private Object name;

        public Object getName()
        {
            return name;
        }

        public void setName( Object name )
        {
            this.name = name;
        }
    }

    public static class ClassB
    {
        private String  name;

        public String getName()
        {
            return name;
        }

        public void setName( String name )
        {
            this.name = name;
        }
    }
}
```

Since there is a mapping between Object and String, I would have guessed Dozer might not to be able to map the string without a type hint. **But**, because the mapping behaves correctly with a non-empty string, I think the failure of the last `assert` may be a bug in Dozer or at least a weird default-behavior.

**Comment by garethahealy** [comment]
@skjardenCode ; this is due to the default behaviour of primitive mapping.

https://github.com/DozerMapper/dozer/blob/16565b05cce98f8115cb4a2dbae18a4224fa2fc9/core/src/main/java/org/dozer/converters/PrimitiveOrWrapperConverter.java#L70-L72

**Comment by garethahealy** [comment]
@skjardenCode ; any feedback?
