### ISSUE TITLE
How to map to Custom List Implementation?

### ISSUE THREAD

**Issue by eiswind** [DozerMapper/dozer#344]
I have a JavaFX ObservableList in my target Object. I guess there must be a way to tell dozer to create an instance somehow, but I'm just net getting it and would really appreciate a hint how to specifiy this. Do I need to create a Plugin with a Factory or is there an easier way?

map ArrayList <-> ObservableList (and vice versa)

**Comment by garethahealy** [comment]
@eiswind ; I've not used JavaFX before, but you can provide factorys to create objects.

https://github.com/DozerMapper/dozer/blob/master/docs/asciidoc/documentation/custombeanfactories.adoc

Does that help?

**Comment by eiswind** [comment]
Thx!
