### ISSUE TITLE
Pass MappingContext to CustomConverter

### ISSUE THREAD

**Issue by koh-osug** [DozerMapper/dozer#355]
Currently it is not possible to map fields based on the value of different field. A new method on the Object `CustomConverter`, likegiving a sourceObject :

convert(Object existingDestinationFieldValue, Object sourceFieldValue, Object sourceObject, Class<?> destinationClass, Class<?> sourceClass);

would allow this feature at least in the context of the current Object. The object coudl also be a DozerEvent. A little bit more complex would be to pass a proper "MappingContext" which allows to access also field higher in the hierarchy.

**Comment by garethahealy** [comment]
@koh-osug ; am not sure what you mean by "to map fields based on the value of different field". Can you provide an example.

**Comment by koh-osug** [comment]
class Foo {
String country;
String currency;
}

The CustomConverter  should be able to inspect all fields of Foo, i.e. the country to map the currency based on the country to some default value. Other parser frameworks are proving a parser context, which allows to access other field.

**Comment by garethahealy** [comment]
Would the MapperAware help?

See: https://github.com/DozerMapper/dozer/tree/master/core/src/test/java/org/dozer/functional_tests/mapperaware

**Comment by koh-osug** [comment]
I guess not, I cannot find the full information about  the source object. Only the mapper is there but not the object the mapper is operating on, right?
