### ISSUE TITLE
Event for mapping finished not fired when using converter

### ISSUE THREAD

**Issue by michbeck100** [DozerMapper/dozer#364]
When using a custom converter for mapping no event after mapping is fired. This issue belongs to Dozer 5.4.0. (see https://github.com/DozerMapper/dozer/blob/v5.4.0/core/src/main/java/org/dozer/MappingProcessor.java#L173)

**Comment by garethahealy** [comment]
@michbeck100 ; happy for any PRs to fix issue :)
