### ISSUE TITLE
> 6.1; Change Proposals

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#376]
This is a high level ticket to track any major changes to the core code base which require a change proposal before commencing with work.

Any submitted proposal should fit the following criteria:

- You are willing to suggest the change, **as well as implement** it.
- A proposal should be raised via new github issue and explained in full what the suggested change is, and how it benefits the project.
- Any docs reflecting a change or addition should be updated.
- Unit test coverage should be to a high standard.

**Comment by garethahealy** [comment]
Fluent builder and move away from Singletons; https://github.com/DozerMapper/dozer/issues/375

**Comment by garethahealy** [comment]
Pipelines for Mapping Processor; https://github.com/DozerMapper/dozer/issues/377

**Comment by orange-buffalo** [comment]
Another suggestion - #400.

**Comment by buzdin** [comment]
I would suggest #94
