### ISSUE TITLE
Change MappingProcessor to use a pipeline model

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#377]
The mapping processor currently does a lot of work. Its suggested that this be split out into several classes, which use a Pipeline pattern. This will allow for easier extension in the future as well as modularising the current mapping processor.

https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/MappingProcessor.java

A "exchange" object would be passed between pipelines, which would hold the payload and any properties/headers required. The pipeline would make use of Java8 streams.

http://qrman.github.io/posts/2017/02/09/pipeline-pattern-plumber-quest

**Comment by garethahealy** [comment]
@orange-buffalo ; views / ideas / comments? :)

**Comment by orange-buffalo** [comment]
@garethahealy, I really appreciate splitting this huge class into several ones. If in the end all the logic is extracted and `MappingProcessor` simply contains a pipeline which it executes, I would suggest to remove this class completely and move pipeline directly into the `DozerBeanMapper`.

**Comment by garethahealy** [comment]
@orange-buffalo ; yes, that would be the idea. Combined with your builder change, we could then allow the user to pass in their own pipeline manager class and give them full control over what dozer is mapping.

i.e.: maybe they want a custom step, which isnt supported by default, such as firing an event at a certain point

With this model, they can easily do it.

**Comment by orange-buffalo** [comment]
@garethahealy sounds great, I like this idea.
