### ISSUE TITLE
Copyright javadocs

### ISSUE THREAD

**Issue by orange-buffalo** [DozerMapper/dozer#378]
Currently Dozer uses javadoc for copyright notice in source code, above the `package` statement:
```java
/**
 * Copyright 2005-2017 Dozer Project
 *
 * ....
 */
package org.dozer.functional_tests;
```

javadoc does not support this notation, package-level comments should be specified in [dedicated files inside the package](http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#packagecomment). This causes "complaints" from IDE, like IDEA's "dandling javadoc". Moreover, [classical code conventions](http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-141855.html#3043) recommend to use comments for copyrights:
> 3.1.1 Beginning Comments
All source files should begin with a c-style comment that lists the class name, version information, date, and copyright notice:

Does it makes sense to align Dozer code styles for copyright notice with industry standards and replace copyright javadocs with comments?

**Comment by garethahealy** [comment]
Am not sure what you mean... comparing what Camel does and what we have, they look the same.

https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/CamelContext.java#L1-L17

https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/DozerBeanMapper.java#L1-L16

**Comment by orange-buffalo** [comment]
When it comes to code conventions, I believe "right" or "wrong" is not always applicable. We can observe both approaches to handle copyright notices. For instance, [Spring is using comments](https://github.com/spring-projects/spring-framework/blob/master/spring-beans/src/main/java/org/springframework/beans/AbstractNestablePropertyAccessor.java#L1-L15).

To me this is purely question of taste and preferences. My argumentation to use comments is quite simple.

First, according to [javadocs tool documentation](http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#documentationcomments), `package` is not a proper place to use "Javadoc comments" :
> Placement of comments - Documentation comments are recognized only when placed immediately before class, interface, constructor, method, or field declarations -- see the class example, method example, and field example. 

Thus javadoc as a file header is a misuse of this tool to me. 

And second, the problem of copyright notice is addressed in [Sun's/Oracle's Code Conventions](http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-141855.html#3043) - it is recommended to use a comment at the beginning of the file.

As I said, this is one of those topics where personal opinion makes a big deal. So if you are not convinced with the arguments, let's just close this issue :)

**Comment by garethahealy** [comment]
@orange-buffalo ; sorry, but i am totally missing the point. You keep mentioning comments, but isn't that what the license format currently is?

Think the easiest thing to do is; make a change and show me that, then i'll understand what you mean.

Is it purely that theres a empty line between the license and package? i.e.:

```
/**
 * Copyright 2005-2017 Dozer Project
 *
 * ....
 */

package org.dozer.functional_tests;
```

**Comment by orange-buffalo** [comment]
@garethahealy, sorry for being confusing. This is not about empty line, but about comment format. 
There are two types of comments in this context. 

The first one is "Javadoc comment", I refer to it in my statements as "javadoc". It looks like the following:
```java
/**
 * Copyright 2005-2017 Dozer Project
 *
 * ....
 */
```
It is used in Dozer, Camel and others for copyright notices. This type of comments is processed by javadoc tool to generate documentation. 

The second is regular multi-line comment, in code convention Oracle refers to it as "c-style comment", I used "comment" in my previous posts:
```java
/*
 * Copyright 2002-2016 the original author or authors.
 *
 */
```
This is ignored by javadoc tool. Spring, google-gson and others use this style for copyright notices. 

These two types of comments have different semantic and purpose. As far as I am aware, most of IDEs and editors with syntax highlighting would render them differently:

![image](https://cloud.githubusercontent.com/assets/4532247/26400074/9581d60a-407f-11e7-8c00-2ed0e8e6d1a7.png)
 
Coming back to a change in Dozer, it would be basically removing one asterisk character (which sounds like a petty thing, but makes some difference):
```java
/*
 * Copyright 2005-2017 Dozer Project
 *
 * ....
 */
```

**Comment by garethahealy** [comment]
OK, i get it now. Had a quick check on the plugin, and not sure if theres that final control, but might be possible. If not, we can move to the codehaus plugin. Up to you.
