### ISSUE TITLE
Provide spring-boot support

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#382]
- Spring boot starter
- Make dozer work within spring-boot as a first-class-citizen

**Comment by vadeg** [comment]
@garethahealy could you provide some details what exactly should be supported by dozer spring boot starter module? (bean creation, properties configuration etc..)

**Comment by garethahealy** [comment]
@vadeg ; i'd expect the first version to just provide support;

i.e.: @DozerMapperAutoConfiguration

which would create a default mapper. once thats done, we can build on other bits.

If you are interested in committing, that would be great.

**Comment by vadeg** [comment]
@garethahealy yes, I am interested :) Thank you for explanation!

**Comment by garethahealy** [comment]
@vadeg ; if you are happy to commit, i am happy to review/merge :)
