### ISSUE TITLE
Release v6

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#388]
As travis can now push to sonatype, we can do a release of v6.

@orange-buffalo ; any reason not to?

**Comment by orange-buffalo** [comment]
@garethahealy, nope, I am for releasing.

**Comment by garethahealy** [comment]
Travis build:
- https://travis-ci.org/DozerMapper/dozer/builds/236100398

Sonatype release:
- https://oss.sonatype.org/content/repositories/releases/com/github/dozermapper/dozer-core/6.0.0/

**Comment by garethahealy** [comment]
GitHub release tag:
- https://github.com/DozerMapper/dozer/releases/tag/v6.0.0

**Comment by garethahealy** [comment]
Maven Central:
- http://central.maven.org/maven2/com/github/dozermapper/dozer-core/6.0.0/

**Comment by orange-buffalo** [comment]
Great, thanks a lot! 
It would also very nice if the versions in poms were updated to the next snapshot.
