### ISSUE TITLE
Make DozerBeanMapper immutable. Part I. Deprecating setters. 

### ISSUE THREAD

**Issue by orange-buffalo** [DozerMapper/dozer#400]
Currently `DozerBeanMapper` allows users to change its configuration after instantiation. This has several drawbacks:
* encourages users to work with implementation, as `Mapper` interface does not provide those "set" methods;
* adds additional logic to synchronize initialization of internals and track that this is done only once.

I assume, these "set" methods were introduce to avoid multiple constructors for all possible configuration options. This will not be an issue after fluent builder is introduced in #375.

Suggestion:
* replace "set" methods from `DozerBeanMapper` with constructor parameters;
* add fluent API to configure those parameters in builder created in #375;
* make  `DozerBeanMapper` package-private as users will only use builder and `Mapper`.

During this implementation some logic is likely to be extracted from `DozerBeanMapper` to the third classes. For instance, `Mapper` requires only final mapping config, thus merging XML mappings and Java mapping builders is a perfect candidate to be delegated to another class.

**Comment by garethahealy** [comment]
Sounds good.

**Comment by orange-buffalo** [comment]
I've split this issue into two. In current one, scheduled for 6.1, we'll deprecate the setters and provided fluent builder method for the same configuration. 
In #434 we will remove the deprecated code, making `DozerBeanMapper` indeed immutable. This should be scheduled for 6.2.
This way we'll provide migration path for Dozer users.
