### ISSUE TITLE
Update milestones

### ISSUE THREAD

**Issue by orange-buffalo** [DozerMapper/dozer#401]
Current Dozer milestones are outdated: https://github.com/DozerMapper/dozer/milestones. This might be confusing to users. It would make sense to clean-up outdated ones. 

And related suggestion is to use and maintain milestones in the project. This would help to organise and communicate the scope of next release(s), and also would visualise what changes are delivered in each version.

**Comment by garethahealy** [comment]
Closed old milestones and created 6.1.0.

**Comment by orange-buffalo** [comment]
Great, thanks!
