### ISSUE TITLE
Update github short description URL

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#405]
The current description points people to SF; needs updating to GH-pages.

<img width="1003" alt="screen shot 2017-05-29 at 16 46 28" src="https://cloud.githubusercontent.com/assets/8656974/26555774/9a0a2ade-448e-11e7-82e7-cff6c4b202d0.png">

@buzdin ; I cant edit this description. Can you give me permissions or do it yourself please.

**Comment by garethahealy** [comment]
@buzdin ; are you able to update? URL just needs updating to: 
- https://dozermapper.github.io/

**Comment by buzdin** [comment]
done
