### ISSUE TITLE
Move XSD and DTD to dozer-schema JAR

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#407]
- Move resources to own JAR
- Start to version files, i.e.: beanmapping.xsd is latest, beanmapping-6-0.xsd is 6.0

**Comment by garethahealy** [comment]
@orange-buffalo ; I also suggest renaming beanmapping to bean-mapping, as it follows how other projects name XSDs (i.e.: spring).

**Comment by orange-buffalo** [comment]
@garethahealy, completely agree with new naming.
