### ISSUE TITLE
date format issue with dozer framework

### ISSUE THREAD

**Issue by skaluva** [DozerMapper/dozer#412]
I'm using latest dozer version 5.5.1 where i'm facing weird issue string to date conversion mapping. I receive data in a map with, MonitoredAt (date field), as string with format: yyyy-MM-dd HH:mm:ss.SS ( date with full timestamp including millis) and my POJO having java.util.Date property defined to hold this value. I defined mapping like this:

```
<mapping > 
    <class-a>java.util.Map</class-a>
    <class-b>com.MyPojo</class-b>   
    <field>
      <a date-format="yyyy-MM-dd HH:mm:ss.SS">MonitoredAt</a>
      <b>monitoredAt</b>
    </field>
  </mapping> 
```
During conversion, dozer keeping only date without timestamps in target property. But for me full date with timestamp is very important.

I know one way that we can write custom converter to acheive my task. But i want to know, without custom converter can we do that?
https://stackoverflow.com/questions/44196263/date-format-issue-with-dozer-framework

**Comment by garethahealy** [comment]
@skaluva ; can you provide a github repo with a workable test showing what you mean.

**Comment by skaluva** [comment]
Sorry, please close the issue.. eclipse imported java.sql.Date instead of java.util.Date which caused the issue.  Now its working as expected. Please close the issue.
