### ISSUE TITLE
Reduce amount of duplicate test classes

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#417]
There is currently lots of different test data classes, with lots of different and duplicate properties. We should move to a testing model (i.e.: pick a theme; Car, Person etc) so we can reduce the amount of code.

**Comment by buzdin** [comment]
This one is a big problem. There are lots of tests from different PRs and they often overlay each other are different in approaches and there is no feature matrix for tests, which would cover combinations. Basically what you can do now is just adding more tests on top of legacy tests. Structuring all of them is a lot of work.

One interesting approach is to do data-driven testing. Write code generator, which would assemble test cases for all possible combinations of features and generate asserts as well. This might uncover a lot of hidden bugs.

**Comment by garethahealy** [comment]
Thinking about this recently. Propose the following stages:
- Move all model classes out of core, into their own JAR - will help understand what can be removed/not
- Move the functional tests out of core, into their own JAR. Keep the core test folder as pure unit tests for dozer, no mapping/functional tests - again, will help understand whats the current state of play.

CC @orange-buffalo

**Comment by orange-buffalo** [comment]
I would appreciate moving functional tests into a separate module. It is likely that some of the model objects are required for the unit tests, and those I would keep in the core, probably with step-by-step cleaning and re-writing (even keeping some duplicates in core and functional test at the beginning, if the same models are currently reused by both). But I would not introduce another module for model objects only.

Data-driven tests would be an interesting approach, something similar to the chaos monkey. But for now implementing this seems quite a complicated and resource-consuming task to me.
