### ISSUE TITLE
Update hardcoded version to resolve from meta-inf

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#424]
Instead of using hardcoded version:

-
 https://github.com/DozerMapper/dozer/blob/0b8f939980e003c1da421ca0c8f25ad143264e0a/core/src/main/java/org/dozer/DozerInitializer.java#L76-L77

Resolve from: META-INF/maven/dependencies.properties 

i.e.: 
- https://github.com/kiegroup/drools/blob/f7ab4ee3c88d767a8cbb372c2db1afa84b20a51d/drools-compiler/src/main/java/org/drools/compiler/kproject/xml/MinimalPomParser.java

**Comment by orange-buffalo** [comment]
Another alternative would be to have a file in `src/resources` with placeholder for `${project.version}`, filtered by Maven during `process-resources` phase. With this approach we would rely on the file in our code base instead of build-tool-generated file.
