### ISSUE TITLE
Add OpenTracing support

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#426]
The current stats implementation are just counters. I don't think that gives a user of dozer a lot of information, since they need to manually integrate into the stats manager and pull out info to visualise. I think a much better approach is to integrate with OpenTracing
- https://github.com/opentracing

We implement the API and the user provides the implementation - be it Zipkin, jaeger or another.

- https://github.com/openzipkin/zipkin
- https://github.com/uber/jaeger

@orange-buffalo ; do you guys use any OpenTracing impl? would this be helpful?

**Comment by garethahealy** [comment]
And a secondary benefit would be we can easily profile the codebase to understand where flaws are.

**Comment by buzdin** [comment]
What type of information would you be sending in this case? Is Dozer relevant in application tracing or is it just a small conversion layer? In case it is used in middleware, like Camel, the framework itself would take care of tracing and all that. Just a thought.

**Comment by orange-buffalo** [comment]
@garethahealy, I agree with @buzdin that Dozer is only one of the tools used by applications. As an end-user, I would not be interested in looking into stats about Dozer execution. I believe we should have internal performance testing to make sure we do not waste resource, perhaps some simple internal monitoring to (optionally) alert user if they use Dozer extensively (i.e. we detected huge graph of objects being mapped, which takes more than N ms - drop some warning into logs so users can decide if they really need to map these objects), but I would vote for removing detailed counters at all and not invest in OpenTracing or similar approaches. Of course, IMHO :)

**Comment by buzdin** [comment]
I would suggest not doing anything here and maybe even dropping the current statistics support, because it is hardly usable.

**Comment by garethahealy** [comment]
Stalling feature request unless other users request.
