### ISSUE TITLE
Create resources based on open source survery

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#427]
The following survey suggests we should add a few "admin" style info:
- https://github.com/blog/2372-announcing-the-open-source-survey

- [ ] contributing guide
- [/] code of conduct
- [/] contributor license agreement 

1/2 are just docs, 3 can be done via a github bot.

**Comment by garethahealy** [comment]
@orange-buffalo ; views?

**Comment by garethahealy** [comment]
CLABot 
- https://github.com/clabot/clabot

**Comment by buzdin** [comment]
My view is to keep it simple. Dozer is not under Apache or other legal entity, so generally speaking no one cares about license agreements. It will just increase the barrier to entry for those willing to contribute.
Code of conduct idea for an open source project seems like a really strange idea to me. I know that there is a trend somewhere out there, but would not go and just copy paste some text to the website.

Contributing guide is a must. I made a placeholder some time ago https://github.com/DozerMapper/dozer/wiki/Contributing-to-Dozer 
:)

**Comment by orange-buffalo** [comment]
I agree with @buzdin that having CLA would complicate contribution process, especially for new members. I believe that it would be enough to have a short statement in contribution guide in this regard, something like "By contributing to Dozer project you agree that you contribution is managed and distributed in compliance with Dozer license" (or any fancier expression if you familiar with more formal legal statements :) ). 

As for code of conduct, I don't mind having it in the project. But to me this is something more typical for big companies / huge projects with lots of contributors. Again, having a statement in contribution guide like "Please respect others and be polite" would be quite sufficient.

I suggest to move the contribution guide from wiki to the `CONTRIBUTING.md` file in the root of the project. Then GitHub will provide link to this document every time new issue/PR is created (https://github.com/blog/1184-contributing-guidelines).

**Comment by garethahealy** [comment]
Am happy with what you've both said. Am just throwing ideas out there :)
