### ISSUE TITLE
Make DozerBeanMapper immutable. Part II. Removing setters. 

### ISSUE THREAD

**Issue by orange-buffalo** [DozerMapper/dozer#434]
See #400. 
This issue is to remove deprecated code and finally make `DozerBeanMapper` immutable.

**Comment by garethahealy** [comment]
@orange-buffalo ; have been thinking about this recently. The current idea i have is to add a new interface called "MapperContext" that includes all the getters. That way anyone interested in getting the list of converters / mapping files back, can cast the mapper and has access to the getters.

Thoughts?

**Comment by orange-buffalo** [comment]
@garethahealy Could be a nice feature of `Mapper`. The only thing to suggest here from my side is to introduce a method like `getMapperContext` on `Mapper` so that users could get this via API instead of casting.
