### ISSUE TITLE
ResourceLoader#getResource does not use provided classLoader

### ISSUE THREAD

**Issue by orange-buffalo** [DozerMapper/dozer#436]
`org.dozer.util.ResourceLoader#getResource` uses thread context classloader, then classloader of `ResourceLoader`, then system classloader  to load requested resource. It does not use provided `classLoader` at all, although should use it as the first attempt. 

TODO:
* unit test to reproduce
* fix for this issue.

**Comment by garethahealy** [comment]
I think this should be done as part of the wider context to improve class loading. We need to give the option to the user to provide a list of DozerClassLoader[1], which is joined onto a list of default class loaders provided by dozer, which could be:

1. Mapper class loader
2. OSGi class loader
3. Current thread class loader
4. System class loader

[1] https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/util/DozerClassLoader.java

**Comment by orange-buffalo** [comment]
I like this idea, it completely makes sense to have this chain in one place, transparently used within the project code.
