### ISSUE TITLE
JMXPlatform and multiple Mapper instances

### ISSUE THREAD

**Issue by orange-buffalo** [DozerMapper/dozer#437]
After we moved away from global state in Dozer and removed the singletons, it became obvious that there is a problem with usage of `JMXPlatform`. Every new `Mapper` will try to register the JMX beans under the same names, effectively unregistering previously registered beans - only the last `Mapper` will be exposed via JMX.

I wonder if JMX beans are required after all. They expose statistics and version. As we discussed in #426, the need in this statistics is questionable. If required, tracing can be implemented in more elegant way.

IMO, the cleanest solution would be to remove statistics and JMX beans from Dozer.
If JMX beans should stay, then probably there should be some unique identification of created `Mapper` instances to register independent beans (i.e. with different names) for every `Mapper` instance.
If it is okay to remove JMX beans but statistics should stay, `Mapper` interface should be enriched with methods to get `StatisticsManager`.

@buzdin, @garethahealy what do you think?

**Comment by garethahealy** [comment]
I suggest we deprecate JMX in 6.1, and remove in 6.2. Lets try and find out if people are using the stats, and if not, follow suit with 6.2/6.3

**Comment by buzdin** [comment]
Do we have something like triggering reload of mapper files in JMX?

If its only statistics, I would day its ok to discard. Would be a better approach to provide an API, and then implement JMX module on top for administrative methods.

**Comment by garethahealy** [comment]
No, only stats from what i can see:
- https://github.com/DozerMapper/dozer/tree/master/core/src/main/java/org/dozer/jmx
