### ISSUE TITLE
Feature Idea/Request: Programmatic API for Mappings

### ISSUE THREAD

**Issue by zharvey-welltok** [DozerMapper/dozer#454]
## Whats the problem?
I will have a running ETL server that needs to do all sorts of conversions & transformations from one type of bean to another and would like Dozer to be the main transformation library running under the hood. I need these transformations (Dozer mappings) to be defined dynamically at runtime, not just at startup or Dozer initialization-time.

Users will be creating and storing Dozer XML mapping files in a document store such as MongoDB and I'll be reading those XML files into memory when the server is running. So I need the ability to dynamically load Dozer XML mapping files from in-memory objects (probably just Strings unless anybody has a better idea) and to re-initialize/bootstrap itself to honor the content in the mapping files.

Example:

```
public void onReloadRequested(EtlEvent etlEvent) {
    UUID mapperID = etlEvent.getMapperId();

    // This fetches the entire content of a typical Dozer mapper XML file
    String dozerMapperXml = mongoClient.getDozerMapperXml(mapperId);

    // Now the global 'dozer' object is reconfigured with the new mapping that we just
    // read out of Mongo (it could be a new mapping or an update to an existing one).
    //
    // Now anytime the code tries to map from type A to type B, the new mapping will be
    // used.
    dozer.reload(dozerMapperXml);
}
```

After reading the docs on your main SF site as well as the wiki on GitHub I don't think this is currently possible to do.

If it is, can someone point me in the right direction?!

And if it's not then I was hoping to solicit the community's opinion as to whether this would be a welcomed Dozer feature. If that's the case I'm perfectly happening contributing a PR in the coming weeks for it, but I don't want to go to that trouble unless I know its something the community will want!

Thanks!

**Comment by garethahealy** [comment]
@zharvey-welltok ; the current direction of the code base is to make the Mapper immutable, as we are heading down a Builder pattern, as per:
- https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/org/dozer/DozerBeanMapperBuilder.java

So i don't think the proposed "reload" would work.

But to understand your requirement a bit more, have a few questions.

- Is this 1 mapping file that contains 1 mapping? or multiple files with multiple mappings
- If the old mappings need to be invalidated, how do you expect this to happen? remove all current mappings and add new one? or only remove the ones that are being changed?

CC @orange-buffalo

**Comment by garethahealy** [comment]
@zharvey-welltok ; any update?

**Comment by garethahealy** [comment]
Closing due to no feedback.
