### ISSUE TITLE
Documentation - Downloading the Distribution

### ISSUE THREAD

**Issue by AxelBaumann** [DozerMapper/dozer#477]
in the usergide there are the wrong maven coordinates. In **Getting Started** section there is

````xml
<dependency>
<groupId>net.sf.dozer</groupId>
<artifactId>dozer</artifactId>
<version>6.2.0-SNAPSHOT</version>
</dependency>
````
but it has to be

````xml
<dependency>
<groupId>com.github.dozermapper</groupId>
<artifactId>dozer-core</artifactId>
<version>6.2.0-SNAPSHOT</version>
</dependency>
````

**Comment by garethahealy** [comment]
- https://github.com/DozerMapper/dozer/blob/5eaa5a3339f8d2e215b007c77c551d87ded3fb4a/docs/asciidoc/documentation/faq.adoc#is-dozer-in-the-maven-repository
- https://github.com/DozerMapper/dozer/blob/62aff344fadf9c3edece8cba2082dd8a9264525c/docs/asciidoc/documentation/gettingstarted.adoc

Please raise a PR.
