### ISSUE TITLE
SpringBoot Integration

### ISSUE THREAD

**Issue by buzdin** [DozerMapper/dozer#480]
There is a simple Spring Framework integration, however Spring Boot allows a more sophisticated plugin approach. It is possible to configure DozerMapper beans on startup by putting annotation on configuration class @EnableDozerMapper. This would enable all convention based settings.

This approach could be investigated and implemented.

**Comment by garethahealy** [comment]
Duplicate of:
- https://github.com/DozerMapper/dozer/issues/382

**Comment by vadeg** [comment]
Maybe it is better to close this ticket if it is a duplicate?
