### ISSUE TITLE
ClassNotFoundException when mapping com.google.protobuf.Timestamp

### ISSUE THREAD

**Issue by panes** [DozerMapper/dozer#514]
## Whats your runtime?
* Dozer version: 6.1.0
* OS version: osx 10.12.6
* JDK version: 1.8.144
  
## Whats the problem?
_Steps to reproduce:_
1. Create new dozer mapper
2. (Optional) Create one custom converter with LocalDate and com.google.protobuf.Timestamp
3. Call : mapper.map(new LocalDate(), Timestamp.class)

Dozer is trying to load class: com.google.protobuf.TimestampProto.Timestamp, which doesn't exist in proto3
 
ProtoUtils.java@156
`
return MappingUtils.loadClass(StringUtils.join(
                getFullyQualifiedClassName(descriptor.getMessageType().getFile().getOptions(), descriptor.getMessageType().getName()), '.'), beanContainer);
`

Method: 
`
private static String[] getFullyQualifiedClassName(DescriptorProtos.FileOptions options, String name) {
        return new String[] {
            options.getJavaPackage(),
            options.getJavaOuterClassname(),
            name};
    }
  `
### Observed Results:
`
Caused by: org.dozer.MappingException: java.lang.ClassNotFoundException: com.google.protobuf.TimestampProto.Timestamp from [Module "xxx:main" from local module loader @768b970c (finder: local module finder @5a4041cc (roots: /apps/jboss/modules,/apps/jboss/modules/system/layers/base))]
	at org.dozer.util.MappingUtils.throwMappingException(MappingUtils.java:82) [dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.util.DefaultClassLoader.loadClass(DefaultClassLoader.java:46) [dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.util.MappingUtils.loadClass(MappingUtils.java:223) [dozer-core-6.1.0.jar:6.1.0]
	at com.github.dozermapper.protobuf.util.ProtoUtils.getJavaClassIgnoreRepeated(ProtoUtils.java:156) [dozer-proto-6.1.0.jar:]
	at com.github.dozermapper.protobuf.util.ProtoUtils.getJavaClass(ProtoUtils.java:125) [dozer-proto-6.1.0.jar:]
	at com.github.dozermapper.protobuf.propertydescriptor.ProtoFieldPropertyDescriptor.getPropertyType(ProtoFieldPropertyDescriptor.java:77) [dozer-proto-6.1.0.jar:]
	at org.dozer.fieldmap.FieldMap.getSrcFieldType(FieldMap.java:131) [dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.loader.MappingsParser.processMappings(MappingsParser.java:113) [dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.loader.CustomMappingsLoader.load(CustomMappingsLoader.java:64) [dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.DozerBeanMapper.loadCustomMappings(DozerBeanMapper.java:326) [dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.DozerBeanMapper.initMappings(DozerBeanMapper.java:443) [dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.DozerBeanMapper.getMappingProcessor(DozerBeanMapper.java:305) [dozer-core-6.1.0.jar:6.1.0]
	at org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:214) [dozer-core-6.1.0.jar:6.1.0]
`
  
### Expected Results:
To not load TimestampProto.Timestamp but use Timestamp.
Dozer should be able to handle 2 cases, one where the class XXXProto encapsulates XXX, and other case when XXX and XXXProto are two files like Timestamp example.

**Comment by garethahealy** [comment]
@jbq are you able to help with this? since you've worked on the proto module before.

**Comment by garethahealy** [comment]
@panes ; i've just created a basic unit test based on your description, but dont see an error.
- https://github.com/garethahealy/dozer/commit/da78e77b1f1e7a9f6ca7f7f4331f26aa2c39fc95

Can you provide a github repo that reproduces using a unit test please?

**Comment by garethahealy** [comment]
@panes ; i've created a simple unit test, but dont see an exception based on your description. can you please provide a github repo with a unit test showing a problem?

- https://github.com/garethahealy/dozer/commit/8e69794b0e0673e7971ce0d13893ebff07517996

**Comment by jbq** [comment]
@garethahealy I had a look at the problem and can't figure out why dozer would load the wrong class.  However I can see something strange at Google: they specified an outer class name of `TimestampProto` in `timestamp.proto` at https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto but the generated class is `Timestamp` instead of `TimestampProto.Timestamp`: `https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Timestamp`.  A full test case would be needed to understand.

**Comment by panes** [comment]
@jbq Yes found same thing as you when reading the timestamp.proto file, and if I generate a Java Class from .proto file I don't have same behaviour, I really have TimestampProto.Timestamp.

@garethahealy  Ok I pushed some code to github to reproduce the issue at [https://github.com/panes/dozer-protobuf ](url)

I did 2 correct cases:
 - **DateConverterUsingXmlTest.java**, one with dozer mapping using xml file, defining one custom converter: **SUCCESS**
 - **DateConverterUsingSpringAPITest.java**, second with dozer mapping using API with Spring injection, defining one custom converter: **SUCCESS**

I did 2 wrong cases:
 - **WrongDateConverterUsingXmlTest.java**, one with dozer mapping using xml file, defining one custom converter and one mapping: **FAIL**
 - **WrongDateConverterUsingSpringAPITest.java**, second with dozer mapping using API with Spring injection, defining one custom converter and one mapping: **FAIL**
 
May be I'm using badly dozer, and you can explain me how to do it in a good way, I want to define a custom converter from com.google.protobuf.Timestamp to java.util.LocalDate, this step is working, and use this converter automatically each time I define a mapping from class A with a Timestamp field to a class B with a LocalDate field. When I try to define a dozer mapping with such setup I got the issue about ClassNotFoundException. Let me know if you need more details, or if I should do things differently. 
Thanks.

**Comment by garethahealy** [comment]
@panes ; just did a quick scan of the project, and the working vs wrong, look identical. what are the differences?

**Comment by panes** [comment]
On working solution I just put a custom converter without any mapping between two classes; on the wrong part, I took the same as working plus added a mapping between two classes having a timestamp as a field.

**Comment by panes** [comment]
Did you have time to investigate that issue or some expected date to get feedback? I disabled dozer for now and use standard mapping rules, but wanted to use dozer instead to make some benchmark tests and see dozer impact on mapping resolution. If I got some time next week I'll try to get into it to try to find the root cause. Thanks.

**Comment by jbq** [comment]
I just had a look in the debugger and confirm that this is a Google bug, not a dozer one.  Indeed, Google's `timestamp.proto` specifies `TimestampProto` as outer class name, so dozer expects to find the `Timestamp` class in `TimestampProto$Timestamp`.

**Comment by panes** [comment]
If I use my custom timestamp instead of protobuf one, of course it works fine, in dozer side no issues. For my test purpose I'll do it but I would prefer to use the protobuf timestamp, I'll send them a message with that case to see how to fix it in proto side, may be one option is to generate correct timestamp classes using protoc compiler, or at least understand why I've this wrong timestamp generated. I'll keep you updated. Thanks for your help.

**Comment by panes** [comment]
Ok I got some reply from protobuf thread, that you can follow here:
[https://github.com/google/protobuf/issues/3731](url)

> Protobuf generates com.google.protobuf.Timestamp because of the "java_multiple_files = true" option. It sounds to me dozer doesn't have the right support for this option.

Can we can improve dozer to support this option? Thanks.

**Comment by garethahealy** [comment]
@jbq ; do you understand what we'd need to do for: java_multiple_files ?

**Comment by jbq** [comment]
Yes it is pretty obvious what should be done, I'm looking at it right now
