### ISSUE TITLE
Cannot find method DozerBeanMapperBuilder.createDefault()

### ISSUE THREAD

**Issue by maoqyhz** [DozerMapper/dozer#517]
i read the user-guide version 6.1.0.
1st	Mapping 
```
Mapper mapper = DozerBeanMapperBuilder.createDefault();
DestinationObject destObject = mapper.map(sourceObject, DestinationObject.class);
```
but i read the source, cannot find this method`createDefault()`

**Comment by garethahealy** [comment]
@maoqyhz ; it should be:

`Mapper mapper = DozerBeanMapperBuilder.buildDefault();`

**Comment by maoqyhz** [comment]
I think so. You could correct the docs. What's more , I recommend you to update the doc's version on sf site or another website. Now we can find Dozer in two websites，one is sf sites last update in 2014, another is https://dozermapper.github.io, which is latest version. There are some confusion.

**Comment by garethahealy** [comment]
@maoqyhz ; i've already updated the docs. 

re: the website, we dont have control over SF anymore, so cant update, thats why all github references/docs point to github.io
