### ISSUE TITLE
Map with name() and valueOf(...) for Enums in EnumConverter

### ISSUE THREAD

**Issue by amotzek** [DozerMapper/dozer#52]
Currently, the code in EnumConverter works like this:

```
return Enum.valueOf(destClass, srcObj.toString());
```

This is not quite correct if srcObj is an Enum. I suggest that code should be like this:

```
if (srcObj instanceof Enum) {
    return Enum.valueOf(destClass, ((Enum) srcObj).name());
}
return Enum.valueOf(destClass, srcObj.toString());
```

**Comment by ekitrak** [comment]
Check this out: https://gist.github.com/jmochel/a38ded520c4da61ad6e1b43aec844854

Would it be possible for this to be the default behavior when mapping from Enum to String in Dozer?

**Comment by rockingdemon** [comment]
this is crit!
if you have toString() override that prints something human-readable (as toString() is supposed to) - dozer will not be able to map enum value to itself.

using name() is a MUST.

**Comment by garethahealy** [comment]
@rockingdemon ; do you want to raise a PR?

**Comment by diegov** [comment]
I created pull request https://github.com/DozerMapper/dozer/pull/729 to address this.
