### ISSUE TITLE
slim down core to make optional functionality pluggable 

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#528]
Certain bits in core are optional, i.e.: hibernate. To slim down the code base of core, i am proposing to split these out into extensions or plugins (name not decided), as per the below:

> dozer
> |- dozer-extensions
> |   |- dozer-hibernate-extension
> |   | ...

**Comment by garethahealy** [comment]
CC @orange-buffalo

**Comment by orange-buffalo** [comment]
With this approach, would users who use Dozer for mapping Hibernate entities need to explicitly include `dozer-hibernate-extension` as a dependency?

**Comment by garethahealy** [comment]
@orange-buffalo ; yes, they'd need to include it as a dependancy.

**Comment by orange-buffalo** [comment]
Frankly speaking, I believe adding additional Dozer dependencies to a project is too complicated for end-user. This will require digging into Dozer docs to understand what and when to add, which seems to be an additional obstacle in applying Dozer, especially for new users.  

IMHO, I would prefer a solution where Dozer automatically applies its extensions whenever appropriate classes are detected in classpath. I like this approach in Spring, when they pick-up various implementations automatically, whenever they are detected.  

For example, in case with `ProxyResolver` I would rather by default create a chained resolver which tries to apply all known implementations, which in turn signal if they should be applied (by checking related classes availability), i.e.:
```java
ChainedProxyResolver chainedResolver = new ChainedProxyResolver();
// get knownImplementations with Service Loader, for instance 
for (ProxyResolver resolver : knownImplementations) { 
     // every resolver verifies if it makes sense to enable it, in case of Hibernate by checking Hibernate classes availability
    if (resolver.isApplicable()) {  
        chainedResolver.register(resolver);
    }
}
```


Coming back to slimming the core down. I am not sure, if this is really required, as all the dependencies for optional features are, well, optional :) and thus are not transitively added to users' projects. And the extensions themselves are pretty small and do not add much in terms of jar size. 
But if this is still desired, there could be an alternative solution, by providing core jar with all extensions as a default artifact, and providing `dozer-slim` jar without optional features. This will give users who really need clean core only a possibility to fetch such an artifact. Or another way around, default artifact is slim, and `dozer-all` with extensions.
