### ISSUE TITLE
Type-safe mapping configuration

### ISSUE THREAD

**Issue by orange-buffalo** [DozerMapper/dozer#529]
I was checking recently was is going on in the field of Java mapper libraries and found out that Dozer has one significant disadvantage comparing to solutions like ModelMapper - mapping configuration is not type safe and very hard to refactor, because mapping configuration is XML- or String-based. 

@garethahealy , @buzdin what do you think, does it make sense to start discussion about moving towards type-safe and refactoring-friendly mapping configuration?

**Comment by buzdin** [comment]
I would be interested to participate in such discussion. Will post pros and cons of different options I have had in mind mind to this thread.
