### ISSUE TITLE
Access to mapId from FieldMappingMetadata

### ISSUE THREAD

**Issue by antch** [DozerMapper/dozer#530]
## Whats your runtime?
* Dozer version: 5.5.1
* OS version: OSX 10.12.6
* JDK version: 1.8
  
## Whats the problem?
When traversing class and field mapping metadata, recursive introspection is not (reasonably) possible as the API does not provide access to `mapId` from the `FieldMappingMetadata` class.

## Current workaround
Access can be gained by the following (evil) code:

    Field f = DozerFieldMappingMetadata.class.getDeclaredField("fieldMap");
    f.setAccessible(true);
    FieldMap fm = (FieldMap)f.get(fieldMappingMetadata);
    String mapId = fm.getMapId();

As we all know the above should be avoided at all costs.

Is there any reason why this could/should not be exposed? Would the maintainers be open to a PR to add this getter for 5.5.x? Are there any other work-arounds?

**Comment by garethahealy** [comment]
Happy for you to raise a PR as this is a minor change. However, we wont be able to release against the 5.5.x branch, as we no longer have the keys to publish. It would have to be against latest.
