### ISSUE TITLE
Get springboot module added to SPRING INITIALIZR

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#534]
@vadeg ; do you how to get the springboot module added to the initializr? i did a quick google, and it wasn't obvious, but seems possible, as other non-spring tech has been added.

- https://start.spring.io/

**Comment by vadeg** [comment]
@garethahealy Never did it before, but I have found [this doc](https://docs.spring.io/initializr/docs/current/reference/htmlsingle/#getting-started-dependencies) which may be helpful.

**Comment by kazuki43zoo** [comment]
Hi @garethahealy @vadeg ,
I want to submit PR for supporting dozer-spring-boot-starter in https://github.com/spring-io/initializr.
But current dozer-spring-boot-starter does not consist starter project of spring-boot. Hence I propose to fix to spring-boot starter project at first via #661.

WDYT?

**Comment by kazuki43zoo** [comment]
Related with this, I've submitted [PR](https://github.com/spring-projects/spring-boot/pull/13501) to spring-boot project for introducing spring-boot-starter module as community starter.

**Comment by kazuki43zoo** [comment]
I've submitted a [PR](https://github.com/spring-io/initializr/pull/715) for supporting dozer-spring-boot-starter in initializr service provided spring.io.

**Comment by garethahealy** [comment]
PR to springboot was declined, so closing this issue.
