### ISSUE TITLE
Update springboot config to be same as supported by spring

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#539]
Springboot config doesnt set all options provided by spring. Next step is to do that:
- https://github.com/DozerMapper/dozer/blob/master/spring/src/main/java/com/github/dozermapper/spring/DozerBeanMapperFactoryBean.java

**Comment by garethahealy** [comment]
@vadeg ; if you want to help out here, thats cool :)

**Comment by vadeg** [comment]
@garethahealy Sure, I can help :) 
Could you specify which exactly options are not set? `DozerBeanMapperFactoryBean` takes all properties from `ApplicationContext` except `customFieldMapper`.
