### ISSUE TITLE
No read or write method found for field ... for subclasses

### ISSUE THREAD

**Issue by mineroda** [DozerMapper/dozer#542]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: _6.1.0____
* OS version: _Windows 7____
* JDK version: _1.8.0_92____
  
## Whats the problem?
_Steps to reproduce:_
1. _Create class with fields, getters setters____
2. _Create subclass without reproducing fields, getters & setters____
3. _Map to/from the subclass____
  
### Observed Results:
_What happened?  This could be a description, log output, etc._
  org.dozer.MappingException: No read or write method found for field ...

### Expected Results:
_What did you expect to happen?_
successful mapping like in previously used version - 5.4.0

## Link to GitHub repo with Unit test
_The easiest way for us to fix issues, is if you provide a GitHub repo, using the latest release and a simple unit test._

**Comment by garethahealy** [comment]
@mineroda ; please provide a github repo which shows this issue. a simple unit test is best.

**Comment by mineroda** [comment]
After further inspection, the superclasses being ignored are package-private [no modifier]. changing to public allows the methods to be seen.
