### ISSUE TITLE
Add fields parameter to DozerBeanMapper

### ISSUE THREAD

**Issue by LwaziPrusent** [DozerMapper/dozer#545]
## Whats the problem?
Currently there is no way to dynamically specify fields to map (this could be very helpful with lazy loading in ORMs)

### Expected Results:
Could we add an array to the map method that specifies what fields I would like to map
eg
`CarDto car = dozerBeanMapper.map(carEntity,CarDto.class,"id","color");`

**Comment by garethahealy** [comment]
Although its not possible to pass through any field options, you could create a mapping which fits your needs via the API, and then process that.
