### ISSUE TITLE
Remove dozer-building-tools maven module.

### ISSUE THREAD

**Issue by vadeg** [DozerMapper/dozer#547]
The `dozer-building-tools` module contains only configurations related to project build phase. It does no have to be maven module. 
My suggestion will be to leave it as a simple folder instead of having useless maven module.

**Comment by garethahealy** [comment]
Its used by the findbugs/checkstyle plugins, thats why its a POM:
- https://github.com/DozerMapper/dozer/blob/master/plugins-parent/pom.xml#L335-L344

**Comment by vadeg** [comment]
ok
