### ISSUE TITLE
Add code style rules configuration.

### ISSUE THREAD

**Issue by vadeg** [DozerMapper/dozer#548]
Project has strict rules how imports should be organised in source files. It would be nice to have configuration file for IDEA and Eclipse (probably Netbeans as well) which have proper import settings and etc.

**Comment by garethahealy** [comment]
I only use IntelliJ, so am happy for that to be added. Only negative, these types of things go out of date quickly as they are not connected to the code. If theres a way to fix that, then happy to add all other ones.
