### ISSUE TITLE
Converting into protobuf class object not working

### ISSUE THREAD

**Issue by pascalwhoop** [DozerMapper/dozer#553]
## Whats your runtime?
* Dozer version: 6.2.0-SNAPSHOT
* OS version: Ubuntu 17.14
* JDK version: OpenJDK 8
  
## Whats the problem?

I cannot seem to get the Protocol Buffer conversion to work. It works with normal classes but not with protobufs for some reason. I saw the tests in the repo and it seems to work there. But for me it doesn't

  
```java
@Test
    public void convertGeneric() {
        Broker b = new Broker("chickenboy", false, false);
        TestBroker f = conv.convertGeneric(b, TestBroker.class);
        assertEquals(b.getUsername(), f.getUsername()); //succeeds

        PBBroker pbf = conv.convertGeneric(b, PBBroker.class);
        assertEquals(b.getUsername(), pbf.getUsername()); //fails
    }
```
the code above calls this 

```java
public GRPCTypeConverter() {
        mapper = DozerBeanMapperBuilder
                .create()
                .withMappingFiles("dozer-mappings.xml")
                .build();
    }

    public void convertGeneric(Object source, Object dest) {
        mapper.map(source, dest);
    }
```
mapping file looks like this

```xml
<configuration>
        <stop-on-errors>true</stop-on-errors>
        <date-format>MM/dd/yyyy HH:mm</date-format>
        <wildcard>true</wildcard>
    </configuration>
```
proto definition is this
```
message PBBroker {                                               
  int64 id = 1 ;        
  string username = 2 ;             
}
```

```java
class Broker{
private String username;
private String password;
//...
```

**Comment by garethahealy** [comment]
@pascalwhoop ; can you provide a github repo, which can be cloned with a simple example / unit test. Makes looking into problems easy.

@jbq ; any ideas?

**Comment by pascalwhoop** [comment]
@garethahealy I did. Thanks for the help. 
https://github.com/pascalwhoop/protobuf-dozer-example

**Comment by jbq** [comment]
Hi @pascalwhoop, happy to help.  There is a mistake in your pom.xml you didn't add a dependency to `dozer-proto` that's why the test fails to map to protobuf classes.

See my fork of your code: https://github.com/jbq/protobuf-dozer-example

**Comment by garethahealy** [comment]
@pascalwhoop ; i presume above answer has solved your issue. closing.
