### ISSUE TITLE
Cannot build dozer with Java 9

### ISSUE THREAD

**Issue by jbq** [DozerMapper/dozer#555]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: 6.2.0-SNAPSHOT
* OS version: macOS 10.13.2
* JDK version: 9.0.4
  
## Whats the problem?
_Steps to reproduce:_
1. run mvn install
  
### Observed Results:
_What happened?  This could be a description, log output, etc._

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.684 s
[INFO] Finished at: 2018-02-24T09:16:07+01:00
[INFO] Final Memory: 74M/246M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:xjc (default) on project dozer-core: Execution default of goal org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:xjc failed: A required class was missing while executing org.codehaus.mojo:jaxb2-maven-plugin:2.3.1:xjc: com/sun/codemodel/CodeWriter
```  

See https://github.com/mojohaus/jaxb2-maven-plugin/issues/43

Removing `jaxb2-maven-plugin` and `xmlbeans-maven-plugin` from `core/pom.xml` and running with `-Dmaven.test.skip=true` the install goes fine.

**Comment by garethahealy** [comment]
@jbq ; going to wait a few months until adding java{X} support, to let all other components catch up. At that point, we'd probably go to the latest Java release, as they are doing shorter releases now, so Java10 will be out soon.

**Comment by garethahealy** [comment]
- http://blog.joda.org/2018/02/java-9-has-six-weeks-to-live.html

**Comment by garethahealy** [comment]
Module-info generator:
- https://github.com/moditect/moditect

**Comment by garethahealy** [comment]
Code and components build. OSGi tests fail, but need to wait for a new release of pax to fix.
- https://api.travis-ci.org/v3/job/372720183/log.txt

As core/components build, closing this ticket.
