### ISSUE TITLE
@Mapping with CustomConverter

### ISSUE THREAD

**Issue by calameda2** [DozerMapper/dozer#556]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: _____6.1.0
* OS version: _____
* JDK version: _____1.8
  
## Whats the problem?
I would like to know if you can perform a mapping of two classes with subclasses with annotations by combining it with a CustomConverter¿?¿?

**Comment by garethahealy** [comment]
@calameda2 ; have you tried to do this? if so, please share your code.

**Comment by calameda2** [comment]
Tengo que mapear clases muy grandes y estaba usando @Mapping para mapearlas pero algunas subclases son listas a mapear con una clase que contiene una lista por lo que me crree un converter. 

Me gustaría saber si puedo combinar las anotaciones que esto me devuelva un resultado y luego aplicar un converter para los campos listas?

**Comment by garethahealy** [comment]
@calameda2 ; have you tried doing it?

**Comment by calameda2** [comment]
I could not, I did not do it

**Comment by calameda2** [comment]
I would like to know if it is possible to do it?

**Comment by garethahealy** [comment]
There are not tests for that:
- https://github.com/DozerMapper/dozer/tree/master/core/src/test/java/org/dozer/functional_tests/annotation
- https://github.com/DozerMapper/dozer/blob/master/docs/asciidoc/documentation/annotations.adoc

You'll just have to try and see if it works...

**Comment by calameda2** [comment]
I think it can not be done because in the MappingProcessor it gets the result in createByCreationDirectiveAndMap and previously the converters are processed by returning the object from the mapUsingCustomConverter function so the annotations are not made. But I'm not sure how Dozzer works

**Comment by garethahealy** [comment]
@calameda2 ; can this be closed? seems more like a question than an issue.
