### ISSUE TITLE
EnumMappingTest showing exceptions in logs

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#594]
Tests are logging out exceptions, but not failing.

> [main] INFO com.github.dozermapper.core.DozerBeanMapperBuilder - Successfully loaded custom xml mappings from URL: [file:/home/travis/build/DozerMapper/dozer/core/target/test-classes/mappings/enumMapping.xml]
> [main] ERROR com.github.dozermapper.core.MappingProcessor - Field mapping error -->
>   MapId: null
>   Type: null
>   Source parent class: com.github.dozermapper.core.vo.enumtest.MyBeanPrimeString
>   Source field name: destType
>   Source field type: class java.lang.String
>   Source field value: BAZ
>   Dest parent class: com.github.dozermapper.core.vo.enumtest.MyBean
>   Dest field name: srcType
>   Dest field type: com.github.dozermapper.core.vo.enumtest.SrcType
> com.github.dozermapper.core.MappingException: Cannot convert [BAZ] to enum of type class com.github.dozermapper.core.vo.enumtest.SrcType

**Comment by garethahealy** [comment]
> [main] INFO com.github.dozermapper.core.DozerBeanMapperBuilder - Successfully loaded custom xml mappings from URL: [file:/home/travis/build/DozerMapper/dozer/core/target/test-classes/mappings/enumMapping.xml]
> [main] ERROR com.github.dozermapper.core.MappingProcessor - Field mapping error -->
>   MapId: null
>   Type: null
>   Source parent class: com.github.dozermapper.core.vo.enumtest.MyBeanPrimeInteger
>   Source field name: second
>   Source field type: class java.lang.Integer
>   Source field value: 3
>   Dest parent class: com.github.dozermapper.core.vo.enumtest.MyBean
>   Dest field name: srcTypeWithOverride
>   Dest field type: com.github.dozermapper.core.vo.enumtest.SrcTypeWithOverride
> com.github.dozermapper.core.MappingException: Cannot convert [3] to enum of type class com.github.dozermapper.core.vo.enumtest.SrcTypeWithOverride

**Comment by garethahealy** [comment]
Fail positive but test needs cleaning up.

**Comment by vadeg** [comment]
Exception is logged by `MappingProcessor` every time when exception occurs. Tests are testing that particular mappings are failed. If it is failing then test is successful. So from tests perspective everything is correct.
If an error message is confusing then there are two options:
* Change log level for specific tests (looks more as a workaround)
* Do not log messages in `MappingProcessor`. But there is an option exists when exception should be logged but mapping should be successful.
