### ISSUE TITLE
Cannot use default mapping in context based mapping

### ISSUE THREAD

**Issue by wangtora** [DozerMapper/dozer#604]
* Dozer version: 5.5.1
* OS version: Windows 10
* JDK version: 1.8
 
I have class B within A, which is going to be mapped to class T within S. I defined a mapping of B to T as:
`
<mapping map-null="false">
  <class-a>B</class-a>
  <class-b>T</class-b>
  <field map-id="case1">
    <a>sourceAsString</a>
    <b>source</b>
  </field>
</mapping>
`
When I tried to map A to S with "map(Object source, Object destination, String mapId)", I got "Class mapping not found by map-id: caseA". The A->S default mapping doesn't work.

I think in "MappingProcessor.getClassMap()", it got an exception in "classMappings.find()", without a chance to add default mapping. If this is the reason, is it a bug or specification?

**Comment by garethahealy** [comment]
@wangtora ; please provide a github repo, with a junit test showing the behaviour.

**Comment by garethahealy** [comment]
@wangtora ; repo referenced is empty... i don't see any code in it

**Comment by wangtora** [comment]
@garethahealy Sorry, I have the code added.

**Comment by Ranx0r0x** [comment]
The link associated with the comment above is pointing to the wrong location. This is the correct location.

https://github.com/wangtora/dozermapper_604

The previous link has the right text but clicking it refs to https://github.com/DozerMapper/dozer/issues/url
