### ISSUE TITLE
Bahavior of one-way custom mappings changed from 6.1.0 to 6.2.0

### ISSUE THREAD

**Issue by j-be** [DozerMapper/dozer#605]
## Whats your runtime?
* Dozer version: 6.2.0
* OS version: Linux Mint 18.3 with all updates installed
* JDK version: Oracle Java 8 JDK (1.8.0_161)
  
## Whats the problem?
_Steps to reproduce:_
1. Define a custom mapping in dozerBeanMapping.xml, like:
    <?xml version="1.0" encoding="UTF-8"?>
         <mappings xmlns="http://dozermapper.github.io/schema/bean-mapping"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://dozermapper.github.io/schema/bean-mapping
              https://dozermapper.github.io/schema/bean-mapping.xsd">
        <mapping type="one-way">
            <class-a>org.duckdns.owly.dozerOneWayTest.Dest</class-a>
            <class-b>org.duckdns.owly.dozerOneWayTest.Source</class-b>
        </mapping>
    </mappings>
2. Make sure both `Dest` and `Source` contain a member with the same name, including getters and setters and such.
3. Try to map an instance of `Source` with said member set to something to `Dest`.
  
### Observed Results:
Now up until Dozer 6.1.0 the member in the resulting instance of `Dest`would carry the same value as the one in `Source` does, but on Dozer 6.2.0 it is empty. This leads me to the assumption, that if a one-way mapping is defined, Dozer up to including 6.1.0 provides a default mapper in the inverse direction (i.e. from `Source` to `Dest` in this scenario), but Dozer 6.2.0 does not.

### Expected Results:
I would expect Dozer 6.2.0 to behave the same as Dozer 6.1.0 and below and provide a default mapper for the inverse direction of the defined one-way mapping.

## Link to GitHub repo with Unit test
https://github.com/j-be/dozer-one-way-test

## Edits

1. This behavior change also is not mentioned in https://dozermapper.github.io/gitbook/migration/v61-to-v62.html, which lead me to the assumption this behavior is actually unintended.

**Comment by garethahealy** [comment]
This is due to the following bug:
- https://github.com/DozerMapper/dozer/issues/451
- https://github.com/DozerMapper/dozer/pull/467

Its regarded as a bug fix, as if you explicitly set one-way but then attempt to map in the opposite direction, you are achieving bi-directional. 

If you want bi-directional, you should not set one-way mapping.

**Comment by j-be** [comment]
I see... Maybe to explain a bit more in detail: The issue we are facing with Dozer 6.2.0 is, that we have a custom one-way mapping from A to B, which maps a member of a member of A to a member of B, but we would still like to create kind of a template of an A from a given B, where we then populate said member of A using business logic and the value of the member in B. Imagine (omitted getters, setters, etc.):

    public class C {
        Long id;
        String name;
    }

    public class A {
        C c;
        String somethingMore;
        String somethingMoreMore;
        String evenMore;
    }

    public class B {
        Long c_id;
        String somethingMore;
        String somethingMoreMore;
        String evenMore;
    }

Now - as I understand it - I need a custom one-way mapping in `dozerBeanMapping.xml`, where `A`'s `c.id` is mapped to `B`'s `c_id` field. But still it is quite handy to just use:

    A a = mapper.map(someB, A.class);
    a.setC(myFancyService.getCById(someB.getC_id());

... instead of mapping all the rest by hand. Also defining an additional one-way mapping from B to A without any custom stuff in it seems overhead.

Regardless of that: I find the behavior of Dozer 6.2.0 a bit unintuitive... If a one-way mapping is really an enforced one-way mapping and the inverse mapping is not allowed I would expect Dozer to either throw an Exception or return `null`. But from what I see it does instantiate `Destination`, yet it leaves all members `null` (or default if they are primitive), which then leads to a `NullPointer` down the road, which is not immediately obvious where it comes from.

**Comment by j-be** [comment]
Yes, they are (see my example with `A`, `B` and `C` above - I only realize now my naming choice was really bad here...): 
* Mapping from `A` to `B` includes mapping `A`'s `c.id` to `B`'s `c_id` field, which requires a custom mapping, but for this direction only
* When mapping from `B` to `A` I do not care about neither `A.c`, nor `B.c_id`, since I have to lookup (think database) the right instance of `C` by using `B.c_id` and then set that value to `A.c`, so I am happy with the default mapping handling anything but `c` and `c_id` respectively.
* I could go for a bi-directional mapping, but as far as I understand it this would instantiate an instance of `C`, then apply `B`'s `c_id` to its `id` just to be overwritten afterwards. In addition this would fail in scenarios where `C` doesn't have a default public constructor, right?

My `dozerBeanMapping.xml` would look something like this:

    <mappings xmlns="http://dozermapper.github.io/schema/bean-mapping"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://dozermapper.github.io/schema/bean-mapping
         https://dozermapper.github.io/schema/bean-mapping.xsd">
         <mapping type="one-way">
             <class-a>A</class-a>
             <class-b>B</class-b>
            <field>
                <a>c.id</a>
                <b>c_id</b>
            </field>
         </mapping>
</mappings>

As mentioned: If I add a second one-way mapping to `dozerBeanMapping.xml`, like:

         <mapping type="one-way">
             <class-a>B</class-a>
             <class-b>A</class-b>
         </mapping>

... I get the behavior from Dozer 6.1.0. But it just seems weird to me to define a default mapping in a file used for custom mappings.

And I still think just returning an instance of the destination class without any members set is not the best behavior in such a scenario.
