### ISSUE TITLE
API Documentation 

### ISSUE THREAD

**Issue by jbolous** [DozerMapper/dozer#607]
There is a lack of documentation as to how to configure mappings using API instead of using XML. For example, I am trying to set the set-method for a field mapping however, it isn't clear as to how this can be accomplished and there is a lack of documentation as to how this can be accomplished. Another example would be setting the mapNull to false as a global configuration. It's not clear if global configurations can only be accomplished in XML still or it can be accomplished in API and how. 

Any insight on these would be greatly appreciated.

**Comment by garethahealy** [comment]
No, global config is not supported via APIMappings, as per:
- https://github.com/DozerMapper/dozer/search?q=ConfigurationBuilder&unscoped_q=ConfigurationBuilder

API mappings are not 100% feature comparable with XML

**Comment by FirstJavaMaster** [comment]
After such a long time passed, does the author have plans to provide an API-based global configuration?

**Comment by garethahealy** [comment]
@FirstJavaMaster ; do you want to contribute the code?

**Comment by FirstJavaMaster** [comment]
> @FirstJavaMaster ; do you want to contribute the code?

Thanks. I will give it a try. But I need some time to understand the existing code. Don't hold too much hope...
