### ISSUE TITLE
Lombok fails on java10

### ISSUE THREAD

**Issue by garethahealy** [DozerMapper/dozer#620]
- https://github.com/rzwitserloot/lombok/issues/1572

**Comment by garethahealy** [comment]
Related to:
- https://github.com/DozerMapper/dozer/issues/612

**Comment by robertnosko** [comment]
You can try the edge version: https://projectlombok.org/download-edge

**Comment by garethahealy** [comment]
@robertnosko ; i've already tried edge locally and it works, but the ticket is staying open until next release of lombok, so it can be included as a standard dependancy.
