### ISSUE TITLE
BeanFactory strategy does not refresh its classMap 

### ISSUE THREAD

**Issue by ShibuGoogle** [DozerMapper/dozer#637]
## Whats your runtime?
* Dozer version:  Since 5.5.1, reproducible even in 6.2.0
* OS version: MacOS high Sierra 10.13.3 
* JDK version: 1.8
  
## Whats the problem?

1.  Have Class A on left side to be mapped to Class B1 on right side
2.  Class B1 is extending from its parent Class B
3. Use Dozer XML mapping to instruct dozer to create Class B1 for Class A using BeanFactory class,
    XML mapping below,
  
  ```
  <mapping bean-factory="com.XXX.ABCBeanFactory">
		<class-a>com.XXX.A</class-a>
		<class-b>com.YYY.B</class-b>
    </mapping>
```

4. You will see that dozer will create Class B1 for Class A, but none of the fields of A gets mapped to Class B1.  Class B1 would always be empty with no field values.
  
### Observed Results:
Issue seems to be in org.dozer.MappingProcessor class @ line 230 in method,
private void map(ClassMap classMap, Object srcObj, Object destObj, boolean bypassSuperMappings, List<String> mappedParentFields, String mapId) {}
 Here destObj would be changed to B1, but classMap still points to ClassB.
In Line 230 we have a check that says refresh classMap only when it is null.
Instead it should be,  if (classMap == null   ||  destObj.getClass() != classMap.destClass.classToMap) {}
This would ensure to refresh classMap in scenarios where destinationObject was created using BeanFactory strategy.
### Expected Results:
After applying beanFactory strategy to create new destination class, all fields from source must be mapped to the destiantion fields.

## Link to GitHub repo with Unit test
N/A

**Comment by garethahealy** [comment]
@ShibuGoogle ; please raise a PR with the suggest change and unit tests.

**Comment by garethahealy** [comment]
@ShibuGoogle ; were you able to work on this?
