### ISSUE TITLE
Need more types of conversions supported

### ISSUE THREAD

**Issue by yuanpli** [DozerMapper/dozer#642]
Hi,

Can the dozer provide more types of conversions by default? 

Such as:
-  String to Enum
-  String to Boolean
-  Integer to Boolean
-  Nested Map key Mapping
etc.

For `Nested Map key Mapping`, it is imaged like:
```
    <mapping>
        <class-a>java.util.Map</class-a>
        <class-b>org.dozer.vo.example.ClassA</class-b>
        <field>
            <a key="key1">this</a>
            <b>nestedMap["key2"]</b>
        </field>
    </mapping>
```

Thanks a lot!

Br,
Yuanping

**Comment by garethahealy** [comment]
@yuanpli ; if you are willing to create PRs, i am willing to review/merge.

**Comment by yuanpli** [comment]
I find that the nested map conversion is supported via the following configuration.
```
    <mapping wildcard="true">
        <class-a>java.util.HashMap</class-a>
        <class-b>com.github.dozermapper.core.vo.map.SimpleObj</class-b>
        <field>
            <a key="key1">this</a>
            <b key="key2">nested2</b>
        </field>
    </mapping>
```
That is great and easy to understand.

**Comment by garethahealy** [comment]
@yuanpli ; are all conversions covered? can this be closed?

**Comment by yuanpli** [comment]
Hi @garethahealy, it seems that String/Integer to Boolean and reverse conversions are not covered by default after checked from the UT com.github.dozermapper.core.functional_tests.NewCustomConverterTest.
From my point of view, it would be better if can make these conversions be built-in functionalities. 
But anyway, it is OK for me to do with custom converter. 
If there is no plan, this ticket can be closed. 
Thanks!
