### ISSUE TITLE
field-exclude still tries to cast source to destination?

### ISSUE THREAD

**Issue by jjwilliams42** [DozerMapper/dozer#66]
Recently I have discovered issues with private constructors for our [widely used, large] API that does not work well with Dozer (because you cannot instantiate these objects outside of the API package). The solution was to ignore a property because essentially it was not needed (a web service to API mapping). The problem is that this STILL generates errors. Below is the error and the config xml I am using.

2013-01-18 15:18:57,631 ERROR [pool-nmr.endpoint.TaskWS/1.1/Port-thread-1] com.X.webservices.common.BaseWS: service name: updateMultipleTasksRequest Exception occured in TaskWSImp.updateMultipleTasksRequest() com.X.webservices.beans.order.Memo cannot be cast to com.X.Y.busobj.memo.Memo --java.lang.ClassCastException: com.X.webservices.beans.order.Memo cannot be cast to com.X.Y.busobj.memo.Memo

```
<mapping>
    <class-a>com.X.Y.busobj.order.Task</class-a>
    <class-b>com.X.webservices.beans.order.OrderTask</class-b>
    <field-exclude>
        <a>remarks</a>
        <b>remarks</b>
    </field-exclude>
</mapping>
```

Please note that the remarks field is a List of type Memo (don't know if this matters). I do not understand why it is attempting to CAST anything? I've excluded the remarks field in the xml.

**Comment by asarkar123** [comment]
How did you solve it. I am experiencing the same issue.

**Comment by jackjwilliams** [comment]
Honestly that was so long ago I have no idea what I was working on. I've been in c# for the last 5 years now almost. Sorry!
