### ISSUE TITLE
JAXB is deprecated in Java 9+

### ISSUE THREAD

**Issue by sylvain-rouquette** [DozerMapper/dozer#668]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: 6.2.0
* OS version: Win10
* JDK version: 10
* related to Java10 support: #612
  
## Whats the problem?
1. use Mapper.map to map an object to another
  
### Observed Results:
An exception is thrown:
org.dozer.MappingException: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBElement
This is because MappingProcessor.mapToDestObject is referencing javax.xml.bind.JAXBElement,
but this class is deprecated in Java 9+ and isn't included anymore.

## Workaround
import the dependency jaxb-api in your project.

**Comment by garethahealy** [comment]
This is already fixed on master:
- https://github.com/DozerMapper/dozer/commit/4008562406bbf2f2a275db6ce6bf29098845079b

Closing as will be fixed with next release.
