### ISSUE TITLE
Some questions about @Mapping annotations

### ISSUE THREAD

**Issue by FirstJavaMaster** [DozerMapper/dozer#700]
## Whats your runtime?
* Dozer version: 6.4.1
* JDK version: 1.8.0_171
  
I really like to configure the mapping between classes by @Mapping annotation. It almost solves all my current xml file based configurations. But there is still a little problem.

I have the following three classes: 

```
import lombok.Data;

@Data
public class SourceClass {
    private Integer id;
    private String name;
    private InnerClass innerClass;
}
```
```
import lombok.Data;

@Data
class InnerClass {
    private Integer id;
    private String name;
    private String code;
}
```
```
import com.github.dozermapper.core.Mapping;
import lombok.Data;

@Data
public class TargetClass {
    private Integer id;
    private String name;

    @Mapping("innerClass.code")
    private String innerClassCode;
}
```

`InnerClass` is a field of `SourceClass`. I want to convert `SourceClass` to `TargetClass`. What I want is the way to use `@Mapping("innerClass.code")` in `TargetClass` above. But the value of `innerClassCode` is always null in the result. I noticed that a comment in the @Mapping annotation is like this: 
> If property level is considered this annotation should be put on valid bean property getter method.

But as seen above, I use `lombok` in my project to automatically handle my get and set methods. I don't want to write its get method separately for the mapping of a field. So I want to ask if I can use the above (that is, annotate the property instead of the get method).

**Also worth noting is that when I use dozer in the spring boot 1.x version (eg 1.5.13.RELEASE), the above is effective. When I upgrade the springboot version to 2.x (now 2.0. 4.RELEASE) found this problem**

**Comment by garethahealy** [comment]
Since you mention the bug is only present in springboot2, please see this issue. does it help?
- https://github.com/DozerMapper/dozer/issues/273

**Comment by FirstJavaMaster** [comment]
Thanks for your help, follow the above tips I created a new project under the "non-springboot environment (ie ordinary java project)" and "springboot 2.x environment" to test. The test results surprised me: **In both projects, I can accurately achieve my expectations**.

So this problem should not be related to springboot's two class loaders (and I have no direct or indirect reference to spring devtools dependencies in my project). 

So I re-examined my original project, I think there may be a problem with `hibernate`. I mapped the associations between the tables in the entity class, similar to the following:
```
@Data
@Entity
@Table(name = "user")
@DynamicUpdate
Public class User {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     Private Long id;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "corporation_id", nullable = false)
     @NotFound
     Private Corporation corporation;

     Private String userName;

     Private String password;
}
```
As shown above, in the database, the `user` table has a `corporation_id` field, and the `corporation` field in the `User` entity class is associated with the `Corporation` entity class. I added `(fetch  = FetchType.LAZY)` after the `@ManyToOne` annotation, used to improve the response speed of the program. The problem is here. When using dozer mapping, it does not trigger "lazy loading", so the final result obtained is always "null".

I tested a previous project, which is based on springboot 1.x. It also uses a lazy loading strategy, but dozer works fine. I don't know much about the implementation principle of dozer. According to the existing clues, can I make dozer work well when lazy loading is in effect?

**Comment by FirstJavaMaster** [comment]
Bad news, I manually created a springboot project based on the H2 database. The test found that lazy loading did not affect the operation of the dozer. I now have to cut down the problematic project, and then see if I can find more information.

**Comment by garethahealy** [comment]
Those warnings are fine. 
1. LegacyPropertiesSettingsResolver; means you are not providing any custom config.
2. ELExpressionFactory; means you havent included el-impl on the classpath, so are not using expression replacements in the XML, i.e.: ${my-thing}

Since you've mentioned you are mapping ORM entities. Is the mapped object a proxy?
- https://github.com/garethahealy/dozer/blob/master/core/src/main/java/com/github/dozermapper/core/util/HibernateProxyResolver.java

**Comment by FirstJavaMaster** [comment]
Spring data jpa + hibernate has hidden the details of "proxy", I can be sure that the principle of hibernate implementation lazy loading is to use "proxy".

After my tests, I can now know the following:
+ Has nothing to do with the springboot version. (Yes, I thought it was a version issue at first, because dozer worked fine in another 1.x version of the springboot project. But I reduced the springboot version of the test project from 2.x to 1.x and the dozer still has a problem)
+ No problem if you don't use lazy loading

Below is my streamlined project code:
> https://github.com/FirstJavaMaster/demo-show-github.git

this is a standard maven project, you can use it to reproduce the problem, but need to do some preparation:

+ run the `temp_tong.sql` file under `resources` path in a mysql database. 
+ modify the database connection in the `application.properties` file.
+ to run your project(If you are using some IDEs, it will be very convenient).
+ use the "GET" method to access `localhost:8080/user/1`.

**Comment by garethahealy** [comment]
@FirstJavaMaster ; i wont be able to look at this for another few weeks - out of country. will try when i am back

**Comment by FirstJavaMaster** [comment]
@garethahealy Thank you for everything you have done, I will continue to test the code, I hope to narrow the problem. And wait for your good news.
