### ISSUE TITLE
@MappingOptions is not effective

### ISSUE THREAD

**Issue by kuoho** [DozerMapper/dozer#703]
## Whats the problem?
i use custome config to create mapper.and I want to map emptyString, i use @MappingOptions in both
src and dest Class, but it didn't effect. in dest Object ,there is only null.

```
@Configuration
public class MapperConfig {

    @Bean
    public Mapper dozerBeanMapper() {
        DozerBeanMapperBuilder builder = DozerBeanMapperBuilder.create()
                .withCustomConverter(new DateStringConvert(Date.class, String.class))
                .withCustomConverter(new BigdecimalToStringConvert(BigDecimal.class, String.class));
        return builder.build();
    }
}

@MappingOptions(mapEmptyString = OptionValue.ON)
public class Foo{
}
```

## Whats your runtime?
* Dozer version: _6.1.0____
* JDK version: ___1.8__

**Comment by kuoho** [comment]
i upgrade dozer to 6.4.1, but still not effective.

**Comment by garethahealy** [comment]
@kuoho ; can you provide a github repo with a junit test showing the behaviour

**Comment by kuoho** [comment]
> @kuoho ; can you provide a github repo with a junit test showing the behaviour

I build a project, it works very well。。。maybe my fault。。。sorry
