### ISSUE TITLE
Spring is taking more than 5 sec to create Dozer instance

### ISSUE THREAD

**Issue by venkypk** [DozerMapper/dozer#708]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: 6.4.1
* OS version: Windows 7
* JDK version: 1.8.0.131
  
## Whats the problem?
Spring is taking more than 5 sec to create an instance of dozer mapper, which is causing other bean to fails to initialize and throwing lots of warning messages.
  
### Observed Results:
_What happened?  This could be a description, log output, etc._
  
### Expected Results:
_What did you expect to happen?_

## Link to GitHub repo with Unit test
_The easiest way for us to fix issues, is if you provide a GitHub repo, using the latest release and a simple unit test._

**Comment by garethahealy** [comment]
@venkypk ; how many mappings are you loading? 1 or a million? you need to provide examples

**Comment by venkypk** [comment]
We have 19 mapping XML files and average less than 10 mapping fields in each. In this one Converter file, which has one Custom Converter mapped to 5 fields. We have noticed this issue after upgrading to 6.4.1, in 6.0.0 no issue with loading. 
There is performance issue with both of these versions, one of the file have 20 field mappings and it is taking around 275 milli secs to map it.

**Comment by garethahealy** [comment]
@venkypk ; please provide a github repo with a junit test showing the issue.
