### ISSUE TITLE
Cannot download 6.5.0-SNAPSHOT

### ISSUE THREAD

**Issue by kazuki43zoo** [DozerMapper/dozer#726]
The dozer-spring-boot-compatibility-checker's CI is failed because cannot download the dozer-spring-boot-starter (dozer-integrations).  

```
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.819 s
[INFO] Finished at: 2018-11-13T13:21:03Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dozer-spring-boot-compatibility-checker: Could not resolve dependencies for project com.example.dozerspringboot:dozer-spring-boot-compatibility-checker:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.github.dozermapper:dozer-spring-boot-starter:jar:6.5.0-SNAPSHOT: Failed to read artifact descriptor for com.github.dozermapper:dozer-spring-boot-starter:jar:6.5.0-SNAPSHOT: Could not find artifact com.github.dozermapper:dozer-integrations:pom:6.5.0-20181112.090911-25 in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
...
```

For details see https://travis-ci.org/kazuki43zoo/dozer-spring-boot-compatibility-checker/builds/454122300.

Could you deploy a latest SNAPSHOT again?

**Comment by garethahealy** [comment]
SNAPSHOTS are deployed on each build.

The last build:
- https://travis-ci.org/DozerMapper/dozer/jobs/453853265 

has logs which show it right at the end:
- https://api.travis-ci.org/v3/job/453853265/log.txt

**Comment by kazuki43zoo** [comment]
I rebuild my job at now, but it is failed. (result see [here](https://travis-ci.org/kazuki43zoo/dozer-spring-boot-compatibility-checker/jobs/454645281))

Probably, a root cause exists in dozer-integrations. I think that there is conflicting between with metadata and uploaded files(timestamp in filename). A timestamp is mixed with `20181112.090910` and `20181112.090911` .

> Failed to read artifact descriptor for com.github.dozermapper:dozer-spring-boot-starter:jar:6.5.0-SNAPSHOT: Could not find artifact com.github.dozermapper:dozer-integrations:pom:6.5.0-20181112.090911-25 in sonatype-snapshots

I see [dozer-integrations6.5.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/github/dozermapper/dozer-integrations/6.5.0-SNAPSHOT/) in sonatype-snapshots.

Name | Last Modified | Size | Description
-- | -- | -- | --
dozer-integrations-6.5.0-20181112.090910-25.pom | Mon Nov 12 09:09:11 UTC 2018 | 1384 |  
dozer-integrations-6.5.0-20181112.090910-25.pom.md5 | Mon Nov 12 09:09:11 UTC 2018 | 32 |  
dozer-integrations-6.5.0-20181112.090910-25.pom.sha1 | Mon Nov 12 09:09:11 UTC 2018 | 40 |  
dozer-integrations-6.5.0-20181112.090911-25.pom.asc | Mon Nov 12 09:10:44 UTC 2018 | 473

* maven-metadata.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata modelVersion="1.1.0">
  <groupId>com.github.dozermapper</groupId>
  <artifactId>dozer-integrations</artifactId>
  <version>6.5.0-SNAPSHOT</version>
  <versioning>
    <snapshot>
      <timestamp>20181112.090911</timestamp>
      <buildNumber>25</buildNumber>
    </snapshot>
    <lastUpdated>20181112090911</lastUpdated>
    <snapshotVersions>
      <snapshotVersion>
        <extension>pom</extension>
        <value>6.5.0-20181112.090911-25</value>
        <updated>20181112090911</updated>
      </snapshotVersion>
      <snapshotVersion>
        <extension>pom.asc</extension>
        <value>6.5.0-20181112.090911-25</value>
        <updated>20181112090911</updated>
      </snapshotVersion>
    </snapshotVersions>
  </versioning>
</metadata>
```

I guess that it can be resolved by deploying latest snapshot version again.

WDYT?

**Comment by garethahealy** [comment]
re-triggered:
- https://travis-ci.org/DozerMapper/dozer/builds/453853264

**Comment by kazuki43zoo** [comment]
@garethahealy Thanks! Rebuild is success!!

* https://travis-ci.org/kazuki43zoo/dozer-spring-boot-compatibility-checker/builds/454645280
