### ISSUE TITLE
XML Configuration: Field with line breaks can not be parsed

### ISSUE THREAD

**Issue by andriizakharchuk** [DozerMapper/dozer#727]
## Whats your runtime?
* Dozer version: 6.5.0
* JDK version: 1.8
  
## Whats the problem?
_Steps to reproduce:_
1. Add line breaks tabs or whitespaces to field name
  
### Observed Results:
If field contains line breaks it can not find getter/setter methods or throws MappingException when mapping type="one-way" and field is nested.

Here is an example of xml configuration file:
https://github.com/andriizakharchuk/dozer/blob/master/core/src/test/resources/mappings/fieldWithLineBreaks.xml
  
### Expected Results:
Field with line breaks should be parsed properly

## Link to GitHub repo with Unit test
https://github.com/andriizakharchuk/dozer/blob/master/core/src/test/java/com/github/dozermapper/core/functional_tests/builder/SimpleTest.java

**Comment by garethahealy** [comment]
https://github.com/DozerMapper/dozer/pull/728
