### ISSUE TITLE
Same-class mapping wrongly re-uses value

### ISSUE THREAD

**Issue by clapointe** [DozerMapper/dozer#730]
## Whats your runtime?
* Dozer version: 6.4.1
* OS version: Windows 10
* JDK version: 1.8.0
  
## Whats the problem?
_Steps to reproduce:_
1. Have the following classes  : 
```
class SomeDto {
private SomeOtherDto firstField;
private SomeOtherDto secondField;
}
class SomeOtherDto {
// any fields
}
```
2. Map the class SomeDto to itself, while the destination object has the same value in both fields :
```
SomeDto dto = new SomeDto();
dto.firstField = new SomeOtherDto("one");
dto.secondField = new SomeOtherDto("two");

SomeDto dbDto = new SomeDto();
dbDto.firstField = new SomeOtherDto("three");
dbDto.secondField = dbDto.firstField;

mapper.map(dto, dbDto); // update dbDto with values from dto. This is generic code, is useful for classes where map-null="false" for example.
```
  
### Observed Results:
dbDto now looks like this:
firstField : SomeOtherDto("one")
secondField : SomeOtherDto("one")

### Expected Results:
firstField : SomeOtherDto("one")
secondField : SomeOtherDto("two")

### Comments:
I think this is linked to the check on whether a value has already been mapped, in order to avoid recursive mapping. I couldn't figure out any more from just looking at the code...

Thank you for your time!

**Comment by grubeninspekteur** [comment]
This is desired behavior. Dozer will not create a new object (SomeOtherDto) if one is already present. It copies the string value "two" to the existing SomeOtherDto (the order is arbitrary), followed by the "one". Since firstField and secondField are the same object, they will continue to hold the same value afterwards.

```java
A a1 = new A();
A a2 = new A();
a1.setNumber("one");
a2.setNumber("two");
B from = new B();
B to = new B();
from.setA(a1);
to.setA(a2);
DozerBeanMapperBuilder.buildDefault().map(from, to);
assertSame(a2, to.getA());
assertEquals("one", to.getA().getNumber());
```

**Comment by clapointe** [comment]
I see... Guess I'll just use pass-by-reference, then...
Thanks for the reply :)
