### ISSUE TITLE
Instance to Instance mapping with proto messages

### ISSUE THREAD

**Issue by dvivarelli** [DozerMapper/dozer#733]
* Dozer version: 6.4.1
* OS version: Windows 10 Home
* JDK version: 1.8.0_181
  

In case of proto message to proto message mapping, the mapping does not work and thrown a Mapping Exception 
I have an instance of a proto Message and I wanto to use mapper.map(src,dest) function to copy the source obj into the destination.
The destination is not a ProtoBeanBuilder (but it is a proto Message) so a MappingException is thrown.

Is there any method to enable instance to instance copy between to messages?
That functionality is very useful to implement to use the assembler pattern.

In my opinion should be enough put the following  code in ProtoFieldPropertyDescriptor:
if (!(bean instance of ProtoBeanBuilder) && bean instanceof Message){
  bean = new ProtoBeanBuilder( ((Message)bean).toBuilder(), ((Message)bean).getClass()) );
}

**Comment by garethahealy** [comment]
@jbq ; can you please have a look at this

**Comment by jbq** [comment]
Hi @garethahealy no unfortunately I can't, not doing any Java stuff ATM

**Comment by garethahealy** [comment]
no worries.
