### ISSUE TITLE
Existing object in target is not reused but reinstantiated

### ISSUE THREAD

**Issue by akloeber** [DozerMapper/dozer#739]
## Whats your runtime?
* Dozer version: 6.4.1
* OS version: Mac OS 10.14, Windows 10
* JDK version: 1.8.0_152
  
## Whats the problem?
_Steps to reproduce:_
1. Run `mvn test` after cloning the example repository at https://github.com/akloeber/dozer-issue
2. The test case fails on the last 2 assertions when it is checked that the identity of the nested object has not changed and the value of field `internal` is still there.
  
### Observed Results:
There is a POJO structure which is 3 layers deep:
1. A root object (`RootA` resp. `RootB`)
2. The root object has a field `list` which contains a list with one item (`ItemA` resp. `ItemB`)
3. Each item references another nested object (`NestedA` resp. `NestedB`)

The list in the root objects is mapped with `relationship-type="non-cumulative"`. When comparing the items via `ItemA|B#equals` only the `id` property is checked. 
This is the configuration:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns="http://dozermapper.github.io/schema/bean-mapping"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://dozermapper.github.io/schema/bean-mapping http://dozermapper.github.io/schema/bean-mapping.xsd">
    <mapping>
        <class-a>dozer.model.RootA</class-a>
        <class-b>dozer.model.RootB</class-b>
        <field relationship-type="non-cumulative" remove-orphans="true">
            <a>list</a>
            <b>list</b>
            <a-hint>dozer.model.ItemA</a-hint>
            <b-hint>dozer.model.ItemB</b-hint>
        </field>
    </mapping>
</mappings>
```

After invocation of the dozer mapper the existing instance of `NestedA` has been replaced with a new instance instead of been reused. Therefore the original value of the `internal` field is lost.
In contrast to that, the list items itself have been reused correctly. The problem only occurs with the nested objects below those list items.

### Expected Results:
The existing object should be reused.

In our real use case the target object structure is loaded from the database via JPA. The source object is a DTO to represents changes to be applied. As only a subset of fields may be changed through the DTO, the re-instantiated JPA-object is incomplete and thus provokes constraint violations and other errors later-on when it is stored in the database.

## Link to GitHub repo with Unit test
https://github.com/akloeber/dozer-issue

**Comment by grubeninspekteur** [comment]
Can confirm this as a bug. The issue stems from these lines in `MappingProcessor`:

```java
 // 1596766 - Recursive object mapping issue. Prevent recursive mapping
        // infinite loop
        // In case of "this->this" mapping this rule should be omitted as processing is done on objects, which has been
        // just marked as mapped.
        if (!(DozerConstants.SELF_KEYWORD.equals(srcFieldName) && DozerConstants.SELF_KEYWORD.equals(destFieldName))) {
            Object alreadyMappedValue = mappedFields.getMappedValue(srcFieldValue, destFieldType, fieldMap.getMapId());
            if (alreadyMappedValue != null) {
                return alreadyMappedValue;
            }
        }
```
In order to check whether the list item should be updated or inserted, Dozer creates a comparison object and compares it with the existing one. The new object is stored to prevent infinite recursion, however it is not removed from the MappedFieldsTracker when it is thrown away.
