### ISSUE TITLE
Wrong mapping when List nested in Map

### ISSUE THREAD

**Issue by doshide** [DozerMapper/dozer#746]
Map<String, List<Map<String, Object>>> is wrongly casted to Map<String, List< String >>
testing with version 6.4.1

![1](https://user-images.githubusercontent.com/6176711/54270715-006f3600-45bb-11e9-8121-0c1e77f6bb89.jpg)

FromObject And ToObject are simply like this:
![2](https://user-images.githubusercontent.com/6176711/54270949-796e8d80-45bb-11e9-8f46-7bdb4d094540.jpg)

**Comment by garethahealy** [comment]
@doshide ; please provide a github repo showing the test, not screenshots of code.
