### ISSUE TITLE
Misinterpretation of allowed format at converting JSR310 Date and Time to String.

### ISSUE THREAD

**Issue by yoshikawaa** [DozerMapper/dozer#747]
## Whats your runtime?
* Dozer version: 6.4.1
* OS version: CentOS 7.4
* JDK version: 1.8.x
  
## Whats the problem?
I copied with converting from JSR310 `ZonedDateTime` to `String`.
I defined `date-format` based on the pattern allowed by `DateTimeFormatter`.
But pattern `V` not allowed and got `IllegallArgumentException`.

```xml
<field>
    <a>zonedDateTimeObject</a>
    <b date-format="uuuu/MM/dd HH:mm:ss.SSSZZZZZ'['VV']'">stringObject</b>
</field>
```
`u` is also interpreted as the day of the week, not the year, and is allowed as a result.

### Observed Results:
It seems the bug of allowed format interpretation.
If destination is `String` object, Actually `SimpleDateFormat` is used to validate `date-format` instead of `DateTimeFormatter`.

Please look these classes.
* [PrimitiveOrWrapperConverter.java#L125](https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/com/github/dozermapper/core/converters/PrimitiveOrWrapperConverter.java#L125)
* [StringConverter.java#L38](https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/com/github/dozermapper/core/converters/StringConverter.java#L38)
* [DateFormatContainer.java#L70-L72](https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/com/github/dozermapper/core/converters/DateFormatContainer.java#L70-L72)

### Expected Results:
When converting from JSR310 Date and Time to `String`, should use `DateTimeFormatter` to validate `date-format`.

## Link to GitHub repo with Unit test
none.

**Comment by kazuki43zoo** [comment]
@garethahealy Thanks for merging my PR! When are you planning to release 6.5?

**Comment by yoshikawaa** [comment]
I'm happy that this problem is fixed, thanks @kazuki43zoo @garethahealy !

**Comment by garethahealy** [comment]
@kazuki43zoo ; theres an outstanding java11 build problem:
- https://groups.google.com/forum/?nomobile=true#!topic/ops4j/_WbW6xzCgSU

I'd like to wait until i've had some feedback on this. If its going to take a while to fix, i'll release soon - next week or so.

**Comment by kazuki43zoo** [comment]
@garethahealy Thank you for reaction!! I can wait to fix build error on JDK 11 :D
