### ISSUE TITLE
Inheritance mapping issue with abstract class

### ISSUE THREAD

**Issue by jajajaja** [DozerMapper/dozer#749]
## Whats your runtime?
* Dozer version: 6.4.1
* OS version: Windows
* JDK version: openjdk version "1.8.0_202"
  
## Whats the problem?
_Steps to reproduce:_
1. Create following classes:
```
class S {String a; String b; String c;}
abstract class A {String a}
class B extends A {String b}
class C extends B {String c}
```
2. Mapping configuration:
```
  <mapping>
    <class-a>com.github.dozermapper.core.vo.inheritance.abstractissue.S</class-a>
    <class-b>com.github.dozermapper.core.vo.inheritance.abstractissue.B</class-b>
  </mapping>

  <mapping>
    <class-a>com.github.dozermapper.core.vo.inheritance.abstractissue.S</class-a>
    <class-b>com.github.dozermapper.core.vo.inheritance.abstractissue.C</class-b>
  </mapping>
```
3. Dozer produces error for following order of mapping operations: 
```
   S source = newInstance(S.class);
   A destinationA = mapper.map(source, A.class);
   B destinationB = mapper.map(source, B.class);
```
### Observed Results:
```
  MapId: null
  Type: null
  Source parent class: com.github.dozermapper.core.vo.inheritance.abstractissue.S
  Source field name: c
  Source field type: class java.lang.String
  Source field value: C
  Dest parent class: com.github.dozermapper.core.vo.inheritance.abstractissue.B
  Dest field name: c
  Dest field type: null
com.github.dozermapper.core.MappingException: No read or write method found for field (c) in class (class com.github.dozermapper.core.vo.inheritance.abstractissue.B)
```
  
### Expected Results:
Mapping should be successful or at least mapping result should be independent of order of mapping operations. 

## Link to GitHub repo with Unit test
Please see unit test which reproduce the problem 
https://github.com/jajajaja/dozer/commit/6b0837118dd0b239dcada069fafac9f1aa587bf8

**Comment by oliverlockwood** [comment]
@garethahealy I believe I'm hitting this same issue in Dozer 6.5.2.  I can't see a commit or related PR, so I'm wondering why it was closed.  Is this fixed or did you just decide to close it without fixing?

**Comment by garethahealy** [comment]
@oliverlockwood ; i dont have the time currently to work on the project. if you can raise a PR to fix it, great. if not and this is causing blocking issues, I'd suggest looking at another mapping project:
- https://github.com/DozerMapper/dozer#project-activity
