### ISSUE TITLE
map key contains underLine,do not support underLine to hump

### ISSUE THREAD

**Issue by richardplas** [DozerMapper/dozer#751]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: _____
* OS version: _____
* JDK version: _____
  
## Whats the problem?
_Steps to reproduce:_
1. _____
2. _____
3. _____
  
### Observed Results:
_What happened?  This could be a description, log output, etc._
  
### Expected Results:
_What did you expect to happen?_

## Link to GitHub repo with Unit test
_The easiest way for us to fix issues, is if you provide a GitHub repo, using the latest release and a simple unit test._

**Comment by grubeninspekteur** [comment]
Please provide a description of the issue and a minimal example, preferably in the form of a new Github repository containing a unit test.

**Comment by garethahealy** [comment]
as no description, closing.
