### ISSUE TITLE
Custom converter updates destination only if it's a field

### ISSUE THREAD

**Issue by rsparkyc** [DozerMapper/dozer#76]
I'm using a custom converter to convert from a String to a custom object.  When I have an object that has a field that uses the custom converter, everything works fine.  However, if I just have a String and I try to convert that into my custom object, my destination object never gets updated, even though my custom converter gets called.  Here's a simplified example:

``` java
public class AClass {
    private String customField;
    //getter & setter...
}

public class BClass {
    private CustomObject customField;
    //getter & setter
}
```

I've implemented a basic custom converter, and since that gets called every time I'll omit it from here.

Now my calling code

``` java
AClass a = new AClass();
a.setCustomField("abc123");
BClass b = new BClass();
beanMapper.mapFrom(a, b);
//This updates b.getCustomField()

String str = "abc123";
CustomObject obj  = new CustomObject();
//tried setting obj to null at first but this gives me the following error:
//Request processing failed; nested exception is org.dozer.MappingException: Destination object must not be null
beanMapper.mapFrom(str, obj);
//this does not update obj
```

Am I doing something wrong or is this an actual bug?

**Comment by garethahealy** [comment]
@rsparkyc ; is this still an issue? if so, can you create a github repo, that includes a unit test showing this behaviour and link it here.

**Comment by garethahealy** [comment]
@rsparkyc ; any update?

**Comment by rsparkyc** [comment]
Sorry, it's been years since I touched this, so I'd have to do a lot of digging to reproduce this.  You can probably close this if you want (or try to reproduce yourself)
