### ISSUE TITLE
There is no release since Apr, 2014?

### ISSUE THREAD

**Issue by mufasa1** [DozerMapper/dozer#762]
May I ask why there is no release for 5 years?
The Jar file that I download from maven is still 5 years ago...
So many new features and issues fixing are still not be published....
What's you plan to publish them?

Thank you in advance!

**Comment by garethahealy** [comment]
You are probably looking at the wrong GAV:
- https://github.com/DozerMapper/dozer/tree/master/docs/asciidoc/migration
- https://mvnrepository.com/artifact/com.github.dozermapper/dozer-core
