### ISSUE TITLE
ClassLevelFieldMappingGenerator should ignore synthetic fields

### ISSUE THREAD

**Issue by dimitarp** [DozerMapper/dozer#763]
* Dozer version: 6.5.0
* JDK version: 1.8.0_212
  
_Steps to reproduce:_
1. Mapping "declared fields accessible" classes
2. Run unit tests coverage with [jacoco maven plugin](https://www.jacoco.org/jacoco/trunk/doc/maven.html)
  
### Observed Results:
```
ERROR c.g.d.core.MappingProcessor - Field mapping error -->
  MapId: null
  Type: null
  Source parent class: A
  Source field name: $jacocoData
  Source field type: class [Z
  Source field value: [Z@16be6b36
  Dest parent class: B
  Dest field name: $jacocoData
  Dest field type: [Z
java.lang.OutOfMemoryError: Java heap space
```
  
### Expected Results:
Dozer should ignore the synthetic jacoco fields. From [jacoco FAQ](https://www.eclemma.org/jacoco/trunk/doc/faq.html):

> **My code uses reflection. Why does it fail when I execute it with JaCoCo?**
> To collect execution data JaCoCo instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic.
> Please change your code to ignore synthetic members. This is a good practice anyways as also the Java compiler creates synthetic members in certain situation.

**Comment by johannschenkl** [comment]
@garethahealy Has this been fixed or is this a not a dozer issue? We're currently seeing excessive memory (OOM) usage after upgrading to dozer 6.5.0 when jacoco is enabled. Thanks!

**Comment by garethahealy** [comment]
@johannschenkl ; no, I've not had time to investigate (and won't have any in the coming months). if you want to investigate/raise a PR, happy to review/merge.

**Comment by johannschenkl** [comment]
@garethahealy ok, perfect. it seems like just ignoring synthetic fields fixes the issues. I'll test a bit more and then try to raise a PR.
