### ISSUE TITLE
Dozer Object Mapping

### ISSUE THREAD

**Issue by JayaPrakashkk4** [DozerMapper/dozer#764]
I have following classes

// source clasess

Class A
{
    private List<Info> infoList;
    private String parent_Id;
},

Class Info
{
   private String child_name;
   private String child_Id;
}

// destination classes

Class B
{
    private List<Data> dataList;
}

 Class Data
 {
    private String data_parent_id;
    private String data_child_id;
    private String data_name;
 }

Now how to map class A to Class B . I have tried with the following mapping configuration but I am not sure how to refer parent_id from child object.

    mapping between A to B : 

    dataList:infoList

    mapping for Info to Data object :

     data_name:child_name,
     data_child_id:child_id,

Now I am asking how to map data_parent_id to #A.parent_id .

     i.e data_parent_id:#A.parent_id

All the classes are from third party sources I can't change the structure of it.

**Comment by garethahealy** [comment]
Can you provide a github repo showing the code? Its a lot easier to understand than reading a fake example

**Comment by JayaPrakashkk4** [comment]
I can't share the repo as it is private. So please let me know what you din't understand from the example.

**Comment by garethahealy** [comment]
You cant make a generic example and push it to github?
