### ISSUE TITLE
Add support for specifying event listeners for the Spring Boot auto-configuration

### ISSUE THREAD

**Issue by dsboger** [DozerMapper/dozer#766]
## Whats your runtime?
* Dozer version: 6.4.1
  
## Whats the problem?
Cannot configure event listeners for the default mapper.
  
### Expected Results:
Some property like:
```
dozer.event-listeners=my.EventListener,other.EventListener
```
would instantiate and inject the listeners into the default mapper.

If there is interest, I can start a PR.

Thanks for your efforts!

**Comment by garethahealy** [comment]
@dsboger ; if you are happy to do the work, i am happy to review/merge.

**Comment by dsboger** [comment]
Actually, I wasn't aware of the possibility of defining the listeners as beans. Although the property-way also seems to make sense, the bean-way is already very convenient. Consequently, this moved to a very low priority to me. 

Feel free to close.
