### ISSUE TITLE
Feature request: Configure custom converter annotation-driven.

### ISSUE THREAD

**Issue by rmvanderspek** [DozerMapper/dozer#779]
### Feature request:
_When using `@Mapping` for field mapping, it would be nice to have features like `@CustomConverters` also configurable via annotations. Now one has to combine both types of configuration, which makes the code hard to read and to maintain._

**Comment by garethahealy** [comment]
@rmvanderspek ; am open to PRs if you have the time to do the work.

**Comment by rmvanderspek** [comment]
I have made an implementation for @Converter annotation. I try to run the unit tests in this project, but Intellij does not recognize test files. Any suggestions on what could be going wrong? (I have already tried several options, such as invalidating cache / restart).
