### ISSUE TITLE
WARN is logged on Mapper creation if javax.el (optional module) is not on classpath

### ISSUE THREAD

**Issue by Blackbaud-MikeLueders** [DozerMapper/dozer#780]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: 6.5.0
* OS version: Mac, Mojave
* JDK version: 1.8
  
## Whats the problem?
com.github.dozermapper.core.el.ELExpressionFactory#isSupported(java.lang.ClassLoader) logs a warning if javax.el is not on the classpath.
  
### Observed Results:
A warning is logged.
  
### Expected Results:
Warnings should indicate a potential problem.  Not having what is documented as an optional module should not be considered a potential problem.

**Comment by Blackbaud-MikeLueders** [comment]
i can easily submit a fix if there is agreement that this is an issue.  i have a work-around but it seems like this will be a problem for any organization that pays attention to warnings in their logs.

**Comment by garethahealy** [comment]
i see this as a nitpick as most alerting systems can dampen / ignore matching alerts but if you want to raise the PR, go for it.

**Comment by laliluna** [comment]
I consider this an issue as well. If this is nitpicking really depends how your organization is reacting to log warnings. Our average Java stack has 100 - 200 libraries. Thankfully they tend not to spit out warnings when optional requirements are missing and they work fully functional. Therefor we get an alarm immediately when there is a warning.

Filtering out warnings is a workaround but there is a fair chance that you hide other warnings with similar text.

**Comment by garethahealy** [comment]
like I said, last year. If someone wants to raise a PR, go for it.
