### ISSUE TITLE
Hibernate non Lazy Load support

### ISSUE THREAD

**Issue by georgesq** [DozerMapper/dozer#781]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: _5.5.1____
* OS version: _ubuntu____
* JDK version: _1.8.xx____
  
## Whats the problem?
The class Jdk8CompatibilityConverter doesnt have hibernate non lazy load support
 
### Observed Results:
Fields Lazy load is loaded ever
  
### Expected Results:
Not load lazy load fields

Line added:
        } else if (!Hibernate.isInitialized(source)) {
            return Boolean.TRUE;
        }
and pom.xml
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>5.4.9.Final</version>
		</dependency>

how i can create a branch with this change???

**Comment by kdebski85** [comment]
I think there should be an option in FieldsMappingOption to enable it.
It shouldn't be automatically enabled for all classes.
In many cases developers would like to map even if a field is lazy and not initialized.
