### ISSUE TITLE
Dozer 6.5.0 performance measurement

### ISSUE THREAD

**Issue by Saraa1979** [DozerMapper/dozer#782]
We are using Dozer version 5.4.0 with  JDK 1.8 and facing some performance issue. I am planning to use new dozer jar released under 6.5.0 version.  

I would like to know if any significant performance improvement has been measured with new release. Kindly provide your thoughts and suggestions.  

<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-core</artifactId>
    <version>6.5.0</version>
</dependency>

**Comment by garethahealy** [comment]
No performance testing / improvements have been done for 6.5.0

**Comment by Saraa1979** [comment]
Thank you,  @garethahealy.

So would you be advising to continue with 5.4.0 or still upgrade to 6.5.0.
