### ISSUE TITLE
[Question] JSON/YAML instead of XML for mappings

### ISSUE THREAD

**Issue by gurpal2000** [DozerMapper/dozer#784]
Are there any plans to make Dozer work with json/yaml rather than XML for the mappings?

**Comment by garethahealy** [comment]
No, but you can provide any type of structure you want by implementing a:
- https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/com/github/dozermapper/core/builder/BeanMappingsBuilder.java

See xml for ideas:
- https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/com/github/dozermapper/core/builder/xml/BeanMappingXMLBuilder.java
