### ISSUE TITLE
Support Hibernate5 Proxy / ByteBuddy Proxy

### ISSUE THREAD

**Issue by jcamerin** [DozerMapper/dozer#791]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: 6.5.0
* JDK version: Java 8
* Hibernate 5.4.12
  
## Whats the problem?
_Steps to reproduce:_
1. Create mapping from a Hibernate 5 entity to another class with a BeanFactory specified in the mapping
2. Retrieve the entity through Hibernate call mapper convert with the entity and the target class.
  
### Observed Results:
Hibernate 5 uses ByteBuddy proxies, so entity class name is of the form com.messagegears.accelerator.entity.AbstractSchedule$HibernateProxy$mDeBjjns
Dozer does not have proxy support for ByteBuddy and does not turn this into 
com.messagegears.accelerator.entity.AbstractSchedule
Dozer does not find a mapping for com.messagegears.accelerator.entity.AbstractSchedule$HibernateProxy$mDeBjjns, uses a default mapping
  
### Expected Results:
Hibernate to resolve the actual class and specified mapping from the Hibernate proxy

## Link to GitHub repo with Unit test
Not so easy with Hibernate. I think this is straightforward enough, i.e. need support for ByteBuddy proxies.

**Comment by jcamerin** [comment]
@garethahealy I see this was tagged as an enhancement and closed.  I dont see any links to a code change or another ticket tracking it as an enhancement.  Could you point me in the right direction?

**Comment by garethahealy** [comment]
@jcamerin ; I don't have the time currently to implement this. if you or anyone else would like to pick it up, happy to re-open and review/merge any PRs.

**Comment by alexandru-popa-socgen** [comment]
This is an unsupported feature currently in the latest 7.0.0 version, right?

**Comment by AlcipPopa** [comment]
Hi, is this still a thing to be implemented?
