### ISSUE TITLE
Injected Custom Converters are not used #110 

### ISSUE THREAD

**Issue by warrenc5** [DozerMapper/dozer#792]
Hi I'm reopening this issue [110]( https://github.com/DozerMapper/dozer/issues/110) with spring dozer 6.5.0 and spring boot 2.2.6 because I realize I've hit this problem everytime I try to use dozer with spring and end up falling back to dozer 4 no spring.

So I have a 
```
@Component
public class ExceedenceConverter extends DozerConverter<Exceedence, ExceedenceDto> implements MapperAware {
}

```

And I am calling map and debugging the MappingProcessor.mapGeneral

I can see  

```
private final List<CustomConverter> customConverterObjects;
    private final Map<String, CustomConverter> customConverterObjectsWithId;
```

both contain my Converter

but 

```
Class<?> converterClass = MappingUtils.findCustomConverter(converterByDestTypeCache, classMap.getCustomConverters(), srcObj .getClass(), destType);
```

Uses a classMap which only contains UUID converter.

It seems that 

```
mapping = classMapBuilder.createDefaultClassMap(globalConfiguration, srcClass, destClass);
```

Does not include anything about my convertor or class.

So my convertorClass is always null.

I am a sad panda.

**Comment by warrenc5** [comment]
From what I can tell the CustomConverters from DozerBeanMapperFactoryBean never get into the GlobalConfiguration of the Mapper on build() 

I don't know why - but that's effectively what @friednail  hacky workaround does is use reflection to copy the converters into the mappers global configuration. 

That should be done by the DozerBeanMapperBuilder imho.

**Comment by warrenc5** [comment]
Yes! Thanks to @friednail for doing the hard ground work. I was able to prove it by inserting this method after autowiring mapper into my service.

It creates a description for every converter in the global configuration.

```
 private void fixMapper() throws IllegalArgumentException, IllegalAccessException, NoSuchFieldException, ClassNotFoundException {
        Field globalConfigurationField = DozerBeanMapper.class.getDeclaredField("globalConfiguration");
        globalConfigurationField.setAccessible(true);
        com.github.dozermapper.core.classmap.Configuration globalConfiguration = (com.github.dozermapper.core.classmap.Configuration) globalConfigurationField.get(mapper);

        Field customConvertersField = DozerBeanMapper.class.getDeclaredField("customConverters");
        customConvertersField.setAccessible(true);
        List<CustomConverter> customConverters = (List<CustomConverter>) customConvertersField.get(mapper);

        for (CustomConverter cc : customConverters) {
            CustomConverterDescription ccd = new CustomConverterDescription();
            ccd.setClassA(Class.forName(((ParameterizedType)cc.getClass().getGenericSuperclass()).getActualTypeArguments()[0].getTypeName()));
            ccd.setClassB(Class.forName(((ParameterizedType)cc.getClass().getGenericSuperclass()).getActualTypeArguments()[1].getTypeName()));
            ccd.setType(cc.getClass());
            globalConfiguration.getCustomConverters().addConverter(ccd);
        }
    }
```

**Comment by warrenc5** [comment]
Additionally please add a default constructor to DozerBeanMapperFactoryBean so we can debug its construction.

**Comment by jbhamilton** [comment]
@warrenc5 Thank you for the solution. Running that is still the only way to properly register custom converters even though the first issue was opened 8 years ago :cricket:
