### ISSUE TITLE
java.util.ConcurrentModificationException when I process many objects

### ISSUE THREAD

**Issue by ParasMittal** [DozerMapper/dozer#794]
One process works fine but when I process many objects, is not working

Java 1.8
Pom config:
`net.sf.dozer
            dozer
            5.5.1`
spring config:
`@Bean(name = "lazyLoadFieldMapper")
    public DozerBeanMapper dozerLazyLoadFieldMapperBean() {
        DozerBeanMapper mapper = new DozerBeanMapper();
        mapper.setCustomFieldMapper(new LazyLoadSensitiveMapper());
        return mapper;
    }`

    class LazyLoadSensitiveMapper implements CustomFieldMapper {

        @Override
        public boolean mapField(Object source, Object destination, Object sourceFieldValue, ClassMap classMap,
                FieldMap fieldMapping) {

            if (!(sourceFieldValue instanceof AbstractPersistentCollection)) {
                // Allow dozer to map as normal
                return false;
            }

            // Check if field is already initialized
            if (((AbstractPersistentCollection) sourceFieldValue).wasInitialized()) {
                // Allow dozer to map as normal
                return false;
            }
            return true;
        }

    }

    

We call mapper.map() under a asyn thread and create a cloned object.

Exceptions sometimes under heavy traffic we get:
java.util.ConcurrentModificationException\n\tat java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)\n\tat java.util.ArrayList$Itr.next(ArrayList.java:851)\n\tat org.hibernate.collection.internal.AbstractPersistentCollection$IteratorProxy.next(AbstractPersistentCollection.java:845)\n\tat org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:810)\n\tat org.dozer.MappingProcessor.addOrUpdateToList(MappingProcessor.java:894)\n\tat org.dozer.MappingProcessor.mapListToList(MappingProcessor.java:730)\n\tat org.dozer.MappingProcessor.mapCollection(MappingProcessor.java:580)\n\tat org.dozer.MappingProcessor.mapOrRecurseObject(MappingProcessor.java:453)\n\tat org.dozer.MappingProcessor.mapFromFieldMap(MappingProcessor.java:361)\n\tat org.dozer.MappingProcessor.mapField(MappingProcessor.java:307)\n\tat org.dozer.MappingProcessor.map(MappingProcessor.java:267)\n\tat org.dozer.MappingProcessor.mapToDestObject(MappingProcessor.java:216)\n\tat org.dozer.MappingProcessor.createByCreationDirectiveAndMap(MappingProcessor.java:196)\n\tat org.dozer.MappingProcessor.mapGeneral(MappingProcessor.java:170)\n\tat org.dozer.MappingProcessor.map(MappingProcessor.java:104)\n\tat org.dozer.MappingProcessor.map(MappingProcessor.java:99)\n\tat org.dozer.DozerBeanMapper.map(DozerBeanMapper.java:120)

Unable to share a git repo where this issue can we replicated as this happens rarely under heavy traffic.

**Comment by grubeninspekteur** [comment]
If you map from multiple threads into the same collection, there will be concurrent modification of that list. There is nothing Dozer can do to prevent that.
