### ISSUE TITLE
Update org.objenesis:objenesis dependency from 2.6 to 3.1

### ISSUE THREAD

**Issue by holgerhaag** [DozerMapper/dozer#800]
## Whats your runtime?

* Dozer version: 6.5.0
  
## Whats the problem?
_Steps to reproduce:_
1. include mockito and dozer as maven dependencies
2. use maven-enforcer-plugin withdependencyConvergence
3. run maven build
  
### Observed Results:

Dependency convergence error for org.objenesis:objenesis:2.6 paths to dependency are:
+-de.softconex.connectors:dc-ndc-mappers:2.31.1-SNAPSHOT
  +-com.github.dozermapper:dozer-core:6.5.0
    +-org.objenesis:objenesis:2.6
and
+-de.softconex.connectors:dc-ndc-mappers:2.31.1-SNAPSHOT
  +-de.softconex.connectors:dc-test-utils:2.31.1-SNAPSHOT
    +-org.mockito:mockito-core:3.5.2
      +-org.objenesis:objenesis:3.1
  
### Expected Results:

Ideally, dozer would be updated to use objenesis version 3.1

Of course, other workarounds may be applied, e.g. downgrading objenesis  to 2.6 through maven pom, but dozer using latest objenesis would be ideal.

**Comment by garethahealy** [comment]
@holgerhaag  ; if you want to open a PR to fix, am happy to review/merge.

**Comment by holgerhaag** [comment]
Thanks!
