### ISSUE TITLE
How to turn off Dozer logging entries using log4j2 ?

### ISSUE THREAD

**Issue by kmmahesh** [DozerMapper/dozer#803]
How to turn off Dozer logging entries using log4j2 ?
Using Java 1.8,  Dozer version: 6.4.1, Logger version 2.11.2 on Windows 7 
pom.xml config
`<groupId>com.github.dozermapper</groupId>`
`<artifactId>dozer-core</artifactId>`

Every time I load a web page or run a JUnit tests Dozer logs 100s of lines of logging messages which makes the application bit slow. Tried following configuration in log4j2.xml to turn off Dozer messages but it doesn't turn off Dozer INFO messages. 
`        
>        <Configuration xmlns="http://logging.apache.org/log4j/2.0/config" status="WARN">
>
>             
>
>            <Loggers>
>	           <Root level="debug">
>		       <AppenderRef ref="STDOUT" />
>		       <AppenderRef ref="FILE" />
>	           </Root>
>	       </Loggers>
>
>	   	
>	   <category name="com.github.DozerBeanMapperBuilder">
>	       <priority value="OFF" />
>	   </category>	
>	   <category name="com.github.dozermapper.core.builder.xml.BeanMappingXMLBuilder">
>	       <priority value="OFF" />
>	   </category>
>	   <category name="com.github.dozermapper.core.config.resolvers.LegacyPropertiesSettingsResolver">
>	       <priority value="OFF" />
>	   </category>
>	   <category name="com.github.dozermapper.core.util.RuntimeUtils">
>	       <priority value="OFF" />
>	   </category>
>	   <category name="com.github.dozermapper.core.el.ELExpressionFactory">
>	       <priority value="OFF" />
>	   </category>
>	   <category name="com.github.dozermapper.core.builder.xml.SchemaLSResourceResolver">
>	       <priority value="OFF" />
>	   </category>
>     </Configuration>`

Any suggestions as how to turn off Dozer logging messages? Thanks.

**Comment by zemochen** [comment]
`
<loggers>
		
		<logger name="com.github.dozermapper" level="ERROR"/>
		<root level="info">
			<appender-ref ref="Console" />
		</root>
	</loggers>
</configuration>
`
