### ISSUE TITLE
Trying to map String (dd-MMM-yyyy HH:mm:ss) -> java.sql.Timestamp but mapper exceptions

### ISSUE THREAD

**Issue by alpizano** [DozerMapper/dozer#808]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: _____
* OS version: macOS
* JDK version:8
  
## Whats the problem?
_Steps to reproduce:_
1. I was Trying to map a String (dd-MMM-yyyy HH:mm:ss) to a Timestamp ie. "30-Apr-2020 23:59:59" -> java.sql.Timestamp

I have other Strings in the dd-MMM-yyyy format, and my default date format in y Dozer config is dd-MMM-yyy and this seems to map just FINE with my other java.sql.timestamp data types in my entity/DB classes.

I wanted to see if this could be done without using a custom converted, and only editing the .xml dozer config, and without changing my db java.sql.timestamp datatypes, but it seems, everytime I add TIME (HH:mm:ss) to my String, everything messes up.

 I was trying to follow this guide where they map a String to a Date by declaring the date-format in the .xml config:
```
<field>
  <a date-format="MM/dd/yyyy HH:mm:ss:SS">dateString</a>
  <b>dateObject</b>
</field>
```
http://dozer.sourceforge.net/documentation/stringtodatemapping.html

### Observed Results:
_What happened?  This could be a description, log output, etc._
I'm getting mapper exceptions.
  
### Expected Results:
_What did you expect to happen?_
The data to be converted.

## Link to GitHub repo with Unit test
_The easiest way for us to fix issues, is if you provide a GitHub repo, using the latest release and a simple unit test._

**Comment by garethahealy** [comment]
@alpizano ; can you share the exception?
