### ISSUE TITLE
Deploy 6.5.1 on maven

### ISSUE THREAD

**Issue by javathought** [DozerMapper/dozer#812]
v6.5.1 is released but no available on maven 

![image](https://user-images.githubusercontent.com/1075135/113740921-72b29600-9701-11eb-9409-90428a9e133b.png)

It's an important release, that includes an upgrade on a dep with CVE

**Comment by garethahealy** [comment]
released to sonar, so should be in central in a few hours:
- https://repo.maven.apache.org/maven2/com/github/dozermapper/dozer-core/

**Comment by garethahealy** [comment]
https://repo.maven.apache.org/maven2/com/github/dozermapper/dozer-core/6.5.2/
