### ISSUE TITLE
Keeping source and target POJO outside the classpath

### ISSUE THREAD

**Issue by kaleescts** [DozerMapper/dozer#825]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: __5.5.1___
* OS version: ___Linux - CentOS__
* JDK version: _8____
  
## Whats the problem?
_Steps to reproduce:_
1. _keep the xml file of dozer mapping outside classpath, also the POJOS outside classpath____
2. _Try to run the mapper____
3. __Class not found exception is coming___
  
### Observed Results:
_What happened?  This could be a description, log output, etc._
I could  successfully load the XML files outside classpath but not the POJOs. My requirement is, i will be dynamicaaly getting many JSONs and trying to map them with an XML mapping adhoc. In this course of action, i cannot rebuild the WAR everytime keeping the POJOs inside. I am trying to keep the POJOS and Mappings outside classpath
 
### Expected Results:
_What did you expect to happen?_
I wish to load the POJOs from outside classpath and load them to classpath along with their dependencies

## Link to GitHub repo with Unit test
_The easiest way for us to fix issues, is if you provide a GitHub repo, using the latest release and a simple unit test._

**Comment by garethahealy** [comment]
does setting the classload help?
- https://github.com/DozerMapper/dozer/blob/master/core/src/main/java/com/github/dozermapper/core/DozerBeanMapperBuilder.java#L172-L185

**Comment by kaleescts** [comment]
I will check this and let u know, Thanks

**Comment by garethahealy** [comment]
presuming the classloader has worked
