### ISSUE TITLE
what's relationship with 'dozer' and 'dozer-core' of dependency 

### ISSUE THREAD

**Issue by zemochen** [DozerMapper/dozer#828]
In [http://dozer.sourceforge.net/documentation/gettingstarted.html](url) use maven dependency ：
```
<dependency>
                <groupId>net.sf.dozer</groupId>
                <artifactId>dozer</artifactId>
                <version>5.4.0</version>
                
</dependency>
```

but in github readme use：

```
<dependency>
                <groupId>com.github.dozermapper</groupId>
                <artifactId>dozer-core</artifactId>
                <version>6.4.1</version>
</dependency>
```

so what's the relationship with them? which one is more stable?

**Comment by garethahealy** [comment]
https://github.com/DozerMapper/dozer/blob/master/docs/asciidoc/migration/v5-to-v6.adoc#2-maven-gav-group-id-artifact-and-version-has-changed
