### ISSUE TITLE
CustomConverter not able to be set by withCustomConverter within DozerBeanMapperBuilder

### ISSUE THREAD

**Issue by am185652** [DozerMapper/dozer#829]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: 5.5.1
* OS version: Big Sur
* JDK version: 11
  
## Whats the problem?
When creating a builder, the function withcustomconverter does not set the value of customconverter.
_Steps to reproduce:_
1. Create DozerBeanMapperBuilder
2. Use custom converter implemented from CustomConverter.
  
### Observed Results:
_What happened?  This could be a description, log output, etc._
customConverters = {ArrayList@16643} size = 0
### Expected Results:
_What did you expect to happen?_
I expect for the customconverter to be used within the mapper.
## Link to GitHub repo with Unit test
_The easiest way for us to fix issues, is if you provide a GitHub repo, using the latest release and a simple unit test._

**Comment by garethahealy** [comment]
like this?
- https://github.com/DozerMapper/dozer/blob/master/core/src/test/java/com/github/dozermapper/core/converters/CustomConverterThreadSafetyTest.java#L52-L55

**Comment by am185652** [comment]
Yes. My implementation is 
`ItemCustomConverter customConverter = new ItemCustomConverter(objectMapper);
        Mapper mapper = DozerBeanMapperBuilder
                .create()
                .withMappingBuilder(builder)
                .withCustomConverter(customConverter)
                .build();`

**Comment by am185652** [comment]
This is my BeanMappingBuilder

`BeanMappingBuilder builder = new BeanMappingBuilder() {
            protected void configure() {
                mapping(ClassA.class, ClassB.class, mapNull(false));
            }
        };`
I see a usage of customconverter within the field set, is that required for the customconverter to be set within the mapper creation?

**Comment by am185652** [comment]
I guess another way to phrase my issue is I am trying to implement my own custom converter only using the API rather than the xml mappings. So is `withCustomConverter` supposed to be able to be used without the use of xml?
