### ISSUE TITLE
dozer can not work for springboot 3 

### ISSUE THREAD

**Issue by huihui-hb** [DozerMapper/dozer#843]
## Whats your runtime?
* Dozer version:  lastest
* OS version: win
* JDK version: 17
  
## Whats the problem?
1 required dozer and springboot 3
2 init dozer
  
### Observed Results:
throw exception :
`
java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
`
  
###
Do you have plan to make dozermapper support springboot3.0.0 , thks

**Comment by garethahealy** [comment]
Simple answer; sorry, I dont have time. Longer answer; if you want to update dozer to work on SB3, I am happy to review/merge.
- https://github.com/DozerMapper/dozer#project-activity

**Comment by rivancic** [comment]
@huihui-hb this isn't SB3 issue.
Dozer is dependent on JAXB-API. JAXB was part of Java core. Now with latest Java version it isn't anymore.
You have upgraded your module to Java 17.
You'll have to declare those dependencies yourself https://jesperdj.com/2018/09/30/jaxb-on-java-9-10-11-and-beyond/

**Comment by garethahealy** [comment]
@bender316 ; if your willing to do a PR, I am happy to merge/release.

**Comment by bender316** [comment]
Yeah, I know. If a maintaner tells you to run you'd better run. Dozer is used in a lot of services in our environment. As the update to SB3 already brought us a lot of tasks (and other migrations) I consider it a valid option to stay with Dozer for the time being.

Long term I totally agree with you. So lets see what happens.

**Comment by RuslanHryn** [comment]
forked dozer and migrated to Jakarta to unblock migration to Spring Boot 3.
here is repo https://github.com/RuslanHryn/dozer-jakarta
feel free to contribute and test it

**Comment by bender316** [comment]
> However, I would strongly suggest you move away from dozer.

In the long run we "migrated" to ModelMapper. The effort was much less than anticipated.
