### ISSUE TITLE
Dozer to Mapstruct Intellij plugin.

### ISSUE THREAD

**Issue by vivek-dhayalan** [DozerMapper/dozer#845]
Hi Team,

As the project is heading to sunset, we have decided to migrate to mapstruct for one of the enterprise application that we're working on and happen to realize that migration is consuming lot of time as we need to be careful and not miss-out anything, so we decided to automate the basic steps and came up with a plugin Idea that can help in migration.

Sharing this plugin with you so that it can help the community if they're in the process of migration

https://plugins.jetbrains.com/plugin/20853-dostruct

Feel free to add this plugin in readme.

**Comment by garethahealy** [comment]
added: https://github.com/DozerMapper/dozer/commit/6ce2405370e3cc035f4c4155b9f7e9b7b92c25c8
