### ISSUE TITLE
Not able to start the Server(Wildfly 18 ) while updating the Dozer-Core 6.5.2 jars

### ISSUE THREAD

**Issue by Sanjeeb-21** [DozerMapper/dozer#854]
## Are you in the right place?
* For issues or feature requests related to the code **in this repository** file a Github issue.
* For general technical questions, post a question on [Google Groups](https://groups.google.com/forum/?fromgroups=#!forum/dozer-mapper).

## Whats your runtime?
* Dozer version: 6.5.2
* Dozer-Spring4: 6.5.2
* OS version: Windows 10
* JDK version: JDK 11 
  
## Whats the problem?
_Steps to reproduce:_
1. Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.github.dozermapper.core.config.BeanContainer' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}"}}
11:43:01,797 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 35) WFLYSRV0010: Deployed "napier-his-web.war" (runtime-name : "napier-his-web.war")
11:43:01,800 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."napier-his-web.war".undertow-deployment: java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'enecoreservice': Unsatisfied dependency expressed through field 'registrationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.napier.core.registration.service.external.RegistrationService': Unsatisfied dependency expressed through field 'regCoreService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'registrationCoreService': Unsatisfied dependency expressed through field 'customDozerBeanMapper'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'CustomDozerBeanMapper' defined in class path resource [dozer-spring.xml]: Cannot resolve reference to bean 'javaBeanMapper' while setting bean property 'inboundMapperBean'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'javaBeanMapper' defined in class path resource [dozer-spring.xml]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.github.dozermapper.core.config.BeanContainer' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: [{}]([server.log](https://github.com/DozerMapper/dozer/files/12046912/server.log))
2. _____
3. _____
  
### Observed Results:
_What happened?  This could be a description, log output, etc._
  
### Expected Results:
_What did you expect to happen?_

## Link to GitHub repo with Unit test
_The easiest way for us to fix issues, is if you provide a GitHub repo, using the latest release and a simple unit test._

**Comment by garethahealy** [comment]
Dozer is only tested against wildfly10
- https://github.com/DozerMapper/dozer/blob/master/tests/dozer-wildfly-tests/pom.xml#L40

if you want it tested against 18, you'll need to update as the project isn't active.
