### ISSUE TITLE
Dozer loose information when mapping non-cumulative collection (set) that contain objects with one-way properties

### ISSUE THREAD

**Issue by hares2** [DozerMapper/dozer#90]
This one occurs when we maps a graph containing a set in no-cumulative-relationship (that contain objects with one-way properties) to another graph containing also a set. 

Therefore all sub-elements (with some one-way properties that are already setted) in the elements set of destination are build from scratch (because Dozer returns null when it calls getExistingValue --> because source is a set and destination isn't a set) and mapped from the source, and in the case where some properties of these elements are one-way, we lose those informations !

**Comment by garethahealy** [comment]
Closing due to workarounds provided.
