### ISSUE TITLE
Performance Benchmark Suite

### ISSUE THREAD

**Issue by buzdin** [DozerMapper/dozer#94]
Results to be gathered and stored for every release
http://labs.carrotsearch.com/junit-benchmarks.html

**Comment by garethahealy** [comment]
As per link, move to:
- http://openjdk.java.net/projects/code-tools/jmh/

**Comment by garethahealy** [comment]
See comment for further improvements needed:
- https://github.com/DozerMapper/dozer/pull/431#issuecomment-308235977
